### ISSUE TITLE
StorageException: Failed to acquire storage lock

### ISSUE THREAD

**Issue by imsuperman0920** [camunda-cloud/zeebe#3082]
hi
My zeebe version is 0.20 and the exception as below:
 io.atomix.storage.StorageException: Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory

how to configurate the cluster ?
Pls help ~

**Comment by imsuperman0920** [comment]
i have fixed it . This can be closed.

**Comment by Zelldon** [comment]
Would you mind to share what was the problem and how you fixed that, so other users can benefit from that?

**Comment by ysaakpr** [comment]
I am also running into same problem, How did you fix this

**Comment by PinoNTK** [comment]
@imsuperman0920 I have encountered the same problem, can you share how to solve it with us?

**Comment by saig0** [comment]
This failure occurred again.

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
..
Caused by: java.util.concurrent.CompletionException: io.atomix.raft.storage.StorageException: 
Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory
..
Caused by: io.atomix.raft.storage.StorageException: Failed to acquire storage lock; 
ensure each Raft server is configured with a distinct storage directory
```

```
Bootstrap Broker-1 [6/14]: cluster services failed with unexpected exception.
..
Closing Broker-1 [4/5]: membership and replication protocol failed to close.
..
Failed to start broker 1!
..
Application run failed
```

Version: `1.0.0-SNAPSHOT`
Environment: Camunda Cloud (ultratest) 
Configuration: 1 partition, replication factor 3

Error Reporting: https://console.cloud.google.com/errors/CPafl_PD5beB7wE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
Log: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22c260dd2a-0638-4191-8877-1dd7f1961758-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2021-04-13T06:30:42.591Z%2F2021-04-14T03:30:42.591Z;pinnedLogId=2021-04-13T16:43:13.244692Z%2F1l5seozg536c1v2;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2021-04-13T16:43:15.389923Z?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: io.atomix.raft.storage.StorageException: Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:119) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.atomix.raft.storage.StorageException: Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:138) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 29 more

```

</p>
</details>

**Comment by deepthidevaki** [comment]
Caused by PR https://github.com/camunda-cloud/zeebe/pull/6779 which changed the format in which memberId is written to the lock file. It is expected as we don't guarantee compatability in  SNAPSHOT images.
