### ISSUE TITLE
Zeebe-Operate: Crashed with report

### ISSUE THREAD

**Issue by dinilv** [camunda-cloud/zeebe#3599]
**Describe the bug**
Zeebe-operate has crashed and restarted after running workflows.

**To Reproduce**
Deployed in Kubernetes with helm-charts

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**
Zeebe-Operate should work

**Log/Stacktrace**
operate crash logs

```
org.camunda.operate.exceptions.OperateRuntimeException: Exception occurred, while obtaining finished workflow instances: Request cannot be executed; I/O reactor status: STOPPED
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:128) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.archiveNextBatch(ArchiverJob.java:109) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.run(ArchiverJob.java:89) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.camunda.operate.archiver.ArchiverJob.runSearch(ArchiverJob.java:190) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:122) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        ... 9 more

2020-01-06 09:33:07.852 DEBUG 6 --- [       Thread-1] o.c.o.z.RecordsReader                    : No index found for alias zeebe-record-variable-document
2020-01-06 09:33:07.861 DEBUG 6 --- [       Thread-1] o.c.o.z.RecordsReader                    : No index found for alias zeebe-record-variable-document
2020-01-06 09:33:08.196 DEBUG 6 --- [       Thread-1] o.c.o.z.RecordsReader                    : No index found for alias zeebe-record-variable-document
2020-01-06 09:33:09.489 DEBUG 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Finished workflow instances for archiving request:
{
  "constant_score" : {
    "filter" : {
      "bool" : {
        "must" : [
          {
            "range" : {
              "endDate" : {
                "from" : null,
                "to" : "now-1h",
                "include_lower" : true,
                "include_upper" : true,
                "boost" : 1.0
              }
            }
          },
          {
            "term" : {
              "joinRelation" : {
                "value" : "workflowInstance",
                "boost" : 1.0
              }
            }
          },
          {
            "terms" : {
              "partitionId" : [
                1,
                2,
                3
              ],
              "boost" : 1.0
            }
          }
        ],
        "adjust_pure_negative" : true,
        "boost" : 1.0
      }
    },
    "boost" : 1.0
  }
}
 and aggregation:
{"datesAgg":{"date_histogram":{"field":"endDate","format":"basic_date","interval":"1d","offset":0,"order":{"_key":"asc"},"keyed":true,"min_doc_count":0},"aggregations":{"instancesAgg":{"top_hits":{"from":0,"size":100,"version":false,"seq_no_primary_term":false,"explain":false,"_source":{"includes":["id"],"excludes":[]},"sort":[{"id":{"order":"asc"}}]}},"datesSortedAgg":{"bucket_sort":{"sort":[{"_key":{"order":"asc"}}],"from":0,"size":1,"gap_policy":"SKIP"}}}}}
2020-01-06 09:33:09.497 ERROR 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Exception occurred, while obtaining finished workflow instances: Request cannot be executed; I/O reactor status: STOPPED

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.camunda.operate.archiver.ArchiverJob.runSearch(ArchiverJob.java:190) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:122) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.archiveNextBatch(ArchiverJob.java:109) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.run(ArchiverJob.java:89) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

2020-01-06 09:33:09.498 ERROR 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Error occurred while archiving data. Will be retried.

org.camunda.operate.exceptions.OperateRuntimeException: Exception occurred, while obtaining finished workflow instances: Request cannot be executed; I/O reactor status: STOPPED
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:128) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.archiveNextBatch(ArchiverJob.java:109) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.run(ArchiverJob.java:89) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.camunda.operate.archiver.ArchiverJob.runSearch(ArchiverJob.java:190) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:122) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        ... 9 more

2020-01-06 09:33:11.500 DEBUG 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Finished workflow instances for archiving request:
{
  "constant_score" : {
    "filter" : {
      "bool" : {
        "must" : [
          {
            "range" : {
              "endDate" : {
                "from" : null,
                "to" : "now-1h",
                "include_lower" : true,
                "include_upper" : true,
                "boost" : 1.0
              }
            }
          },
          {
            "term" : {
              "joinRelation" : {
                "value" : "workflowInstance",
                "boost" : 1.0
              }
            }
          },
          {
            "terms" : {
              "partitionId" : [
                1,
                2,
                3
              ],
              "boost" : 1.0
            }
          }
        ],
        "adjust_pure_negative" : true,
        "boost" : 1.0
      }
    },
    "boost" : 1.0
  }
}
 and aggregation:
{"datesAgg":{"date_histogram":{"field":"endDate","format":"basic_date","interval":"1d","offset":0,"order":{"_key":"asc"},"keyed":true,"min_doc_count":0},"aggregations":{"instancesAgg":{"top_hits":{"from":0,"size":100,"version":false,"seq_no_primary_term":false,"explain":false,"_source":{"includes":["id"],"excludes":[]},"sort":[{"id":{"order":"asc"}}]}},"datesSortedAgg":{"bucket_sort":{"sort":[{"_key":{"order":"asc"}}],"from":0,"size":1,"gap_policy":"SKIP"}}}}}
2020-01-06 09:33:11.501 ERROR 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Exception occurred, while obtaining finished workflow instances: Request cannot be executed; I/O reactor status: STOPPED

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.camunda.operate.archiver.ArchiverJob.runSearch(ArchiverJob.java:190) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:122) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.archiveNextBatch(ArchiverJob.java:109) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.run(ArchiverJob.java:89) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

2020-01-06 09:33:11.506 ERROR 6 --- [     archiver_1] o.c.o.a.ArchiverJob                      : Error occurred while archiving data. Will be retried.

org.camunda.operate.exceptions.OperateRuntimeException: Exception occurred, while obtaining finished workflow instances: Request cannot be executed; I/O reactor status: STOPPED
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:128) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.archiveNextBatch(ArchiverJob.java:109) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.run(ArchiverJob.java:89) [camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:537) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:520) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:232) ~[elasticsearch-rest-client-6.8.4.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.5.jar!/:6.8.5]
        at org.camunda.operate.archiver.ArchiverJob.runSearch(ArchiverJob.java:190) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        at org.camunda.operate.archiver.ArchiverJob.queryFinishedWorkflowInstances(ArchiverJob.java:122) ~[camunda-operate-archiver-1.2.0-alpha2.jar!/:?]
        ... 9 more

```

**Environment:**
 - OS: Kuberntes
 - Zeebe Version: 0.22
 - Configuration:NA

**Comment by Zelldon** [comment]
Hey @dinilv 

sorry for the late response.

Does this issue still exist?
Have you resolved it?

Greets
Chris

**Comment by npepinpe** [comment]
I will close this as inactive.
