### ISSUE TITLE
Investigate why we often see 'already Completed job' exceptions

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#3765]
**Description**

I think we already checked that, but I'm not 100% sure. I would like to understand why we sometimes see a lot of logs which say:

```
I 2020-01-30T03:37:53.166794958Z io.grpc.StatusRuntimeException: NOT_FOUND: Command rejected with code 'COMPLETE': Expected to complete job with key '4503599648142663', but no such job was found
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:382) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:307) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$1(BrokerRequestManager.java:116) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:138) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:181) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
Caused by: io.zeebe.gateway.cmd.BrokerRejectionException: Command (COMPLETE) rejected (NOT_FOUND): Expected to complete job with key '4503599648142663', but no such job was found
	... 10 more
 
I 2020-01-30T03:37:53.166906298Z io.grpc.StatusRuntimeException: NOT_FOUND: Command rejected with code 'COMPLETE': Expected to complete job with key '4503599648142661', but no such job was found
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:382) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:307) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$1(BrokerRequestManager.java:116) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:138) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:181) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
Caused by: io.zeebe.gateway.cmd.BrokerRejectionException: Command (COMPLETE) rejected (NOT_FOUND): Expected to complete job with key '4503599648142661', but no such job was found
	... 10 more
 
I 2020-01-30T03:37:53.166993344Z io.grpc.StatusRuntimeException: NOT_FOUND: Command rejected with code 'COMPLETE': Expected to complete job with key '4503599648142657', but no such job was found
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:382) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:307) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$1(BrokerRequestManager.java:116) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:138) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:181) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
Caused by: io.zeebe.gateway.cmd.BrokerRejectionException: Command (COMPLETE) rejected (NOT_FOUND): Expected to complete job with key '4503599648142657', but no such job was found
	... 10 more
 
I 2020-01-30T03:37:53.167099164Z io.grpc.StatusRuntimeException: NOT_FOUND: Command rejected with code 'COMPLETE': Expected to complete job with key '4503599648142625', but no such job was found
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:382) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.EndpointManager.lambda$sendRequest$3(EndpointManager.java:307) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$1(BrokerRequestManager.java:116) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:138) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:181) ~[zeebe-gateway-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
Caused by: io.zeebe.gateway.cmd.BrokerRejectionException: Command (COMPLETE) rejected (NOT_FOUND): Expected to complete job with key '4503599648142625', but no such job was found
	... 10 more
 
```

This makes sense when the worker takes to long to complete the job, but in our benchmark we do not much. For that reason I dont expect that exception.

**Comment by npepinpe** [comment]
Are we sure it's because it was already completed? :thinking:

**Comment by Zelldon** [comment]
It was actually an assumption 😅

**Comment by npepinpe** [comment]
Just spitballing here, so possible options are:

1. The job was already completed somewhere else - could verify this in Elasticsearch?
1. The job was cancelled because the instance terminated - could also verify this in Elasticsearch?
1. The job disappeared :scream: - not sure, what are other cases where we would delete it? We could maybe check RocksDB ourselves I guess?
1. An error in the client/worker - some race condition here? We could log all sent requests and should see some duplicates
1. An error in the benchmark app - same as above I guess?

**Comment by Zelldon** [comment]
I think either problem in client were it sends twice or it was completed from another client. Or yes bug in  RocksDB which I think is less likely then the other things. Cancel should not happen since we do not send any cancel in the benchmarks.

**Comment by Zelldon** [comment]
I think I checked it with kibana once and saw that it was already completed but we should check it again.

**Comment by npepinpe** [comment]
Happened on my benchmark, and worst of all is that it happened on a node which was not even leader of anything (since a long time) :scream:

**Comment by Zelldon** [comment]
Embedded Gateway which run on this node probably?

**Comment by npepinpe** [comment]
Hypothesis is this is expected behaviour if your worker acquires a lot of job but the job lock times out before the worker can complete it, and another worker acquires and completes it first.

**Comment by Zelldon** [comment]
I think we can close it. Cant remember when I have seen that last time and if so it was because of the reasons mentioned above.
