### ISSUE TITLE
RaftAppendTest.shouldAppendEntryOnAllNodes

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#4540]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? - occurred at least once
- Does it block your work? - no
- Do we suspect that it is a real failure? - unknown

**Failures**

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/600

<details><summary>Example assertion failure</summary>
<pre>
Error Message

[Entry comparison 1 vs 2] 
Expecting:
  <[Indexed{index=1, entry=InitializeEntry{term=1, timestamp=2020-05-14 05:12:43,100}}]>
to contain exactly (and in same order):
  <[Indexed{index=1, entry=InitializeEntry{term=1, timestamp=2020-05-14 05:12:43,100}},
    Indexed{index=2, entry=ZeebeEntry{term=1, timestamp=1589476363383, lowestPosition=1, highestPosition=11}}]>
but could not find the following elements:
  <[Indexed{index=2, entry=ZeebeEntry{term=1, timestamp=1589476363383, lowestPosition=1, highestPosition=11}}]>

Stacktrace

java.lang.AssertionError: 
[Entry comparison 1 vs 2] 
Expecting:
  <[Indexed{index=1, entry=InitializeEntry{term=1, timestamp=2020-05-14 05:12:43,100}}]>
to contain exactly (and in same order):
  <[Indexed{index=1, entry=InitializeEntry{term=1, timestamp=2020-05-14 05:12:43,100}},
    Indexed{index=2, entry=ZeebeEntry{term=1, timestamp=1589476363383, lowestPosition=1, highestPosition=11}}]>
but could not find the following elements:
  <[Indexed{index=2, entry=ZeebeEntry{term=1, timestamp=1589476363383, lowestPosition=1, highestPosition=11}}]>

	at io.atomix.raft.RaftAppendTest.assertMemberLogs(RaftAppendTest.java:96)
	at io.atomix.raft.RaftAppendTest.shouldAppendEntryOnAllNodes(RaftAppendTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

17:12:42.177 [] INFO  io.zeebe.test - Test finished: shouldAppendEntriesOnAllNodes[1: RaftRule with 3 nodes.](io.atomix.raft.RaftAppendTest)
17:12:42.177 [] INFO  io.zeebe.test - Test started: shouldAppendEntryOnAllNodes[1: RaftRule with 3 nodes.](io.atomix.raft.RaftAppendTest)
17:12:42.201 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to FOLLOWER
17:12:42.287 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to FOLLOWER
17:12:42.392 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to FOLLOWER
17:12:43.072 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - No heartbeat from null in the last PT0.836S (calculated from last 868 ms), sending poll requests
17:12:43.074 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to CANDIDATE
17:12:43.075 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{1}{role=CANDIDATE} - Starting election
17:12:43.099 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to LEADER
17:12:43.100 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Found leader 1
17:12:43.107 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Found leader 1
17:12:43.107 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Found leader 1
17:12:43.404 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1} - Transitioning to INACTIVE
17:12:43.404 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{3} - Transitioning to INACTIVE
17:12:43.412 [] WARN  io.atomix.utils.concurrent.SingleThreadContext - Execution of io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@4adcea6 was rejected!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@72793ab6[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@aecf499[Wrapped task = io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@4adcea6]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@55fda172[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2164]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.execute(SingleThreadContext.java:56) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext.execute(SingleThreadContext.java:150) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:850) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$18(RaftContext.java:226) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:223) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
17:12:43.414 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2} - Transitioning to INACTIVE

</pre>
</details>

**Comment by pihme** [comment]
Also: 
https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/623/

**Comment by Zelldon** [comment]
@pihme did we ever saw this again?

**Comment by pihme** [comment]
A couple of times:

Branch | Build # | Date | Week
-- | -- | -- | --
4340-do-not-merge-monitor-build-health-branch | 600 | 2020-05-14 | CW 20
4340-do-not-merge-monitor-build-health-branch | 623 | 2020-05-15 | CW 20
4340-do-not-merge-monitor-build-health-branch | 686 | 2020-05-18 | CW 21
4340-do-not-merge-monitor-build-health-branch | 937 | 2020-05-27 | CW 22
4340-do-not-merge-monitor-build-health-branch | 982 | 2020-05-29 | CW 22
4340-do-not-merge-monitor-build-health-branch | 1140 | 2020-06-04 | CW 23
4340-do-not-merge-monitor-build-health-branch | 1165 | 2020-06-05 | CW 23

**Comment by pihme** [comment]
Haven't updated the statistics for last week yet

**Comment by Zelldon** [comment]
thanks @pihme

**Comment by deepthidevaki** [comment]
This is probably fixed by #5028

**Comment by Zelldon** [comment]
seems to be fixed

**Comment by Zelldon** [comment]
Happend again

**Comment by Zelldon** [comment]
same here https://github.com/camunda-cloud/zeebe/issues/5003#issuecomment-814752460
