### ISSUE TITLE
Task seem sometimes not scheduled

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#4715]
**Describe the bug**
To be honest idk how bad it is, but I saw this in several benchmarks quite often also in out test suite that sometimes task are rejected and not scheduled. 

The following message `Execution of io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@3a9071c6 was rejected!` and exception is printed then
```
"java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@437989b0[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2e67d1e0[Wrapped task = io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable@3a9071c6]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@42c157e9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 764]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.execute(SingleThreadContext.java:56) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext.execute(SingleThreadContext.java:150) ~[atomix-utils-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$17(NettyMessagingService.java:482) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-29.0-jre.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$18(NettyMessagingService.java:482) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.completeExceptionally(AbstractClientConnection.java:186) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.close(AbstractClientConnection.java:123) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$getOrCreateClientConnection$30(NettyMessagingService.java:551) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:431) [netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) [netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
" 

```

**To Reproduce**
Just run a RaftTest or a benchmark.

**Expected behavior**
I dont know what the impact is actually.

**Comment by Zelldon** [comment]
Cant tell what the severity nor the impact is, since idk.

**Comment by deepthidevaki** [comment]
I think you get "RejectedExecutionException" when the executor is not running. So I expect this errors only during startup or shutdown.  If it happens during normal run then there might be a problem.

**Comment by npepinpe** [comment]
Can we confirm if this happens "normally" or not?

**Comment by npepinpe** [comment]
First step is to determine the severity, whether or not this is expected; second step would be to figure out how to track cases where it would not be expected such that we can log them as errors and react on them.

**Comment by npepinpe** [comment]
Can confirm that the error above occurs in a ThreadPoolExecutor when it's already shut down/shutting down. Netty also sometimes throws this exception but with a different error message - however, it also does so when shutting down/was shut down.

I think we can close this for now - I'm happy to look at issues where we want to tackle specific instances where "it was shut down but shouldn't have been", or "we should handle this gracefully in this particular case".
