### ISSUE TITLE
NullPointerException in AtomixLogStorageReader

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#4806]
**Describe the bug**

With the benchmark from yesterday, a new error popped up: https://console.cloud.google.com/errors/CMnI1sSGr8atxAE?service=zeebe-broker&version=snapshot-20200622&time=P1D&project=zeebe-io

NullPointerException: null in
`io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.findEntry` (`AtomixLogStorageReader.java:157`)

It occurred during fail over - or rather, when the stream processor is recovering. It's unclear why or how, someone would have to investigate that cluster.

**To Reproduce**

Not sure, this happened during a running benchmark.

**Expected behavior**

Never expect an NPE :slightly_smiling_face: And if it's expected we should handle it

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.findEntry(AtomixLogStorageReader.java:157) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.read(AtomixLogStorageReader.java:55) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.lambda$readBlockIntoBuffer$1(LogStreamReaderImpl.java:193) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.executeReadMethod(LogStreamReaderImpl.java:197) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readBlockIntoBuffer(LogStreamReaderImpl.java:192) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextAddress(LogStreamReaderImpl.java:225) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextEvent(LogStreamReaderImpl.java:243) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:176) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:20) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:156) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:133) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:111) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.24.0-SNAPSHOT from 2020-06-22
 - Configuration: benchmark setup

**Comment by npepinpe** [comment]
One hypothesis, check if we had an OOM right before as we now exit on out of memory error.

**Comment by Zelldon** [comment]
@npepinpe I remove my assigment since I think it is unrelated to https://github.com/zeebe-io/zeebe/issues/4807

**Comment by npepinpe** [comment]
My understanding is this is only possible due to OOM, where some things are simply not executed and the reader ends up in a weird state. Why? If you look at line 157, you can see that there's two possibilities for the null exception:

1. `entry` is null
1. `entry.type()` is null

Barring a recovered OOM, `entry` will not be null. Do `#next()` on a reader will go through the following paths:

1. `SegmentedJournalReader` => three possible paths -> it's in the current segment (goes to `MappableJournalSegmentReader#next()`), it's in another segment (also goes to `MappableJournalSegmentReader#next()` 
when the segment is found), it's not in any segments (a `NoSuchElementException` is thrown).
1. `MappableJournalSegmentReader#next()` will simply delegate to one of `MappedJournalSegmentReader#next()` or `FileChannelJournalSegmentReader#next()` - as we don't use the mapped one, we can ignore it for now. 
1. `FileChannelJournalSegmentReader#next()` will not return null - if `nextEntry` is null, then a `NoSuchElementException` is thrown. If not, then it's assigned to `currentEntry`, the next entry is read, and I couldn't find any modification of `currentEntry` until it's returned. 

So, barring a concurrent modification or a recovered OOM, `currentEntry` is not null and will be returned, and `entry` will not be null.

What about `entry.type()`? Here I have to mention a caveat - `entry` so far refers to an `Indexed<>` instance, which itself has an `entry` property - it's a little confusing I admit. So when we call `entry.type()`, it actually calls the `getClass()` method of the `entry` property of the `Indexed<>` instance, e.g. `entry.getEntry().getClass()`. However, afaik, if `entry.getEntry()` were to return null, the exception would be thrown in `Indexed#type()` method, not in the reader, so it's most likely that `entry.getEntry()` is not null. As far as I know, it's not possible for Java to return `null` when calling `getClass()`, but maybe there's some edge case where this is true?

My best bet is that we have somehow a race condition which causes the concurrent modification, as we know the readers are not thread safe. 

As making the readers thread safe is a bigger topic, my suggestion for now would be to add a guard clause for both cases regardless - I hope we refactor the journal in the future and this problem would then go away.

**Comment by npepinpe** [comment]
Adding to the Journal Refactor milestone - please verify after if this is still an issue, and possibly close it.

**Comment by npepinpe** [comment]
Closing for now as we rewrote most of the related code.
