### ISSUE TITLE
Lost partition is not recovered automatically.

### ISSUE THREAD

**Issue by sergeylebed** [camunda-cloud/zeebe#5337]
**Describe the bug**
Node 0 has lost a partition without being able to automatically restore.

```
NodeId: 0,
 Port: 26501,
 Partitions:
  PartitionId: 1,  IsLeader: True,  Role: LEADER,   
  PartitionId: 2,  IsLeader: True,  Role: LEADER,
 NodeId: 2,
 Port: 26501,
 Partitions:
  PartitionId: 1,  IsLeader: False,  Role: FOLLOWER,   
  PartitionId: 2,  IsLeader: False,  Role: FOLLOWER,   
  PartitionId: 3,  IsLeader: True,  Role: LEADER,
 NodeId: 1,
 Port: 26501,
 Partitions:
  PartitionId: 1,  IsLeader: False,  Role: FOLLOWER,   
  PartitionId: 2,  IsLeader: False,  Role: FOLLOWER,   
  PartitionId: 3,  IsLeader: False,  Role: FOLLOWER
```

**To Reproduce**
There's no precise steps to reproduce. The cluster was running for some time and got into this state. There's no known external events that might trigger it. There's permanent small load on the cluster. 

**Expected behavior**
The partition should be automatically recovered from other brokers with manual interference.

**Log/Stacktrace**
Node 0: 
```
2020-09-09 12:56:42.393 [Broker-0-LogAppender-3] [Broker-0-zb-actors-1] ERROR io.zeebe.logstreams - Failed to append block with last event position 2390089.
java.util.NoSuchElementException: Expected an appender, but none found, most likely we are not the leader
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorage.append(AtomixLogStorage.java:57) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.appendBlock(LogStorageAppender.java:114) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.onWriteBufferAvailable(LogStorageAppender.java:164) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
```

Node 2:
```
2020-09-10 12:10:53.621 [] [raft-server-2-raft-partition-partition-3] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-3} - AppendRequest{term=298, leader=2, prevLogIndex=1983884, prevLogTerm=297, entries=0, commitIndex=2074829} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-append timed out in 5000 milliseconds
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-append timed out in 5000 milliseconds
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$17(NettyMessagingService.java:509) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-29.0-jre.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$18(NettyMessagingService.java:509) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:163) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-append timed out in 5000 milliseconds
```

**Environment:**
 - OS: Kubernetes
 - Zeebe Version: 0.24.2
 - Configuration:  3 nodes, 3 partitions, 3 replication factor.

**Comment by npepinpe** [comment]
Hi @sergeylebed, sorry for the slow response, I have some questions to better understand what happened, though I imagine after so much time you may not have all the information any more unfortunately.

Broker 0 is missing a partition, which implies partition 3 is the one which died on the broker. Do you have any logs related to it which show it going inactive? It would specifically say something like "transition to inactive" or some such. 

As well for broker 0, the log you added is not too dangerous, as it may indicate that failover is due to the followers triggering an election, and broker 0 simply being a little behind. So if you had a short bursts of these messages that may indicate there's an issue, but that it's probably recoverable. So I'd be interesting to know if there were any other errors or warnings there?

Finally, did the system ever recover? e.g. if the broker restarted, was it then running fine?

**Comment by sergeytest2014** [comment]
Hi @npepinpe , unfortunately, no logs are preserved from that incident. The problem was that the cluster stuck in this state for a long, that we lost our hope on self-recovery. As far as I remember, we had to delete all the data on node-0 and several time restarted the cluster and eventually it came to life.

**Comment by sergeylebed** [comment]
Hi @npepinpe , unfortunately, no logs are preserved from that incident. The problem was that the cluster stuck in this state for a long, that we lost our hope on self-recovery. As far as I remember, we had to delete all the data on node-0 and several time restarted the cluster and eventually it came to life.

**Comment by npepinpe** [comment]
Unfortunately without more information it's difficult for us to pinpoint what happened. I will close this for now, but please reopen if you ever run into this, and if possible provide us with the data folder of the brokers as well as their logs.
