### ISSUE TITLE
IllegalStateException: Iterator is closed (ReProcessingStateMachine)

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5504]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK_M1tm5u9mg6QE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2

**Comment by pihme** [comment]
Occurred again:
https://github.com/zeebe-io/zeebe/issues/5504

**Comment by Zelldon** [comment]
Node becomes leader. Failed to append [because it is OoD](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-17T13:02:30.455049000Z&dateRangeStart=2020-11-17T12:24:08.680Z&dateRangeEnd=2020-11-17T14:24:08.680Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=logName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%220a8e8f1d-e7f2-4e75-a305-76a3b9001ab5-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0AjsonPayload.context.actor-name!%3D%22io.zeebe.gateway.impl.broker.BrokerRequestManager%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-17T13:03:06.920926000Z&pinnedLogId=6dusmpg2flzs8k&pinnedLogTimestamp=2020-11-17T13:02:28.780138Z)

```
io.atomix.storage.StorageException$OutOfDiskSpace: Not enough space to allocate a new journal segment
	at io.atomix.storage.journal.SegmentedJournal.assertDiskSpace(SegmentedJournal.java:294) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.atomix.storage.journal.SegmentedJournal.getNextSegment(SegmentedJournal.java:385) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.atomix.storage.journal.SegmentedJournalWriter.createNewSegment(SegmentedJournalWriter.java:133) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.9.0.jar:?]
	at io.atomix.storage.statistics.JournalMetrics.observeSegmentCreation(JournalMetrics.java:72) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.atomix.storage.journal.SegmentedJournalWriter.append(SegmentedJournalWriter.java:60) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.atomix.storage.journal.DelegatingJournalWriter.append(DelegatingJournalWriter.java:46) ~[atomix-storage-0.25.1.jar:0.25.1]
	at io.atomix.raft.roles.LeaderRole.tryToAppend(LeaderRole.java:642) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.raft.roles.LeaderRole.append(LeaderRole.java:614) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:700) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$10(LeaderRole.java:674) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.25.1.jar:0.25.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Steps down to follower closes log etc. Stream processor is still on recovery and fails because iterator was closed.

```
I 2020-11-17T13:02:26.645042Z Processor starts reprocessing, until last source event position 10028513 
D 2020-11-17T13:02:28.184422Z Detected unhealthy components. The current health status of components: {ZeebePartition-1=HEALTHY, Raft-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY, Broker-1-StreamProcessor-1=UNHEALTHY} 
E 2020-11-17T13:02:28.215879Z Partition-1 failed, marking it as unhealthy 
D 2020-11-17T13:02:28.224596Z Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY} 
D 2020-11-17T13:02:28.312238Z Recovering exporter from snapshot 
D 2020-11-17T13:02:28.390563Z Partition 1 transition complete, installed 11 resources! 
D 2020-11-17T13:02:28.400286Z Received metadata change from Broker 1, partitions {1=FOLLOWER}, terms {} and health {1=HEALTHY}. 
D 2020-11-17T13:02:28.585619Z Received metadata change from Broker 1, partitions {1=LEADER}, terms {1=19} and health {1=HEALTHY}. 
D 2020-11-17T13:02:28.713963Z Failed to append block with last event position 10028663. This can happen during a leader change. 
E 2020-11-17T13:02:28.780138Z Actor Broker-1-LogAppender-1 failed in phase STARTED. 
D 2020-11-17T13:02:28.790632Z Partition role transitioning from LEADER to FOLLOWER 
D 2020-11-17T13:02:28.791065Z Closing Zeebe-Partition-1: ExporterDirector 
I 2020-11-17T13:02:28.800553Z Close appender for log stream logstream-raft-partition-partition-1 
E 2020-11-17T13:02:28.806521Z logstream-raft-partition-partition-1 failed, marking it as unhealthy 
D 2020-11-17T13:02:28.816371Z Dispatcher closed 
I 2020-11-17T13:02:28.821180Z On closing logstream logstream-raft-partition-partition-1 close 3 readers 
I 2020-11-17T13:02:28.821977Z Close log storage with name logstream-raft-partition-partition-1 
E 2020-11-17T13:02:28.822379Z Unexpected error on recovery happens. 
  undefined

```

**Comment by Zelldon** [comment]
Happens again on 0.25.1 btw

**Comment by npepinpe** [comment]
We expect with properly configured disk watermarks in 0.25+ that this should not happen. In case it does (e.g. misconfiguration, older version), the workaround is to resize your disk so there is more space available (you may also have to restart the node).

**Comment by npepinpe** [comment]
Possibly related to https://github.com/camunda-cloud/zeebe/issues/5517 and issues with concurrent transitions.

**Comment by npepinpe** [comment]
Closing for now, as #5517 was fixed, and we are rewriting (have rewritten?) the `ReProcessingStateMachine`.
