### ISSUE TITLE
NPE in ProcessMessageStartEventMessageNameValidator.validateMessageName

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5510]
**Describe the bug**
Observed as error in production logs.

**Expected behavior**
* no NPEs in input validation

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK-E7ry54eavQA?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by deepthidevaki** [comment]
Observed this in Camunda cloud/ prod/ 0.25.1

[log](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-12T06%3A50%3A55.633000000Z&dateRangeStart=2020-11-12T05%3A50%3A55.633Z&project=camunda-cloud-240911&minLogLevel=0&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22619e4f26-60c7-498a-91c9-456a15570c9f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.cluster_name%3D%22production%22%0Atimestamp%3D%222020-11-12T06%3A50%3A25.209876000Z%22%0AinsertId%3D%22gxlkrukb4cqei5b36%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-12T06%3A56%3A23.252633000Z&dateRangeUnbound=forwardInTime)
```
Unexpected error while processing resource '****.bpmn'
 "java.lang.NullPointerException: null
	at io.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validateMessageName(ProcessMessageStartEventMessageNameValidator.java:53) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.lambda$validate$0(ProcessMessageStartEventMessageNameValidator.java:46) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$Itr.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validate(ProcessMessageStartEventMessageNameValidator.java:46) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validate(ProcessMessageStartEventMessageNameValidator.java:25) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0(ValidationVisitor.java:51) ~[zeebe-bpmn-model-0.25.1.jar:0.25.1]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:51) ~[zeebe-bpmn-model-0.25.1.jar:0.25.1]
	at io.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-0.25.1.jar:0.25.1]
	at io.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:60) ~[zeebe-bpmn-model-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:41) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:104) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:81) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:71) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:51) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:323) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.25.1.jar:0.25.1]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:298) ~[zeebe-workflow-engine-0.25.1.jar:0.25.1]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.1.jar:0.25.1]
```

No impact as far as we know. Broker continues to run without any failure.

**Comment by npepinpe** [comment]
Note, this would require the upgrade process if we were to back port it as it may change the records being written.

**Comment by saig0** [comment]
This issue was reported in [support](https://jira.camunda.com/browse/SUPPORT-11233) for version `1.0.0`.

It can be reproduced with the following BPMN process:
[zeebe_npe.bpmn](https://github.com/camunda-cloud/zeebe/files/6791190/zeebe_npe.bpmn.txt)
