### ISSUE TITLE
ConnectException: Failed to send request to command-api-1, no remote address found.

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5538]
**Describe the bug**
Observed as error in production logs

**Log/Stacktrace**
https://console.cloud.google.com/errors/CLfq8Mup-Ku8Gg?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
ava.net.ConnectException: Failed to send request to command-api-1, no remote address found.
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:108) ~[zeebe-transport-0.24.2.jar:0.24.2]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2(AtomixClientTransportAdapter.java:83) ~[zeebe-transport-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:151) ~[zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
</p>
</details>


**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by pihme** [comment]
most likely wrong log level

**Comment by npepinpe** [comment]
This should be logged as a warning, and maybe we should improve the message so it's clearer what this means.

**Comment by npepinpe** [comment]
Let's not do anything in the transport for now as we plan on replacing it anyway.

**Comment by ana-vinogradova-camunda** [comment]
Observed again here:
https://console.cloud.google.com/errors/detail/CO3W_73W0_XOZw;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911

```
 java.net.ConnectException: Failed to send request to command-api-1, no remote address found.
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:143) ~[zeebe-transport-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2(AtomixClientTransportAdapter.java:88) ~[zeebe-transport-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:88) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.5.6.jar:8.5.6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.5.6.jar:8.5.6] 
```
