### ISSUE TITLE
 NoSuchElementException: Expected an appender, but none found, most likely we are not the leader io.zeebe.logstreams.storage.atomix.AtomixLogStorage.append (AtomixLogStorage.java:57)

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5541]
**Describe the bug**
Observed as error in production logs

**Expected behavior**
This should be logged at most as warning

**Log/Stacktrace**
https://console.cloud.google.com/errors/CKeL1YX1oJjEHg?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.NoSuchElementException: Expected an appender, but none found, most likely we are not the leader
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorage.append(AtomixLogStorage.java:57) ~[zeebe-logstreams-0.24.1.jar:0.24.1]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.appendBlock(LogStorageAppender.java:114) ~[zeebe-logstreams-0.24.1.jar:0.24.1]
	at io.zeebe.logstreams.impl.log.LogStorageAppender.onWriteBufferAvailable(LogStorageAppender.java:164) ~[zeebe-logstreams-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.1.jar:0.24.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.1.jar:0.24.1]
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by npepinpe** [comment]
Hm, this is a possible case and probably shouldn't be logged as an error. It's a transient state, basically. It seems to have been fixed anyway since, though I couldn't pin point it to a specific PR.
