### ISSUE TITLE
TimeoutException: null (on startup)

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5542]
**Describe the bug**
Observed as error in production log.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CLCjqt7DwtfRBw?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```

Error Reporting
Error Details
zeebe
All versions
Open

TimeoutException: null
io.zeebe.broker.Broker.lambda$atomixCreateStep$13 (Broker.java:210)

    Resolution Status

    Open 

        Link to issue

    Occurrences
        1 
        1 (total) 

    Seen in
            zeebe:0.24.3

    First seen
        Jun 30, 2020 
        Sep 8, 2020 (total) 

    Last seen
        16 hours ago 
        16 hours ago (total) 

Errors
Oct 3Oct 5Oct 7Oct 8, 2:08 PM0111
Stack trace sample

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at io.zeebe.broker.Broker.lambda$atomixCreateStep$13(Broker.java:210) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:56) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:56) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:37) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:79) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.internalStart(Broker.java:130) ~[zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.broker.Broker.start(Broker.java:110) [zeebe-broker-0.24.2.jar:0.24.2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:65) [zeebe-distribution-0.24.2.jar:0.24.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:52) [zeebe-distribution-0.24.2.jar:0.24.2]
```

</p>
</details>

**Environment:**
Camunda Cloud / Prod / 0.24.3

**Comment by pihme** [comment]
Occurred only once

**Comment by npepinpe** [comment]
For now, let's focus on improving the error message here, but let's keep it as an error.

**Comment by npepinpe** [comment]
@pihme - added it to the milestone mostly because we want to challenge the use of the step time out, so we might close this by removing them or changing the logic around them.

**Comment by pihme** [comment]
timeout logic has been removed in 1.2.0
