### ISSUE TITLE
Failed to convert JSON to MessagePack in Gateway

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#5565]
**Describe the bug**

If currently an error/exception happens during converting JSON to MsgPack in the gateway then this is logged as error in the Gateway.

We should try to differentiate here:

 * If it was valid JSON and can't be converted to MsgPack then this is an error which we should log. We should then also print the input so we are able to reproduce this error.
 * If  the JSON was invalid then we should not log that as error since this is an client error and will also be returned to the client

Related error reports:

https://console.cloud.google.com/errors/CJmgtuCH2Nv5bA?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
https://console.cloud.google.com/errors/CKz8h5fFk6eYwwE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Failed to convert JSON to MessagePack
	at io.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:80) ~[zeebe-protocol-impl-0.24.3.jar:0.24.3]
	at io.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:71) ~[zeebe-protocol-impl-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:158) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.RequestMapper.toCompleteJobRequest(RequestMapper.java:85) ~[zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.EndpointManager.mapRequest(EndpointManager.java:378) [zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:303) [zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.EndpointManager.completeJob(EndpointManager.java:140) [zeebe-gateway-0.24.3.jar:0.24.3]
	at io.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1496) [zeebe-gateway-protocol-impl-0.24.3.jar:0.24.3]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [grpc-stub-1.30.2.jar:1.30.2]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.30.2.jar:1.30.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('t' (code 116)): was expecting comma to separate Object entries
 at [Source: (ByteArrayInputStream); line: 1, column: 35]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707) ~[jackson-core-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632) ~[jackson-core-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:741) ~[jackson-core-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2006) ~[jackson-core-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:1985) ~[jackson-core-2.11.1.jar:2.11.1]
	at io.zeebe.protocol.impl.encoding.MsgPackConverter.convert(MsgPackConverter.java:136) ~[zeebe-protocol-impl-0.24.3.jar:0.24.3]
	at io.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:76) ~[zeebe-protocol-impl-0.24.3.jar:0.24.3]
	... 17 more
```

</p>
</details>

**Environment:**
 - OS: cloud
 - Zeebe Version: 0.24.3
 - Configuration: -

**Comment by Zelldon** [comment]
Currently when the grpc message comes in the variables are not validated whether it is valid json or not, https://github.com/zeebe-io/zeebe/blob/develop/gateway/src/main/java/io/zeebe/gateway/RequestMapper.java

**Comment by Zelldon** [comment]
Appeared in new version 0.24.4 https://console.cloud.google.com/errors/CPXK9rWWqJLrOg?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**Comment by feliqueres** [comment]
Hi, @Zelldon! Your Google Cloud links are not open, I'm not allowed to open these. Can you share the JSON content who causes the exception?

**Comment by saig0** [comment]
@feliqueres we don't have the JSON that causes the problem. But I think it can be any invalid JSON (e.g. `no-json`). The [gRPC API](https://docs.zeebe.io/reference/grpc.html#createworkflowinstance-rpc) takes the JSON as a plain string.

**Comment by npepinpe** [comment]
This was fixed via https://github.com/camunda-cloud/zeebe/pull/7302
