### ISSUE TITLE
Deserialization failure caused by problems removing/installing 

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#5701]
**Describe the bug**
Seems similar to #5495 but it's not clear if the root cause is the same because those logs are no longer available. What I observed was:
* Exporter in Broker 1 fails to flush entire bulk
* Broker 1 steps down
* Append block fails since it's not leader anymore
* Appender and logstream are marked as unhealthy and start closing
* Things (logstream, exporter, snapshot director) start being closed
* Before everything is closed, Broker 1 goes from follower to candidate and then to leader (this seems to be the cause of the problem)
* Things start failing to close
* The leader partition fails to be removed and the follower partition fails to be installed
* More things that look like a concurrent follower and leader partition
* Eventually, broker 1 tries to append (and fails) and the exporter fails with the KryoException you can see below

Seems like Broker 1 was transitioning to leader before stepping down completely partition is being installed before it the previous was completely removed which causes weird behavior. 
**To Reproduce**
The logs: https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22ff073a96-1bd3-4dee-a0f7-00c194bb0bfd-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-26T15:46:58.479Z%2F2020-10-26T16:46:58.479Z;pinnedLogId=2020-10-26T16:16:28.479993Z%2Fzbi0nj9ivcoapue2w;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?authuser=1&project=camunda-cloud-240911

**Expected behavior**

**Log/Stacktrace**
Link: https://console.cloud.google.com/errors/CKaXyY_1w7ylvgE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

```
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: newPosition > limit: (6815871 > 0)
Serialization trace:
data (io.atomix.raft.zeebe.ZeebeEntry)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-4.0.2.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:267) ~[atomix-utils-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.readNextEntry(FileChannelJournalSegmentReader.java:215) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext(FileChannelJournalSegmentReader.java:197) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.next(FileChannelJournalSegmentReader.java:117) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.reset(FileChannelJournalSegmentReader.java:159) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.MappableJournalSegmentReader.reset(MappableJournalSegmentReader.java:123) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.SegmentedJournalReader.rewind(SegmentedJournalReader.java:160) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.SegmentedJournalReader.reset(SegmentedJournalReader.java:137) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.journal.DelegatingJournalReader.reset(DelegatingJournalReader.java:76) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.findEntry(AtomixLogStorageReader.java:152) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.read(AtomixLogStorageReader.java:55) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.lambda$readBlockIntoBuffer$1(LogStreamReaderImpl.java:193) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.executeReadMethod(LogStreamReaderImpl.java:197) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readBlockIntoBuffer(LogStreamReaderImpl.java:192) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seekFrom(LogStreamReaderImpl.java:129) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:71) ~[zeebe-logstreams-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:188) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:133) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:111) ~[zeebe-workflow-engine-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.2.jar:0.24.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.2.jar:0.24.2]
Caused by: java.lang.IllegalArgumentException: newPosition > limit: (6815871 > 0)
	at java.nio.Buffer.createPositionException(Unknown Source) ~[?:?]
	at java.nio.Buffer.position(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.position(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.position(Unknown Source) ~[?:?]
	at com.esotericsoftware.kryo.io.ByteBufferInput.readVarInt(ByteBufferInput.java:395) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:846) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729) ~[kryo-4.0.2.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-4.0.2.jar:?]
	... 27 more
```

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.23.6
 - Configuration: [e.g. exporters etc.]

**Comment by MiguelPires** [comment]
This happened in 0.24.4 as well https://console.cloud.google.com/errors/CNy2m9355r_G7gE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
Like the previous occurrence, we can observe services closing before and after a broker transitions from candidate to leader which might indicate a race condition.

**Comment by npepinpe** [comment]
If this occurs at that time, it sounds like:

1) buffers are being reused, or
2) we read a partial entry, the file channel is closed, so don't finish reading the rest and attempt to deserialize a partial entry

Not sure how likely each are though

**Comment by npepinpe** [comment]
I would close this for now - it's possible the underlying cause is still present, but the symptoms will be wildly different. I would wait until it presents itself again (if at all ofc).
