### ISSUE TITLE
RaftContext.createRole throws NPE

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#5705]
**Describe the bug**
`RaftContext.createRole` throws a NullPointerException during a transition.
 https://console.cloud.google.com/errors/CIzxgeKMs-v-Fw?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**To Reproduce**
Logs: https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22215eb183-ec6b-418d-90aa-ab3a07901b0b-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-26T15:58:04.301Z%2F2020-10-26T16:58:04.301Z;pinnedLogId=2020-10-26T16:27:34.301050Z%2F0mn9mhsyxyn4barl7;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?authuser=1&project=camunda-cloud-240911

**Expected behavior**
No NPE occurs during a transition.

**Log/Stacktrace**
```
java.lang.NullPointerException: null
	at io.atomix.raft.impl.RaftContext.createRole(RaftContext.java:554) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:508) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:573) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.cluster.impl.RaftClusterContext.commit(RaftClusterContext.java:688) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.InactiveRole.onConfigure(InactiveRole.java:75) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$0(RaftContext.java:207) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:224) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.2.jar:0.24.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.4
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Seems we're transitioning even before we finish initializing the `RaftContext` - is this even possible? @deepthidevaki @Zelldon ? The error here is that the metrics are not initialized here (that's the last step of the `RaftContext` constructor - which quick reminder isn't running in the Raft thread, as it creates the Raft thread).

**Comment by Zelldon** [comment]
I think the issue with atomix is that it does a lot of stuff inside of ctor's, so with incomplete objects. So for me this kind of bug is no suprise tbh...

**Comment by deepthidevaki** [comment]
> Seems we're transitioning even before we finish initializing the RaftContext - is this even possible?

Yes. I suppose it is possible. `join/bootstrap` is initiated only after initializing RaftContext. But I think it is possible for it to receive messages from other nodes which can then trigger transitions.
