### ISSUE TITLE
StorageException: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#5716]
**Describe the bug**
The exception below happens while a broker is truncating its log because it stepped down to follower. The exception happens before all leader services are closed, so there might be some race condition. This seems similar to this https://github.com/zeebe-io/zeebe/issues/5517#issuecomment-717813230 both happen during the truncation. 

**To Reproduce**
Link: https://console.cloud.google.com/errors/CPGsz_vrtt_hhAE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**Log/Stacktrace**
Logs: https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22ff073a96-1bd3-4dee-a0f7-00c194bb0bfd-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-26T15:46:58.484Z%2F2020-10-26T16:46:58.484Z;pinnedLogId=2020-10-26T16:16:28.484242Z%2Fzbi0nj9ivcoapue3e;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?authuser=1&project=camunda-cloud-240911
```
io.atomix.storage.StorageException: java.nio.channels.ClosedChannelException
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext(FileChannelJournalSegmentReader.java:222) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.reset(FileChannelJournalSegmentReader.java:133) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.reset(FileChannelJournalSegmentReader.java:141) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.MappableJournalSegmentReader.reset(MappableJournalSegmentReader.java:123) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.SegmentedJournalReader.reset(SegmentedJournalReader.java:141) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.SegmentedJournal.resetTail(SegmentedJournal.java:607) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.SegmentedJournalWriter.lambda$truncate$0(SegmentedJournalWriter.java:125) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.8.1.jar:?]
	at io.atomix.storage.statistics.JournalMetrics.observeSegmentTruncation(JournalMetrics.java:62) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.SegmentedJournalWriter.truncate(SegmentedJournalWriter.java:110) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.storage.journal.DelegatingJournalWriter.truncate(DelegatingJournalWriter.java:66) ~[atomix-storage-0.23.6.jar:0.23.6]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:860) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:813) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:667) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:51) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:197) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$20(RaftContext.java:248) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$31(RaftContext.java:278) ~[atomix-cluster-0.23.6.jar:0.23.6]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.6.jar:0.23.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source) ~[?:?]
	at sun.nio.ch.FileChannelImpl.position(Unknown Source) ~[?:?]
	at io.atomix.storage.journal.FileChannelJournalSegmentReader.readNext(FileChannelJournalSegmentReader.java:181) ~[atomix-storage-0.23.6.jar:0.23.6]
	... 24 more
```

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.23.6/0.23.7
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Closing for now as we've dropped this code.
