### ISSUE TITLE
BufferUnderflowException in JournalSegmentDescriptor during [7/14] cluster services

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#5777]
**Describe the bug**
A BufferUnderflowException occurred during raft partition start (7/14 cluster services of broker start).

> "Bootstrap Broker-1 [7/14]: cluster services failed with unexpected exception."

The buffer underflow occurs when the journalsegment descriptor is constructed by reading the meta data from the buffer. It occurs on the very first read from the buffer, so I think the buffer was actually empty.

The buffer was supposed to be filled by reading the segments file channel and flipping the buffer in https://github.com/zeebe-io/zeebe/blob/0.25.0/atomix/storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java#L500#L503. At this time, it is unclear to me why the buffer is empty.

After this happens in step 7/14, the broker starts shutting down and closes the steps in reverse. During that another error is thrown which is already covered by https://github.com/zeebe-io/zeebe/issues/5645.

**Expected behavior**
If the segment file was empty, it should at least contain meta data, so I would not expect a buffer underflow.

**Log/Stacktrace**

[Error](https://console.cloud.google.com/errors/CMrwsKLqhaf5fg?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1)

[Logs](https://console.cloud.google.com/logs/query;query=logName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22excitingdev%22%0Aresource.labels.namespace_name%3D%229be46ebe-d264-4fb3-9ccd-c4569b4dc09a-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2020-11-05T11:51:04.962Z%2F2020-11-05T16:51:04.962Z;pinnedLogId=2020-11-05T15:20:35.006526Z%2F198jmref1drbjp?authuser=1&project=camunda-cloud-240911)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:44) [zeebe-distribution-0.25.0.jar:0.25.0]
Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.zeebe.broker.Broker.internalStart(Broker.java:186) ~[zeebe-broker-0.25.0.jar:0.25.0]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.25.0.jar:0.25.0]
	at io.zeebe.broker.Broker.start(Broker.java:159) ~[zeebe-broker-0.25.0.jar:0.25.0]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:57) ~[zeebe-distribution-0.25.0.jar:0.25.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	... 5 more
Caused by: java.util.concurrent.CompletionException: java.nio.BufferUnderflowException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.25.0.jar:0.25.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source) ~[?:?]
	at java.nio.HeapByteBuffer.getInt(Unknown Source) ~[?:?]
	at io.atomix.storage.journal.JournalSegmentDescriptor.<init>(JournalSegmentDescriptor.java:93) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.storage.journal.SegmentedJournal.loadSegment(SegmentedJournal.java:503) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.storage.journal.SegmentedJournal.loadSegments(SegmentedJournal.java:552) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.storage.journal.SegmentedJournal.open(SegmentedJournal.java:255) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.storage.journal.SegmentedJournal.<init>(SegmentedJournal.java:92) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.storage.journal.SegmentedJournal$Builder.build(SegmentedJournal.java:853) ~[atomix-storage-0.25.0.jar:0.25.0]
	at io.atomix.raft.storage.log.RaftLog$Builder.build(RaftLog.java:284) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:300) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:155) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:301) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:275) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:181) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:151) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:109) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:130) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:204) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:206) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-0.25.0.jar:0.25.0]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-0.25.0.jar:0.25.0]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.25.0.jar:0.25.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Environment: excitingdev
 - Zeebe Version: 0.25.0

**Comment by korthout** [comment]
I've given this `Severity: High` because the error blocked the startup of a broker.

**Comment by npepinpe** [comment]
I'm leaving it in the backlog at the moment, as rewriting the journal means this may go away (or change enough that the original issue doesn't make sense).

**Comment by npepinpe** [comment]
We had one user affected but in a test environment, and they got rid of the data so we couldn't investigate. But apart from this I haven't heard of any users affected, so until more people chime in, let's postpone this and focus on our other topics.

**Comment by npepinpe** [comment]
Closing for now as we refactored also how the descriptor is handled.
