### ISSUE TITLE
NullPointerException in LogStreamReaderImpl

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#5805]
**Describe the bug**

[log](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-10T08%3A54%3A54.120000000Z&dateRangeStart=2020-11-10T07%3A54%3A54.120Z&dateRangeEnd=2020-11-10T09%3A54%3A54.120Z&project=camunda-cloud-240911&minLogLevel=0&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2226cfc159-a9bb-4102-88b8-ffcece414532-zeebe%22%0Atimestamp%3D%222020-11-10T08%3A54%3A24.120998000Z%22%0AinsertId%3D%22hhv632g2bq8x4n%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-10T08%3A54%3A26.432882000Z
)

This happened while the partition was transitioned to follower while it is in reprocessing phase.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
D 2020-11-10T08:54:24.092413Z Dispatcher closed 
I 2020-11-10T08:54:24.093083Z On closing logstream logstream-raft-partition-partition-4 close 3 readers 
I 2020-11-10T08:54:24.102193Z Close log storage with name logstream-raft-partition-partition-4 
E 2020-11-10T08:54:24.120998Z Unexpected error on recovery happens. 
  undefined
 "java.lang.NullPointerException: null
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.lambda$readBlockIntoBuffer$1(LogStreamReaderImpl.java:193) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.executeReadMethod(LogStreamReaderImpl.java:197) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readBlockIntoBuffer(LogStreamReaderImpl.java:192) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextAddress(LogStreamReaderImpl.java:225) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextEvent(LogStreamReaderImpl.java:243) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextAddress(LogStreamReaderImpl.java:228) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextEvent(LogStreamReaderImpl.java:243) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:176) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:20) ~[zeebe-logstreams-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.ReProcessingStateMachine.readNextEvent(ReProcessingStateMachine.java:211) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.ReProcessingStateMachine.reprocessNextEvent(ReProcessingStateMachine.java:223) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.4.jar:0.24.4]
E 2020-11-10T08:54:24.122074Z Actor Broker-2-StreamProcessor-4 failed in phase STARTED. 
E 2020-11-10T08:54:24.134294Z Broker-2-StreamProcessor-4 failed, marking it as unhealthy 

```

</p>
</details>

**Environment:**
 - Zeebe Version: [e.g. 0.24.4]

**Comment by deepthidevaki** [comment]
Probably fixed by #5480 because it fixes the closing order.

**Comment by npepinpe** [comment]
@MiguelPires can we tell if this was fixed by #5480?

**Comment by MiguelPires** [comment]
I don't know why but I can't open the link to the logs, so I can't really tell what's happening here. The refactor made the closing of steps sequential but I can't see what the issue here is.

**Comment by npepinpe** [comment]
Have we ever seen this again? While it's unclear if we would have fixed it, considering we just rewrote most of this, I would close this for now.
