### ISSUE TITLE
NullPointerException in ElasticsearchExporter.close

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#5824]
**Describe the bug**

No big impact. It happened when broker was shutdown before bootstrap was completed.
[log](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-11T19%3A21%3A42.875000000Z&dateRangeStart=2020-11-11T18%3A21%3A42.875Z&dateRangeEnd=2020-11-11T20%3A21%3A42.875Z&project=camunda-cloud-240911&minLogLevel=0&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%2241f7a35f-03f9-47bc-be26-3d63fc4850ad-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22production%22%0Atimestamp%3D%222020-11-11T18%3A49%3A17.078436000Z%22%0AinsertId%3D%22c6mcn9ek94719g2z3%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-11T18%3A51%3A45.975180000Z)

```
java.lang.NullPointerException: null
	at io.zeebe.exporter.ElasticsearchExporter.close(ElasticsearchExporter.java:65) ~[zeebe-elasticsearch-exporter-0.25.1.jar:0.25.1]
	at io.zeebe.broker.exporter.stream.ExporterContainer.close(ExporterContainer.java:155) ~[zeebe-broker-0.25.1.jar:0.25.1]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onActorCloseRequested(ExporterDirector.java:154) ~[zeebe-broker-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorTask.requestClose(ActorTask.java:279) ~[zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.25.1.jar:0.25.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.25.1.jar:0.25.1]
```

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
D 2020-11-11T18:43:13.329967Z Bootstrap Broker-0 [6/14]: embedded gateway started in 508 ms 
I 2020-11-11T18:43:13.330817Z Bootstrap Broker-0 [7/14]: cluster services 
W 2020-11-11T18:43:32.219136Z Listener io.atomix.raft.roles.FollowerRole$$Lambda$1006/0x00000001007c8c40@7eebbe96 not registered 
D 2020-11-11T18:43:38.863490Z Bootstrap Broker-0 [7/14]: cluster services started in 25525 ms 
I 2020-11-11T18:43:38.864507Z Bootstrap Broker-0 [8/14]: topology manager 
D 2020-11-11T18:43:38.875095Z Bootstrap Broker-0 [8/14]: topology manager started in 9 ms 
I 2020-11-11T18:43:38.875975Z Bootstrap Broker-0 [9/14]: monitoring services 
D 2020-11-11T18:43:38.897600Z Bootstrap Broker-0 [9/14]: monitoring services started in 21 ms 
I 2020-11-11T18:43:38.898700Z Bootstrap Broker-0 [10/14]: disk space monitor 
D 2020-11-11T18:43:38.914676Z Bootstrap Broker-0 [10/14]: disk space monitor started in 15 ms 
I 2020-11-11T18:43:38.915607Z Bootstrap Broker-0 [11/14]: leader management request handler 
D 2020-11-11T18:43:38.945051Z Bootstrap Broker-0 [11/14]: leader management request handler started in 28 ms 
I 2020-11-11T18:43:38.948291Z Bootstrap Broker-0 [12/14]: zeebe partitions 
I 2020-11-11T18:43:38.973600Z Bootstrap Broker-0 partitions [1/1]: partition 1 
D 2020-11-11T18:43:39.018764Z Received metadata change from Broker 0, partitions {}, terms {} and health {}. 
D 2020-11-11T18:43:39.107445Z Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, workflowInstance=true, workflowInstanceCreation=false, workflowInstanceSubscription=false, ignoreVariablesAbove=8191}, bulk=BulkConfiguration{delay=5, size=1000, memoryLimit=10485760}} 
D 2020-11-11T18:43:39.545025Z Partition role transitioning from null to LEADER 
D 2020-11-11T18:43:39.551167Z Partition 1 closed all previous open resources, before transitioning. 
D 2020-11-11T18:43:45.295321Z The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY} 
D 2020-11-11T18:43:54.424019Z Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1036299-623-1605119527761-1086627815940-1086627815940, metadata=FileBasedSnapshotMetadata{index=1036299, term=623, timestamp=2020-11-11 06:32:07,761, processedPosition=1086627815940, exporterPosition=1086627815940}} 
D 2020-11-11T18:46:14.069764Z Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'. 
D 2020-11-11T18:46:14.075136Z Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1036299-623-1605119527761-1086627815940-1086627815940, metadata=FileBasedSnapshotMetadata{index=1036299, term=623, timestamp=2020-11-11 06:32:07,761, processedPosition=1086627815940, exporterPosition=1086627815940}}' 
D 2020-11-11T18:46:25.936381Z Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled 
D 2020-11-11T18:46:26.007831Z Recovering state of partition 1 from snapshot 
I 2020-11-11T18:46:26.623167Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6f8e713c)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1d563a1a, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@2f208557, configuration: Configuration(false)] 
I 2020-11-11T18:46:39.408794Z Recovered state of partition 1 from snapshot at position 1086627815940 
I 2020-11-11T18:46:39.430134Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@7e085509)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@2f11466b, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@14762383, configuration: Configuration(false)] 
I 2020-11-11T18:46:39.449469Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1feb4ffa)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@26bcada, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@2c8de22, configuration: Configuration(false)] 
D 2020-11-11T18:46:39.659565Z Detected unhealthy components. The current health status of components: {Broker-0-StreamProcessor-1=UNHEALTHY, logstream-raft-partition-partition-1=HEALTHY} 
I 2020-11-11T18:48:39.582750Z Bootstrap Broker-0 partitions [1/1]: partition 1 failed with unexpected exception. 
I 2020-11-11T18:48:39.604248Z Closing Broker-0 partitions succeeded. Closed 0 steps in 0 ms. 
I 2020-11-11T18:48:39.605100Z Bootstrap Broker-0 [12/14]: zeebe partitions failed with unexpected exception. 
I 2020-11-11T18:48:39.606527Z Closing Broker-0 [1/11]: leader management request handler 
D 2020-11-11T18:49:14.687651Z Recovering exporter from snapshot 
D 2020-11-11T18:49:14.695066Z Closing Broker-0 [1/11]: leader management request handler closed in 35087 ms 
D 2020-11-11T18:49:14.695129Z Partition 1 transition complete, installed 11 resources! 
I 2020-11-11T18:49:14.695938Z Closing Broker-0 [2/11]: disk space monitor 
D 2020-11-11T18:49:14.749018Z All partitions are installed. Broker is ready! 
D 2020-11-11T18:49:14.764348Z Closing Broker-0 [2/11]: disk space monitor closed in 68 ms 
I 2020-11-11T18:49:14.765206Z Closing Broker-0 [3/11]: monitoring services 
D 2020-11-11T18:49:14.774415Z Closing Broker-0 [3/11]: monitoring services closed in 9 ms 
I 2020-11-11T18:49:14.775502Z Closing Broker-0 [4/11]: topology manager 
D 2020-11-11T18:49:14.776354Z Closing Broker-0 [4/11]: topology manager closed in 0 ms 
I 2020-11-11T18:49:14.776845Z Closing Broker-0 [5/11]: cluster services 
D 2020-11-11T18:49:14.777440Z Closing Broker-0 [5/11]: cluster services closed in 0 ms 
I 2020-11-11T18:49:14.779099Z Closing Broker-0 [6/11]: embedded gateway 
D 2020-11-11T18:49:14.803843Z Closing gateway broker client ... 
D 2020-11-11T18:49:14.810248Z topology manager closed 
D 2020-11-11T18:49:14.811289Z Gateway broker client closed. 
D 2020-11-11T18:49:14.811846Z Closing Broker-0 [6/11]: embedded gateway closed in 32 ms 
I 2020-11-11T18:49:14.812441Z Closing Broker-0 [7/11]: subscription api 
D 2020-11-11T18:49:14.815308Z Closing Broker-0 [7/11]: subscription api closed in 3 ms 
I 2020-11-11T18:49:14.816076Z Closing Broker-0 [8/11]: command api handler 
D 2020-11-11T18:49:14.825508Z Closing Broker-0 [8/11]: command api handler closed in 9 ms 
I 2020-11-11T18:49:14.827795Z Closing Broker-0 [9/11]: command api transport 
D 2020-11-11T18:49:16.935123Z Closing Broker-0 [9/11]: command api transport closed in 2105 ms 
I 2020-11-11T18:49:16.936018Z Closing Broker-0 [10/11]: membership and replication protocol 
E 2020-11-11T18:49:17.043935Z Uncaught exception in 'Broker-0-Exporter-1' in phase 'STARTED'. Continuing with next job. 
E 2020-11-11T18:49:17.078436Z Error on close 
D 2020-11-11T18:49:17.080229Z Closed exporter director 'Broker-0-Exporter-1'. 
```

</p>
</details>

**Environment:**
 - Zeebe Version: 0.25.1

**Comment by npepinpe** [comment]
Prioritized as low as the impact is mostly noise, since the broker was already unavailable from the user point of view.
