### ISSUE TITLE
NoSuchFileException : Caused by trying to delete pending directory of already persisted snapshot

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6445]
**Describe the bug**

Found the following exception on a broker when closing.  The snapshot `19-1-1614256970300-19-20` has been previously committed and removed from the pending directory. However the snapshot store is still trying to delete it's pending directory.
```
 [Broker-0-SnapshotStore-1] [Broker-0-zb-actors-0] WARN  io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/tmp/2e899412-4bff-4046-9ec4-6fed3e254b6a/data/raft-partition/partitions/1/pending/19-1-1614256970300-19-20, snapshotStore=io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore@156d2d0b, metadata=FileBasedSnapshotMetadata{index=19, term=1, timestamp=2021-02-25 01:42:50,300, processedPosition=19, exporterPosition=20}}
java.nio.file.NoSuchFileException: /tmp/2e899412-4bff-4046-9ec4-6fed3e254b6a/data/raft-partition/partitions/1/pending/19-1-1614256970300-19-20
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1764) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2717) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2797) ~[?:?]
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:47) ~[classes/:?]
	at io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:145) ~[classes/:?]
	at io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:96) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [classes/:?]

```

There is no impact, just produces unnecessary error logs. 

**Expected behavior**
Should not try to delete pending directories of already committed snapshot.

**Comment by jwulf** [comment]
I see this on 1.0.0-alpha3 while the broker is running:

```
 2021-03-17 03:11:09.578 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] WARN 
zeebe_broker |       io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/5761-1-6095-9223372036854775807, snapshotStore=io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore@51433d06, metadata=FileBasedSnapshotMetadata{index=5761, term=1, processedPosition=6095, exporterPosition=9223372036854775807}}
zeebe_broker | java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/5761-1-6095-9223372036854775807
zeebe_broker |  at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
zeebe_broker |  at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
zeebe_broker |  at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
zeebe_broker |  at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?]
zeebe_broker |  at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
zeebe_broker |  at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
zeebe_broker |  at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
zeebe_broker |  at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:47) ~[zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:145) ~[zeebe-snapshots-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:96) ~[zeebe-snapshots-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker |  at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha3.jar:1.0.0-alpha3]
zeebe_broker | 2021-03-17 03:11:09.579 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] INFO 
zeebe_broker |       io.zeebe.logstreams.snapshot - Current commit position 6258 >= 6258, snapshot 5923-1-6257-9223372036854775807 is valid and has been persisted.
```

**Comment by npepinpe** [comment]
I think this might be fixed by us now using `FileUtil.deleteFolderIfNotExists` on rollback - I would close this, and reopen if this is still occurring.
