### ISSUE TITLE
IOException: No space left on device

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#6505]
**Describe the bug**
Observed in logs: https://console.cloud.google.com/errors/CP-qk6vd55GyiQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source) ~[?:?]
	at java.nio.channels.Channels.writeFully(Unknown Source) ~[?:?]
	at java.nio.channels.Channels$1.write(Unknown Source) ~[?:?]
	at java.nio.file.Files.write(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk(FileBasedReceivedSnapshot.java:180) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.applyInternal(FileBasedReceivedSnapshot.java:120) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.lambda$apply$0(FileBasedReceivedSnapshot.java:68) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) ~[zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1]
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
Error 2021-03-05 18:12:07.828 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:08.961 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:10.101 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.336 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.364 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.369 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.372 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.403 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.406 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:12.652 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:14.071 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:15.524 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.961 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.967 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.972 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.975 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.977 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.980 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:17.428 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:18.863 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:20.116 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.239 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.246 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.250 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.252 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.254 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:23.237 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:23.949 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.471 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.904 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.910 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.913 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.915 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.936 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job." 
Error 2021-03-05 18:12:25.939 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.953 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.955 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:27.248 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:28.136 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:29.911 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:29.917 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.442 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.647 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.650 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.652 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.656 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.658 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.659 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:32.106 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:33.215 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:34.031 CET "RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role"
Error 2021-03-05 18:12:37.545 CET "Raft-1 failed, marking it as unhealthy"
Info 2021-03-05 18:12:37.626 CET "Disk space available again. Current available 10878291968 bytes" 
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.26.1
 - Configuration: Camunda Cloud

**Comment by pihme** [comment]
Not really a bug but something that can happen in the normal course of operation.

Possible improvements: 
- do not log it as an error, but as a warning instead
- allocate disk space of the size of the snapshot to be received before receiving the snapshot

**Comment by npepinpe** [comment]
Properly configured disk watermarks should prevent this - did we misconfigure them? Or is it possible for a snapshot to suddenly spike in size?

**Comment by npepinpe** [comment]
For this issue please lower the log level to a warning.
