### ISSUE TITLE
KryoException: Buffer underflow. Serialization trace: byteArray (org.agrona.concurrent.UnsafeBuffer) data (io.zeebe.journal.file.record.PersistedJournalRecord)

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#6506]
**Describe the bug**
Observed in production logs: https://console.cloud.google.com/errors/CJeIyMW12cqwuAE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```


com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
byteArray (org.agrona.concurrent.UnsafeBuffer)
data (io.zeebe.journal.file.record.PersistedJournalRecord)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:221) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:378) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:358) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.read(DefaultArraySerializers.java:55) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ByteArraySerializer.read(DefaultArraySerializers.java:36) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:787) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:134) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:187) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:732) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:125) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:187) ~[kryo-5.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-5.0.3.jar:?]
	at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:189) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.record.KryoSerializer.read(KryoSerializer.java:37) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.record.JournalRecordReaderUtil.read(JournalRecordReaderUtil.java:60) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.MappedJournalSegmentReader.readNext(MappedJournalSegmentReader.java:124) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.MappedJournalSegmentReader.next(MappedJournalSegmentReader.java:78) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournalReader.next(SegmentedJournalReader.java:84) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournalReader.next(SegmentedJournalReader.java:25) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLogReader.next(RaftLogReader.java:56) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.readNextBlock(AtomixLogStorageReader.java:93) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.hasNext(AtomixLogStorageReader.java:72) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextBlock(LogStreamReaderImpl.java:185) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.hasNext(LogStreamReaderImpl.java:50) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.exporter.stream.ExporterDirector.shouldExport(ExporterDirector.java:287) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.exporter.stream.ExporterDirector.readNextEvent(ExporterDirector.java:275) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]

```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
Debug 2021-03-03 13:54:30.688 CET "We will skip taking this snapshot, because we haven't processed something yet."
Debug 2021-03-03 13:59:30.689 CET "We will skip taking this snapshot, because we haven't processed something yet."
Debug 2021-03-03 14:04:30.721 CET "We will skip taking this snapshot, because we haven't processed something yet."
Debug 2021-03-03 14:09:30.753 CET "We will skip taking this snapshot, because we haven't processed something yet."
Debug 2021-03-03 14:14:30.767 CET "We will skip taking this snapshot, because we haven't processed something yet."
Info 2021-03-03 14:17:51.213 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@4334b5d3)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@7b256f4f, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@6c955af9, configuration: Configuration(false)]"
Error 2021-03-03 14:17:57.669 CET "Uncaught exception in 'Broker-0-Exporter-1' in phase 'STARTED'. Continuing with next job."
Debug 2021-03-03 14:18:12.353 CET "Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"task-job","worker":"default","timeout":60000,"maxJobsToActivate":32,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type task-job after timeout of PT10S"
Debug 2021-03-03 14:19:30.786 CET "Based on lowest exporter position '401' and last processed position '716', determined '401' as snapshot position."
Debug 2021-03-03 14:19:30.794 CET "Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/pending/305-4-1614777570790-716-401."
Debug 2021-03-03 14:19:30.824 CET "Created pending snapshot for Broker-0-StreamProcessor-1"
Info 2021-03-03 14:19:30.825 CET "Finished taking snapshot, need to wait until last written event position 716 is committed, current commit position is 716. After that snapshot can be marked as valid."
Debug 2021-03-03 14:19:30.828 CET "Purging snapshots older than FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/305-4-1614777570790-716-401, metadata=FileBasedSnapshotMetadata{index=305, term=4, timestamp=2021-03-03 01:19:30,790, processedPosition=716, exporterPosition=401}}"
Debug 2021-03-03 14:19:30.838 CET "Search for orphaned snapshots below oldest valid snapshot with index FileBasedSnapshotMetadata{index=305, term=4, timestamp=2021-03-03 01:19:30,790, processedPosition=716, exporterPosition=401} in /usr/local/zeebe/data/raft-partition/partitions/1/pending"
Debug 2021-03-03 14:19:30.841 CET "New snapshot 305-4-1614777570790-716-401 was persisted. Start replicating."
Debug 2021-03-03 14:19:30.855 CET "Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/305-4-1614777570790-716-401, metadata=FileBasedSnapshotMetadata{index=305, term=4, timestamp=2021-03-03 01:19:30,790, processedPosition=716, exporterPosition=401}}"
Info 2021-03-03 14:19:30.855 CET "Current commit position 716 >= 716, snapshot 305-4-1614777570790-716-401 is valid and has been persisted."
Debug 2021-03-03 14:19:30.855 CET "Compacting Atomix log up to index 305"
Debug 2021-03-03 14:19:30.857 CET "No segments can be deleted with index < 305 (first log index: 1)"
Debug 2021-03-03 14:19:30.868 CET "Consume snapshot snapshotChunk 000008.sst of snapshot 305-4-1614777570790-716-401"
Debug 2021-03-03 14:19:30.874 CET "Consume snapshot snapshotChunk 000008.sst of snapshot 305-4-1614777570790-716-401"
Debug 2021-03-03 14:19:30.875 CET "Waiting for more snapshot chunks of snapshot 305-4-1614777570790-716-401, currently have 1/5"
Debug 2021-03-03 14:19:30.876 CET "Waiting for more snapshot chunks of snapshot 305-4-1614777570790-716-401, currently have 1/5"
Debug 2021-03-03 14:19:30.876 CET "Consume snapshot snapshotChunk CHECKSUM of snapshot 305-4-1614777570790-716-401"
Debug 2021-03-03 14:19:30.877 CET "Waiting for more snapshot chunks of snapshot 305-4-1614777570790-716-401, currently have 2/5"
Debug 2021-03-03 14:19:30.877 CET "Consume snapshot snapshotChunk CURRENT of snapshot 305-4-1614777570790-716-401"
Debug 2021-03-03 14:19:30.877 CET "Consume snapshot snapshotChunk CHECKSUM of snapshot 305-4-1614777570790-716-401"
Debug 2021-03-03 14:19:30.878 CET "Waiting for more snapshot chunks of snapshot 305-4-1614777570790-716-401, currently have 3/5" 
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: zeebe:1.0.0-SNAPSHOT-ea5efe6965bef03339ed80b4c9c9c7046b3e468d
 - Configuration: Camunda Cloud

**Comment by pihme** [comment]
Occurred in a cluster on `ultrachaos`.

**Comment by npepinpe** [comment]
This happened last time but was fixed by https://github.com/zeebe-io/zeebe/pull/6471 - if this snapshot was built after this commit then there is a new case for it. However I wouldn't spend too much time on this as we have many changes upcoming to this part of the code specifically. So let's timebox the same as we normally do for medic stuff, and if we don't find anything then let's revisit it once the new serialization format is in.

**Comment by npepinpe** [comment]
Closing for now as we've removed Kryo from our storage.
