### ISSUE TITLE
IllegalStateException: Expected to find a workflow deployed with key '2251799813685249' but not found.

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6518]
**Describe the bug**
Link: https://console.cloud.google.com/errors/CKKKoZr33Lr0ywE?service=zeebe&time=P7D&refresh=auto&project=camunda-cloud-240911&authuser=1&organizationId=669107107215

**Log/Stacktrace**
```
java.lang.IllegalStateException: Expected to find a workflow deployed with key '2251799813685249' but not found.
	at io.zeebe.engine.state.deployment.WorkflowState.getFlowElement(WorkflowState.java:99) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.getElement(BpmnStreamProcessor.java:144) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:51) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:322) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:297) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1]
```

**Environment:**
 - Zeebe Version: 0.26.1

**Comment by korthout** [comment]
During reprocessing, records are simply "processed again". In the case of workflow instance records this means it will use the `BpmnStreamProcessor` to process the record again. After determining the specific processor to process the record, the executable flow element that the record refers to is retrieved from the workflow state. This failed, as it `expected to find a workflow deployed with key x, but not found` (it needs that deployed workflow to take the executable flow element from). 

So why was the deployed workflow not available in state? That's no longer possible to find out. No other record info is printed expect for the `workflowKey`. The cluster is also already removed, so I assume the data is also removed. 

It also doesn't really matter. Soon reprocessing is removed. We'll no longer need to look up the executable flow element of all workflow instance related records to reprocess. This code will not be executed again for replay, unless for a very specific reason. In which case it might be way easier to find the actual problem.

However, I would argue that it would make sense to print record metadata when we throw exceptions during processing/replay. If we have access to the data, it would make investigation a lot easier, since we can then use zdb to lookup the specific record.

**Comment by npepinpe** [comment]
This affects 0.26.x, and we will support this version at least until July, so if we have an idea on how to fix it for existing users than we should do so.

However, reading your comment, it seems quite unlikely we'll figure it out now as we lost the data. What we can do is improve our monitoring so we can do that next time, as you proposed. So I would be happy if improving the monitoring/debugging is the "fix" here for now.
