### ISSUE TITLE
Can't append entries due to Low system clock granularity causes 

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6520]
**Describe the bug**
We received a user report where a broker fails to append entries. This happens because the rate limiter library we're using when appending entries throws an `IllegalArgumentException` stating that the RTT must be larger than zero. 
The limiter library uses `System.nanoTime()` to calculate the round-trip time two calculate the start and end time of the request and takes the difference between them to be the RTT. This means that, in this environment, two consecutive calls to `System.nanoTime()` return the same value. This is weird but not impossible, as the documentation of `System.nanoTime()` states "no guarantees are made except that the resolution is at least as good as that of currentTimeMillis()" and the documentation of `currentTimeMillis()` states "many operating systems measure time in units of tens of milliseconds". So this even though this is unusual, it's possible and we should handle it. 
I made a simple app to verify that the user's system clock doesn't have enough granularity to measure very small time differences and the results reported by the user confirm this hypothesis.

**To Reproduce**
This is dependent on the granularity of the system clock so it's hard to reproduce in other systems but I worked with the user to confirm it.

**Expected behavior**
Entries can be appended without issues.

**Log/Stacktrace**

This is the only the relevant stack trace, I'm omitting the rest of the logs.

<details><summary>Stack trace</summary>
<p>

```
java.lang.IllegalArgumentException: rtt must be >0 but got 0 
	at com.netflix.concurrency.limits.internal.Preconditions.checkArgument(Preconditions.java:21) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limit.VegasLimit._update(VegasLimit.java:201) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limit.AbstractLimit.onSample(AbstractLimit.java:34) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limiter.AbstractLimiter$1.onSuccess(AbstractLimiter.java:102) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at io.zeebe.logstreams.impl.backpressure.AppendEntryLimiter.onCommit(AppendEntryLimiter.java:54) ~[zeebe-logstreams-0.26.1.jar:0.26.1] 
	at io.zeebe.logstreams.impl.log.LogStorageAppender.lambda$releaseBackPressure$2(LogStorageAppender.java:216) ~[zeebe-logstreams-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1] 
```
</p>
</details>

**Environment:**
 - OS: RHEL 7.7
 - Zeebe Version: 0.26.1
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
IIRC they are using the official camunda/zeebe Docker image right? So it's something to do with the virtualization? :dizzy_face:

**Comment by npepinpe** [comment]
Could you share the code used to find the granularity so we can reproduce this?

**Comment by Zelldon** [comment]
interesting read regarding that https://www.javaadvent.com/2019/12/measuring-time-from-java-to-kernel-and-back.html

**Comment by Zelldon** [comment]
Btw it might that GC can affect this, since our application thread can be paused in between, which might cause negative values (if we are continue on different cpu or the pause was long enough).

**Comment by MiguelPires** [comment]
> IIRC they are using the official camunda/zeebe Docker image right? So it's something to do with the virtualization?

The Docker image doesn't necessarily have any effect on this issue. If the system clock isn't granular enough, the outcome would always be the same regardless of image/virtualization differences

> Could you share the code used to find the granularity so we can reproduce this?

Since this is specific to the user's system, we can't really reproduce it. Locally the smallest I got was 15ns, which doesn't really say anything

The simplest way to solve this is to pass a clock to the limiter that wraps the `System.nanoTime()` call with something that keeps the last measurement and, if the next one is the same, it increments it by one. It would fix the issue regardless of what the underlying cause is

**Comment by npepinpe** [comment]
Regarding the solution, how will it handle that the clock is shared by all listeners created by the limiter? Since on a call we don't know if it's being called to measure the start time or the end time, or even if by the same listener.

**Comment by MiguelPires** [comment]
We can set the clock used by the rate limiter, so it's not specific to listeners. We can just increment the time if it's the same as the last, the context of the call (who's calling it and when) won't really have any effect

**Comment by MiguelPires** [comment]
@npepinpe the user hasn't reported this error again so I think the fix worked well enough. Can we merge it?
