### ISSUE TITLE
Broker fails to recover due to corrupted snapshot

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6547]
**Describe the bug**
Brokers aren't able to recover from snapshot because it's corrupted. After sifting through the logs, the situation look like this:

- Broker 0 takes a snapshot and replicates it
- Both broker 1 and broker 2 use it to recover a few minutes later
- A few minutes after that, both fail to recover with the exception pasted below
- Eventually broker 0 recovers from the same snapshot
- The new snapshot is replicated to the other brokers and the problematic one is deleted

The cluster goes away shortly after so there are no metrics available. The fact that the snapshot was initially ok but was then corrupted in two separate brokers at the same time makes it unlikely that this isn't a bug.

**Log/Stacktrace**

<details><summary>Logs</summary>
 <p>

https://console.cloud.google.com/errors/CJOEiez-nbjZlAE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911&authuser=1&folder&organizationId=669107107215

</p>
</details>

<details><summary>Stack trace</summary>
 <p>

```
java.lang.IllegalStateException: Unexpected error occurred trying to open the database
	at io.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:80) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:37) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.StateControllerImpl.openDb(StateControllerImpl.java:143) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:126) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionStep.open(ZeebeDbPartitionStep.java:28) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.PartitionStep.open(PartitionStep.java:30) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:98) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$installPartition$2(PartitionTransitionImpl.java:107) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: org.rocksdb.RocksDBException: Corruption: IO error: No such file or directoryWhile open a file for random read: /usr/local/zeebe/data/raft-partition/partitions/3/runtime/000008.ldb: No such file or directory
	at org.rocksdb.OptimisticTransactionDB.open(Native Method) ~[rocksdbjni-6.15.2.jar:?]
	at org.rocksdb.OptimisticTransactionDB.open(OptimisticTransactionDB.java:40) ~[rocksdbjni-6.15.2.jar:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.openTransactionalDb(ZeebeTransactionDb.java:81) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:75) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 14 more
```
</p>
</details>

**Environment:**
 - Zeebe Version: zeebe:1.0.0-SNAPSHOT-719e0c728d4a4b3958dd2b21af74607fba261441

**Comment by korthout** [comment]
@npepinpe I was unable to find anything new in the logs. The cluster no longer exists, so data analysis is not possible.

**Comment by npepinpe** [comment]
Closing for now, if we see this again we should immediately investigate.
