### ISSUE TITLE
Broker fails after deserializing InitialEntry

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6549]
**Describe the bug**
Brokers fails on startup after deserializing the initial entry with a ClassCastException `class io.atomix.raft.storage.log.entry.InitialEntry cannot be cast to class io.atomix.raft.storage.log.entry.RaftLogEntry `. 
This code is anyway going to be overwritten soon so maybe we can wait until those changes are merged and close this if the error is gone.

**Log/Stacktrace**
[logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-03-12T15%3A19%3A58.203000000Z&dateRangeStart=2021-03-12T14%3A49%3A58.203Z&dateRangeEnd=2021-03-12T15%3A49%3A58.203Z&advancedFilter=error_group(%22CN3ngumKpLDu1gE%22)%0AlogName%3A%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22b9e26b49-b492-47fa-a7f6-c39883261787-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&project=camunda-cloud-240911&authuser=1&folder&organizationId=669107107215)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.atomix.raft.storage.log.entry.InitialEntry cannot be cast to class io.atomix.raft.storage.log.entry.RaftLogEntry (io.atomix.raft.storage.log.entry.InitialEntry and io.atomix.raft.storage.log.entry.RaftLogEntry are in unnamed module of loader 'app')
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassCastException: class io.atomix.raft.storage.log.entry.InitialEntry cannot be cast to class io.atomix.raft.storage.log.entry.RaftLogEntry (io.atomix.raft.storage.log.entry.InitialEntry and io.atomix.raft.storage.log.entry.RaftLogEntry are in unnamed module of loader 'app')
	at io.atomix.raft.storage.log.RaftLogReader.next(RaftLogReader.java:57) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.cluster.impl.RaftMemberContext.openReaderAtEndOfLog(RaftMemberContext.java:100) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.cluster.impl.RaftMemberContext.resetState(RaftMemberContext.java:88) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.cluster.impl.RaftClusterContext.<init>(RaftClusterContext.java:84) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:172) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:119) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 9 more
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
As we're replacing Kryo with SBE, let's not put too much time in there right now. If however this is causing a lot of noise for the medic when looking at testbench, then let's investigate it.

**Comment by npepinpe** [comment]
Closing as we've now replaced Kryo :+1:
