### ISSUE TITLE
StateWriter doesn't use ReprocessingStreamWriter during reprocessing

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6557]
**Describe the bug**
During reprocessing it appears that the StateWriter uses a normal `TypedStreamWriterImpl` as its streamWriter instead of the ReprocessingStreamWriter that is normally used during reprocessing.

Note, that records are not actually written to the log, since the batchwriter is not flushed on reprocessing. However, this can still lead to problems. One of which we've seen in [reported error](https://console.cloud.google.com/errors/CIyOy5qX44qppgE?service=zeebe-broker&time=P7D&filter=text:IndexOutOfBoundsException&project=zeebe-io&authuser=1). In this error, the batchwriter is unable to copy a new `Variable` event into its batch for the reprocessing of a `CreateWorkflowInstance` command.

**To Reproduce**
Process a `CreateWorkflowInstance` command and start reprocessing.

**Expected behavior**
No new events are written to the log (or to the batchwriter) during reprocessing

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IndexOutOfBoundsException: index=1073741823 length=8 maxCapacity=1073741824
	at org.agrona.ExpandableDirectByteBuffer.ensureCapacity(ExpandableDirectByteBuffer.java:1151) ~[agrona-1.9.0.jar:1.9.0]
	at org.agrona.ExpandableDirectByteBuffer.putLong(ExpandableDirectByteBuffer.java:184) ~[agrona-1.9.0.jar:1.9.0]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:165) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.event(LogStreamBatchWriterImpl.java:78) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendRecord(TypedStreamWriterImpl.java:72) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendRecord(TypedStreamWriterImpl.java:60) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendFollowUpEvent(TypedStreamWriterImpl.java:171) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.EventApplyingStateWriter.appendFollowUpEvent(EventApplyingStateWriter.java:48) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.EventApplyingStateWriter.appendFollowUpEvent(EventApplyingStateWriter.java:39) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.variable.VariableBehavior.setLocalVariable(VariableBehavior.java:182) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.variable.VariableBehavior.mergeLocalDocument(VariableBehavior.java:76) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.workflowinstance.CreateWorkflowInstanceProcessor.setVariablesFromDocument(CreateWorkflowInstanceProcessor.java:117) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.workflowinstance.CreateWorkflowInstanceProcessor.onCommand(CreateWorkflowInstanceProcessor.java:81) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:70) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:34) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.reprocessRecord(ReProcessingStateMachine.java:402) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$7(ReProcessingStateMachine.java:368) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$4(ReProcessingStateMachine.java:340) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - Zeebe Version: medic-cw-09-cf1627167-benchmark
 - Source: cf1627167
 - Configuration: Weekly benchmark

**Comment by korthout** [comment]
This problem also exists when writing events directly using the Writers object, e.g. CreateProcessInstanceProcessor

I think it doesn’t happen often, but it is more likely to happen for larger payloads and specific cases that cause many writes during reprocessing (e.g. many Create ProcessInstance commands). 

The specific exception is thrown when inside the LogStreamBatchWriterImpl the eventbufferoffset is overflowing the eventbuffer size. Normally this offset is reset when the batchwriter is written away using tryWrite, which is called by StreamWriter.flush, But this is never called for Reprocessing. So on reprocessing that offset never resets and when too many records are written to the batchwriter during reprocessing, it throws this exception.

I think the issue should be fixed by only using the ReprocessingStreamWriter during reprocessing and only the TypedStreamWriterImpl during processing. Both the Writers object and the StateWriter just assume that the logstreamwriter on the ProcessingContext is up-to-date. It appears the processors themselves are created statically, and not when switching between these states, while their constructors depend on a specific StreamWriter to use during their lifetime

**Comment by npepinpe** [comment]
That's my understanding of why the typed stream writer was previously injected as an argument and not at construction time, tbh.
