### ISSUE TITLE
Closing a bootstrapping partition after timeout does not stop bootstrapping

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6561]
**Describe the bug**
When a boostrapping partition times out after the given `zeebe.broker.stepTimeout` (default 5m), the broker will close the partition again. In the meantime, the bootstrapping does not seem to be interrupted, and eventually throws an IllegalStateException when a reader tries to access a segment that has already been closed.

**To Reproduce**
Unsure, but have a look at the reported error

**Expected behavior**
The partition should stop bootstrapping when it times out, so that it does not interfere with the closing sequence. 

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.scheduleActor(Broker.java:330) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.lambda$partitionsStep$21(Broker.java:412) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:422) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.lambda$initStart$10(Broker.java:233) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.Broker.start(Broker.java:160) [zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) [zeebe-distribution-1.0.0-alpha2.jar:1.0.0-alpha2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar:2.4.3]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [zeebe-distribution-1.0.0-alpha2.jar:1.0.0-alpha2]

```

```
java.lang.IllegalStateException: Segment not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.1-jre.jar:?]
	at io.zeebe.journal.file.JournalSegment.checkOpen(JournalSegment.java:163) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.journal.file.JournalSegment.createReader(JournalSegment.java:143) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.journal.file.SegmentedJournalReader.replaceCurrentSegment(SegmentedJournalReader.java:214) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.journal.file.SegmentedJournalReader.hasNextEntry(SegmentedJournalReader.java:198) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.journal.file.SegmentedJournalReader.hasNext(SegmentedJournalReader.java:68) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.journal.file.SegmentedJournalReader.seekToAsqn(SegmentedJournalReader.java:137) ~[zeebe-journal-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.atomix.raft.storage.log.RaftLogReader.seekToAsqn(RaftLogReader.java:97) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.seek(AtomixLogStorageReader.java:59) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:100) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seekToEnd(LogStreamReaderImpl.java:124) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getLastPosition(LogStreamImpl.java:314) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.openAppender(LogStreamImpl.java:255) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.createWriter(LogStreamImpl.java:206) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.lambda$newLogStreamBatchWriter$3(LogStreamImpl.java:130) ~[zeebe-logstreams-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
```

</p>
</details>

**Reported error**
[link](https://console.cloud.google.com/errors/CN6w6Nu_jbO92QE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1&organizationId=669107107215)

**Environment:**
 - OS: camunda cloud ultrachaos
 - Zeebe Version: zeebe:1.0.0-alpha2

**Comment by korthout** [comment]
A similar but different error was reported. [IllegalStateException: Not leader of partition 7](https://console.cloud.google.com/errors/CNTS5I-ficiL8AE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1&organizationId=669107107215). 

In this case it's not a bootstrapping partition, but a role change. In the logs we can clearly see the `AtomixLogStorage` closing successfully in the closing sequence, followed by `Expected to open step 'AtomixLogStorage' but failed with` (with cause: `java.lang.IllegalStateException: Not leader of partition 7`).

I think something is going wrong with not interrupting the current executed tasks before starting the closing sequence.

```
Debug 2021-03-16 11:08:38.192 CET "Closing Zeebe-Partition-7: AtomixLogStorage"
Debug 2021-03-16 11:08:38.192 CET "Closing Zeebe-Partition-7: AtomixLogStorage closed successfully"
Debug 2021-03-16 11:08:38.192 CET "Partition 7 closed all previous open resources, before transitioning."
Debug 2021-03-16 11:08:38.193 CET "Partition 7 transition complete, installed 5 resources!"
Debug 2021-03-16 11:08:38.193 CET "Closing Zeebe-Partition-7: ConsumeReplicatedSnapshots"
Debug 2021-03-16 11:08:38.193 CET "Closing Zeebe-Partition-7: ConsumeReplicatedSnapshots closed successfully"
Debug 2021-03-16 11:08:38.193 CET "Closing Zeebe-Partition-7: LogDeletionService"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: LogDeletionService closed successfully"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: StateController"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: StateController closed successfully"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: SnapshotReplication"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: SnapshotReplication closed successfully"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: RaftLogReader"
Debug 2021-03-16 11:08:38.194 CET "Closing Zeebe-Partition-7: RaftLogReader closed successfully"
Debug 2021-03-16 11:08:38.194 CET "Partition 7 closed all previous open resources, before transitioning."
Error 2021-03-16 11:08:38.196 CET "Expected to open step 'AtomixLogStorage' but failed with"
Error 2021-03-16 11:08:38.196 CET "Failed to install leader partition 7"
```

Stacktrace
```
java.lang.IllegalStateException: Not leader of partition 7
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.lambda$open$1(AtomixLogStoragePartitionStep.java:43) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.open(AtomixLogStoragePartitionStep.java:26) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:98) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$transition$1(PartitionTransitionImpl.java:81) ~[zeebe-broker-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
```

**Comment by pihme** [comment]
This should no longer (1.2.0 and beyond) happen as the step timeout for startup and shutdown has been removed. Steps will take as long as necessary and it is up to the runtime environment to kill the process if it takes too long to get ready,
