### ISSUE TITLE
Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job

### ISSUE THREAD

**Issue by yzhengwei** [camunda-cloud/zeebe#6581]
**Description**
My zeebe cluster have 3 nodes and version is 0.26.0, I found some error logs in the zeebe log like this `Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job`, and sometimes the ptometheus mericcs zeebe_health is 0.  What's wrong with this?
### The zeebe config:
```
zeebe:
  broker:
    stepTimeout: 5m
    gateway:
      enable: true
      network:
        port: 26500
        minKeepAliveInterval: 30s
      cluster:
        requestTimeout: 15s
      threads:
        managementThreads: 2000
      monitoring:
        enabled: true
      longPolling:
        enabled: true
    network:
      portOffset: 0
      maxMessageSize: 4MB
      commandApi:
        host: 10.21.88.13
        port: 26501
      internalApi:
        host: 10.21.88.13
        port: 26502
      monitoringApi:
        port: 10106
    data:
      directories: [ /data/zeebe ]
      logSegmentSize: 512MB
      snapshotPeriod: 15m
    cluster:
      nodeId: 2
      partitionsCount: 3
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [ 10.21.88.13:26502, 10.21.93.103:26502, 10.21.88.119:26502 ]
      clusterName: zeebe-cluster2
      membership:
        broadcastUpdates: false
        broadcastDisputes: true
        notifySuspect: false
        gossipInterval: 250ms
        gossipFanout: 2
        probeInterval: 1s
        probeTimeout: 2s
        suspectProbes: 3
        failureTimeout: 10s
        syncInterval: 10s
    threads:
      cpuThreadCount: 2
      ioThreadCount: 2
    backpressure:
      enabled : true
      algorithm: "vegas"
      vegas:
        initialLimit: 20
        alpha: 3
        beta: 6
    exporters:
      elasticsearch:
        className: io.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://prod.zeebe2.sbos.sg2.es:9200
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
          index:
            prefix: ms
            createTemplate: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: false
            messageSubscription: false
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
            ignoreVariablesAbove: 32677
```
### This zeebe error log:
```
2021-03-18 19:37:33.813 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:37:33.819 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:37:46.520 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-1] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:38:14.755 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:38:14.755 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:38:14.812 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-1] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
2021-03-18 19:38:37.353 [GatewayLongPollingJobHandler] [Broker-2-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-30.0-jre.jar:?]
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202) ~[grpc-core-1.34.0.jar:1.34.0]
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22) ~[grpc-api-1.34.0.jar:1.34.0]
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39) ~[grpc-api-1.34.0.jar:1.34.0]
	at me.dinowernli.grpc.prometheus.MonitoringServerCall.close(MonitoringServerCall.java:46) ~[java-grpc-prometheus-0.3.0.jar:?]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374) ~[grpc-stub-1.34.0.jar:1.34.0]
	at io.zeebe.gateway.grpc.ErrorMappingStreamObserver.onError(ErrorMappingStreamObserver.java:105) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onCompleted$5(LongPollingActivateJobsHandler.java:152) ~[zeebe-gateway-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
```
### The monitor:
![image](https://user-images.githubusercontent.com/59439277/111621510-0a1f7a00-8823-11eb-8a41-685bacb1ca85.png)

**Comment by npepinpe** [comment]
HI @yzhengwei, this is a known issue - this shouldn't be much a problem however, as it simply indicates the client has gone away.

The monitoring issue should be fixed (as we shouldn't report this as an error), but it should have no adverse effect on your cluster for now.
