### ISSUE TITLE
StorageException$InvalidIndex: Expected to read a record with next index 46967694, but found 46967698

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6773]
**Describe the bug**
The partition failed to start. It failed on recovering when reading the log stream (i.e. `ReProcessingStateMachine.scanLog`).

`Actor Broker-0-StreamProcessor-2 failed in phase STARTED.`

**To Reproduce**

Not clear.

![image](https://user-images.githubusercontent.com/4305769/114365841-25a84700-9b7b-11eb-835b-0cabe7777331.png)

There are multiple role transitions in a short time:

* FOLLOWER to CANDIDATE in term 127
* CANDIDATE to LEADER in term 127
* LEADER to FOLLOWER in term 128
* FOLLOWER to CANDIDATE in term 129
* CANDIDATE to FOLLOWER in term 130

![image](https://user-images.githubusercontent.com/4305769/114366237-89327480-9b7b-11eb-9189-af333c5c58d9.png)

**Expected behavior**
The partition is started successfully.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.journal.StorageException$InvalidIndex: Expected to read a record with next index 46967694, but found 46967698
	at io.zeebe.journal.file.record.JournalRecordReaderUtil.read(JournalRecordReaderUtil.java:78) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.readNext(MappedJournalSegmentReader.java:124) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.hasNext(MappedJournalSegmentReader.java:56) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.hasNextEntry(SegmentedJournalReader.java:194) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.hasNext(SegmentedJournalReader.java:68) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.seekToAsqn(SegmentedJournalReader.java:137) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.storage.log.RaftLogReader.seekToAsqn(RaftLogReader.java:95) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.seek(AtomixLogStorageReader.java:58) ~[zeebe-logstreams-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:100) ~[zeebe-logstreams-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:268) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:185) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:129) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
```

Error Reporting: https://console.cloud.google.com/errors/CPaNto_LxZi_NA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
Logs: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%2299936d0e-e21b-493c-8b96-6d79ac11c40d-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2021-04-10T23:44:01.960Z%2F2021-04-11T00:44:01.960Z;pinnedLogId=2021-04-11T00:13:31.960542Z%2F1a289nrg2cxkzw5;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2021-04-11T00:13:31.960542Z?project=camunda-cloud-240911

</p>
</details>

**Environment:**
 - OS: Camunda Cloud (ultratest)
 - Zeebe Version: 1.0.0-alpha4
 - Configuration:

**Comment by deepthidevaki** [comment]
I had a look at the logs and the log segments. There are no missing records in the log segments. Seems to be some inconsistency observed temporarily by the reader. I couldn't figure out what really happened. But the good thing is that there is no real inconsistency in the segments.

**Comment by deepthidevaki** [comment]
When this exception happened, the role was transitioning from Leader to Follower.  Hence, this might be a result of #4198. Since the node was transitioned to follower immediately after it became the leader, there is high probability that there are uncommitted events that need to be truncated. 

```
D 2021-04-11T00:11:27.294001Z Partition role transitioning from FOLLOWER to CANDIDATE in term 127 
D 2021-04-11T00:11:29.038714Z Partition role transitioning from CANDIDATE to LEADER in term 127 
D 2021-04-11T00:11:29.039486Z Partition 2 closed all previous open resources, before transitioning. 
...
D 2021-04-11T00:12:59.373806Z Partition 2 transition complete, installed 12 resources! 
I 2021-04-11T00:12:59.374321Z ZeebePartition-2 recovered, marking it as healthy 
D 2021-04-11T00:13:00.573451Z Recovered exporter 'Broker-0-Exporter-2' from snapshot at lastExportedPosition 63846122 
D 2021-04-11T00:13:00.573761Z Configure exporter with id 'elasticsearch' 
...
D 2021-04-11T00:13:00.574884Z Open exporter with id 'elasticsearch' 
I 2021-04-11T00:13:00.576778Z Exporter opened 
D 2021-04-11T00:13:00.577123Z Open exporter with id 'MetricsExporter' 
D 2021-04-11T00:13:05.150812Z Partition role transitioning from LEADER to FOLLOWER in term 128 
D 2021-04-11T00:13:05.151301Z Closing Zeebe-Partition-2: ExporterDirector 
D 2021-04-11T00:13:05.151495Z Discard job io.zeebe.util.sched.future.FutureContinuationRunnable QUEUED from fastLane of Actor Broker-0-Exporter-2. 
I 2021-04-11T00:13:05.190188Z Exporter closed 
D 2021-04-11T00:13:05.190779Z Closed exporter director 'Broker-0-Exporter-2'. 
D 2021-04-11T00:13:05.190977Z Closing Zeebe-Partition-2: ExporterDirector closed successfully 
D 2021-04-11T00:13:05.191334Z Closing Zeebe-Partition-2: RocksDB metric timer 
D 2021-04-11T00:13:05.191547Z Closing Zeebe-Partition-2: RocksDB metric timer closed successfully 
D 2021-04-11T00:13:05.191625Z Closing Zeebe-Partition-2: AsyncSnapshotDirector 
D 2021-04-11T00:13:05.191798Z Closing Zeebe-Partition-2: AsyncSnapshotDirector closed successfully 
D 2021-04-11T00:13:05.191880Z Closing Zeebe-Partition-2: StreamProcessor 
D 2021-04-11T00:13:23.991995Z Partition role transitioning from FOLLOWER to CANDIDATE in term 129 
D 2021-04-11T00:13:28.598171Z Partition role transitioning from CANDIDATE to FOLLOWER in term 130 
E 2021-04-11T00:13:31.960542Z Actor Broker-0-StreamProcessor-2 failed in phase STARTED. 
```

Since there is no records missing in the acutal log, I would conclude that the exception happened due to corrupted in-memory state of the reader due to #4198.
