### ISSUE TITLE
Cluster services failed with unexpected exception: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6776]
**Describe the bug**
The cluster service of a partition failed to start repeatedly.

```
Bootstrap Broker-2 [6/14]: cluster services failed with unexpected exception."
```

```
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: index=12 length=838926337 capacity=256
```

**To Reproduce**

Not clear.

![image](https://user-images.githubusercontent.com/4305769/114390496-a4f74400-9b96-11eb-8a02-95eca39a73d5.png)

It seems that it failed directly after a restart.

Before the restart, two partitions were marked as unhealthy. 

**Expected behavior**
The cluster service starts successfully.    

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: index=12 length=838926337 capacity=256
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: index=12 length=838926337 capacity=256
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1730) ~[agrona-1.9.0.jar:1.9.0]
	at org.agrona.concurrent.UnsafeBuffer.getBytes(UnsafeBuffer.java:852) ~[agrona-1.9.0.jar:1.9.0]
	at io.atomix.raft.storage.serializer.MetaDecoder.votedFor(MetaDecoder.java:243) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.storage.serializer.MetaStoreSerializer.readVotedFor(MetaStoreSerializer.java:143) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.storage.system.MetaStore.loadVote(MetaStore.java:139) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:152) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:119) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 9 more

```

</p>
</details>

Error Reporting: https://console.cloud.google.com/errors/CKTlu4nMmPixfQ?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
Log: https://console.cloud.google.com/logs/query;query=%0A%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%223e79b8e1-6eee-4d93-aad9-3c559163e5bf-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;timeRange=2021-04-08T04:30:00.966Z%2F2021-04-08T08:30:00.966Z;pinnedLogId=2021-04-08T07:33:37.827749Z%2Fvn62yuf9jfni5;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2021-04-08T07:33:37.827749Z?project=camunda-cloud-240911

**Environment:**
 - OS: Camunda Cloud (ultratest)
 - Zeebe Version: Snapshot
 - Configuration:

**Comment by npepinpe** [comment]
@deepthidevaki looks like an issue with the new SBE metastore

**Comment by deepthidevaki** [comment]
This cluster is using SNAPSHOT image. The PR https://github.com/camunda-cloud/zeebe/pull/6734 that break compatibility has been merged while this cluster is running. The exception occurs because it is trying to read the old data with new version. This is expected as we are not guaranteeing compatibility in snapshot images.
