### ISSUE TITLE
Do not log a warning that a checksum file is not a snapshot

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6793]
**Description**

In 0.26, we now have a sibling checksum file for the snapshot. While picking up the latest snapshot, it still assumes all files in the snapshots folder are snapshots, and logs a warning that the checksum file is not a real snapshot (which makes sense).

This is purely noise, but can be confusing as it will always log this warning on start up.

**Comment by MiguelPires** [comment]
How do we know this is just purely noise? I'm seeing logs in production where brokers start up up to cluster services, log the exception below and then get stuck. After some time (5 minutes or so) the broker restarts, repeating the process. Eventually, one iteration manages to start up the cluster services after 10 minutes. I think it may be caused by not being able to read the snapshot. It's also not an isolated occurrence, I've seen the same pattern in several namespaces.
I also remember some issues in the medic benchmarks from last week that happened near this point in the start up process and that also had similar logs, so they may be related.

```
java.lang.NumberFormatException: For input string: "4879908076.checksum"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Long.parseLong(Unknown Source) ~[?:?]
	at java.lang.Long.parseLong(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotMetadata.ofFileName(FileBasedSnapshotMetadata.java:57) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotMetadata.ofPath(FileBasedSnapshotMetadata.java:44) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.collectSnapshot(FileBasedSnapshotStore.java:115) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.loadLatestSnapshot(FileBasedSnapshotStore.java:87) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.<init>(FileBasedSnapshotStore.java:78) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.createAndOpenNewSnapshotStore(FileBasedSnapshotStoreFactory.java:60) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.lambda$createReceivableSnapshotStore$0(FileBasedSnapshotStoreFactory.java:55) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.createReceivableSnapshotStore(FileBasedSnapshotStoreFactory.java:53) ~[zeebe-snapshots-0.26.3.jar:0.26.3]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:168) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:151) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:109) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:130) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:204) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:206) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-0.26.3.jar:0.26.3]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.26.3.jar:0.26.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by npepinpe** [comment]
Looking at the code, it looks like we go through all files in the directory and assume they are snapshots. If we cannot parse one, we simply go to the next one. It should have no bearing on being able to read the right snapshot.

I'm happy to look over the code with you again and you can show me how this particular log statement indicates a problem which causes a restart. I'm not saying that there is nothing wrong with snapshots, but that statement (i.e. cannot parse the name of the checksum file as a snapshot) is most likely not a problem.

**Comment by npepinpe** [comment]
Even better, if you want we can release and roll out 0.26.4 which fixes this, and see if the problem persists :slightly_smiling_face:
