### ISSUE TITLE
Nullpointer exception when terminating subprocess

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6829]
**Describe the bug**

[Full log](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-04-20T18%3A43%3A25.000000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22falko-swift-snapshot%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22falko-swift-snapshot-zeebe-3%22%0Atimestamp%3D%222021-04-20T18%3A53%3A25.496829000Z%22%0AinsertId%3D%22tougu5fegqgop%22&scrollTimestamp=2021-04-20T18%3A53%3A44.518995000Z&dateRangeStart=2021-04-20T17%3A43%3A25.000Z&dateRangeEnd=2021-04-20T19%3A43%3A25.000Z)

```
 "Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=TERMINATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=1.0.0}, value={"bpmnProcessId":"BENCH-PERF","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":9007199275446620,"elementId":"Activity_0as9av3","flowScopeKey":9007199275448551,"bpmnElementType":"SUB_PROCESS","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'null'."   
```

**Log/Stacktrace**

```
exception: "java.lang.NullPointerException: null
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.getFlowScopeInstance(BpmnStateBehavior.java:139) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.canBeTerminated(BpmnStateBehavior.java:83) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onChildTerminated$6(SubProcessProcessor.java:143) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onChildTerminated(SubProcessProcessor.java:128) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onTerminate(SubProcessProcessor.java:94) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onTerminate(SubProcessProcessor.java:23) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:207) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:126) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:296) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:286) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:254) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:219) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:210) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
"   

```

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by deepthidevaki** [comment]
@Zelldon Please ask @falko for the process model if you would like to reproduce it.

**Comment by Zelldon** [comment]
https://github.com/camunda-cloud/zeebe/pull/6830
