### ISSUE TITLE
Follower fails to restart due to partial snapshot

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6894]
**Describe the bug**
During a QA run a chaos experiment `Zeebe follower graceful restart experiment` failed.

2 errors were reported for the failure during restart: [IllegalStateException: Server not running](https://console.cloud.google.com/errors/CL6ggtPQsti1fA?time=P30D&project=camunda-cloud-240911&authuser=1&folder&organizationId=669107107215) and [Expected to find a snapshot at index >= log's first index 550255500, but found snapshot 0](https://console.cloud.google.com/errors/CNK46tb9p4fRQw?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1&folder&organizationId=669107107215). 

Just before those errors, a warning was logged: `Cannot load snapshot in /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/219-1-524-525. The checksum stored does not match the checksum calculated.`

Investigating the specific snapshot we find it incomplete:
```sh
ls -al /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/219-1-524-525
total 28
drwxr-xr-x 2 root root 4096 Apr 26 14:56 .
drwxr-xr-x 3 root root 4096 Apr 26 14:56 ..
-rw-r--r-- 1 root root    8 Apr 26 14:56 CHECKSUM
-rw-r--r-- 1 root root   16 Apr 26 14:56 CURRENT
-rw-r--r-- 1 root root  178 Apr 26 14:56 MANIFEST-000004
-rw-r--r-- 1 root root 6304 Apr 26 14:56 OPTIONS-000007
```

The `CHECKSUM` file is not empty, but as far as I can tell it does not contain text but it could be a U32 `1316233983` (LE) or `4280448078` (BE):
```sh
od -x /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/219-1-524-525/CHECKSUM
0000000 0000 0000 ff22 744e
0000010
```

**To Reproduce**

Potentially reproducible by running the QA run again.

**Expected behavior**

Snapshots should always be complete and consistent.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%220fc0df98-1ba7-4bfb-9080-1be1fe5f8a4b-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%220fc0df98-1ba7-4bfb-9080-1be1fe5f8a4b-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2021-04-26T14:33:00.546Z%2F2021-04-26T15:33:00.546Z;pinnedLogId=2021-04-26T15:02:30.546257Z%2F18eavv3g3eufpdw;cursorTimestamp=2021-04-26T15:02:28.501984Z?folder=true&authuser=1&organizationId=669107107215&project=camunda-cloud-240911

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 220, but found snapshot 0
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 220, but found snapshot 0
	at io.atomix.raft.impl.RaftContext.verifySnapshotLogConsistent(RaftContext.java:190) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:166) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:119) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 9 more
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud Ultrachaos
 - Zeebe Version: a26b85b6f
 - Configuration:

**Comment by korthout** [comment]
Failed due to conflicting chaos experiment - `corrupt follower` by running `corruptSnapshot.sh`  in between on the same broker for the same partition.

```
2021-04-26 16:56:08:321 CEST Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/219-1-524-525
```

```
2021-04-26 16:56:07.620 CEST kubectl -n 0fc0df98-1ba7-4bfb-9080-1be1fe5f8a4b-zeebe cp /home/chaos/zeebe-chaos/chaos-experiments/scripts/corruptSnapshot.sh zeebe-0:/usr/local/zeebe/corrupting.sh
2021-04-26 16:56:08.444 CEST Run 'corruptSnapshot zeebe-2' (so it finished running corruptSnapshot.sh at this point)
```

```
2021-04-26 16:56:19.918 CEST Failed to open snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/219-1-524-525
```
