### ISSUE TITLE
Back to back role changes cause ZeebePartition to go unhealthy and transition to inactive

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6997]
**Describe the bug**

Installing leader services failed because of following exception:

```
java.lang.IllegalStateException: Not leader of partition 1
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.lambda$open$1(AtomixLogStoragePartitionStep.java:43) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Optional.java:203) ~[?:?]
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.open(AtomixLogStoragePartitionStep.java:26) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:105) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$transition$1(PartitionTransitionImpl.java:85) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

This error happens when raft has changed the role and term before ZeebePartition has completed transition for the previous term. When this happens, we want to prevent the leader from previous term from appending new entries with the new term. That's why this step fails with this exception. However this fails the leader installation and ZeebePartition detects it as a failure and go inactive, which is not expected.

```
E 2021-05-06T13:42:18.479009Z Expected to open step 'AtomixLogStorage' but failed with 
E 2021-05-06T13:42:18.479385Z Failed to install leader partition 1 
I 2021-05-06T13:42:18.479743Z Unexpected failures occurred when installing follower services, transitioning to inactive 
E 2021-05-06T13:42:18.480418Z ZeebePartition-1 failed, marking it as unhealthy 
```

There are two issues here:
1. When "java.lang.IllegalStateException: Not leader of partition 1" exception happens, there will be already next transition in queue. But ZeebePartition takes action as if the leader install failed. ZeebePartition doesn't have to react as if installation failed and steps down. If it steps down, it might trigger another unnecessary leader election.
2. Even though here leader installation failed, ZeebePartition reacts as if the follower installation failed and go inactive. This happened because it is reading the current role of the raft partition instead of checking which transition failed. This role is different because of asynchronous role transition between raft and zeebe.

In this situation, one partition is unhealthy and the raft is inactive. However it is recoverable by restarting the node.

**To Reproduce**
Not sure how to reproduce this. But check the logs for understanding the scenario.

**Expected behavior**

1. When "java.lang.IllegalStateException: Not leader of partition 1" exception happens, it should just close the current leader services instead of failing or stepdown.
2. On install failures the reaction should be based on for which transitions it failed instead of reading the current role of raft partition.

**Log/Stacktrace**
[logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-05-06T13%3A50%3A34.903000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22medic-cw-17-df496d4b4-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.pod_name%3D%22medic-cw-17-df496d4b4-benchmark-zeebe-1%22%0Atimestamp%3D%222021-05-06T13%3A42%3A18.479009000Z%22%0AinsertId%3D%221iya3xff2y1jbd%22&scrollTimestamp=2021-05-06T13%3A42%3A18.484158000Z) 

**Environment:**
 - Zeebe Version: 1.0.0-SNAPSHOT

**Comment by npepinpe** [comment]
Workaround - if you run into this now, restarting the broker would fix it.
