### ISSUE TITLE
IllegalStateException: MessagingService is closed

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7026]
**Describe the bug**
Observed in production logs: https://console.cloud.google.com/errors/COuJ5b3lsJ_wrgE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Happened during broker shutdown

**Expected behavior**
* The broker rejects incoming requests while it is shutting down.

**Stacktrace/Log**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: MessagingService is closed.
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:187) ~[zeebe-atomix-cluster-1.0.0-rc3.jar:1.0.0-rc3]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:174) ~[zeebe-atomix-cluster-1.0.0-rc3.jar:1.0.0-rc3]
	at io.atomix.cluster.messaging.MessagingService.sendAndReceive(MessagingService.java:135) ~[zeebe-atomix-cluster-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:148) ~[zeebe-transport-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$handleResponse$7(AtomixClientTransportAdapter.java:197) ~[zeebe-transport-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-rc3.jar:1.0.0-rc3]
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
I 2021-05-10T13:08:17.223431Z Closing Broker-0 [13/14]: membership and replication protocol 
I 2021-05-10T13:08:17.225003Z RaftServer{raft-partition-partition-2} - Transitioning to INACTIVE 
I 2021-05-10T13:08:17.225111Z RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE 
W 2021-05-10T13:08:17.225798Z Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/11359821-1-43199459-42632738, checksum=3348776506, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@7fc663f1, metadata=FileBasedSnapshotMetadata{index=11359821, term=1, processedPosition=43199459, exporterPosition=42632738}} 
W 2021-05-10T13:08:17.225949Z Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/11292822-1-43176014-42378214, checksum=3385011616, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@2a546ff, metadata=FileBasedSnapshotMetadata{index=11292822, term=1, processedPosition=43176014, exporterPosition=42378214}} 
I 2021-05-10T13:08:17.266473Z Stopped 
I 2021-05-10T13:08:17.267045Z Stopped 
I 2021-05-10T13:08:17.267394Z Stopped 
I 2021-05-10T13:08:17.268792Z Stopped 
I 2021-05-10T13:08:17.269892Z 0 - Member deactivated: Member{id=0, address=zeebe-0.zeebe-broker-service.6228559f-dbed-4ccb-960b-3339de86e2ef-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAwAAAAAAAgAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS42MjI4NTU5Zi1kYmVkLTRjY2ItOTYwYi0zMzM5ZGU4NmUyZWYtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAIBAAAAAAIAAAAADAACAQAAAAEAAAAAAAAAAgAAAAEAAAAAAAAACQAAADEuMC4wLXJjMwUAAgEAAAAAAgAAAAA=, event-service-topics-subscribed=KIUDAKdkZXBsb3ltZW50LXJlc3BvbnNlLTIyNTE3OTk4MTU1MDMzMjItMmpvYnNBdmFpbGFibOWnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjYwLTKnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODIzOTI3OTE1LTI=}} 
I 2021-05-10T13:08:17.270395Z Stopped 
I 2021-05-10T13:08:17.271430Z Left 
I 2021-05-10T13:08:17.272416Z Stopped 
E 2021-05-10T13:08:19.289972Z Expected to handle gRPC request, but an unexpected error occurred 
E 2021-05-10T13:08:19.291357Z Expected to handle gRPC request, but an unexpected error occurred 
I 2021-05-10T13:08:21.300267Z Stopped 
I 2021-05-10T13:08:21.300802Z Stopped 
I 2021-05-10T13:08:21.301563Z Closing Broker-0 [14/14]: actor scheduler 
I 2021-05-10T13:08:21.307299Z Closing Broker-0 succeeded. Closed 14 steps in 7289 ms. 
I 2021-05-10T13:08:21.307450Z Broker shut down. 

```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: Zeebe 1.0.0-rc3
 - Configuration: Camunda Cloud

**Comment by npepinpe** [comment]
Let's schedule it for now, assuming that it's simply a matter of shutting down in the right order - if this proves to be more complex, please tell me and we can review if it makes sense to do now.

**Comment by pihme** [comment]
@npepinpe I think it is a little more complex. I think we can solve this bug when working on bootstrap refactoring. However, I would propose to remove it from ready list for now.

**Comment by npepinpe** [comment]
Let's do that :+1:
