### ISSUE TITLE
ClassCastException while walking model

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7035]
**Describe the bug**
Observed in production logs: https://console.cloud.google.com/errors/CLX10NPi7-uz0QE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Unable to process unknown element with name standardLoopCharacteristics
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.lambda$walk$0(ModelWalker.java:69) ~[zeebe-bpmn-model-1.0.0.jar:1.0.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:63) ~[zeebe-bpmn-model-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:40) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:119) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:296) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:286) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:254) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:219) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:210) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: java.lang.ClassCastException: class org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl cannot be cast to class io.camunda.zeebe.model.bpmn.instance.BpmnModelElementInstance (org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl and io.camunda.zeebe.model.bpmn.instance.BpmnModelElementInstance are in unnamed module of loader 'app')
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.lambda$walk$0(ModelWalker.java:66) ~[zeebe-bpmn-model-1.0.0.jar:1.0.0]
	... 19 more
```

</p>
</details>

**Environment:**
Linux, Camunda Cloud, Zeebe 1.0.0

**Comment by saig0** [comment]
The root cause of the `ClassCastException` is the same as #4817.

Here, the user tried to deploy a BPMN with a [loop marker](https://camunda.com/bpmn/reference/) (i.e. `bpmn:standardLoopCharacteristics`). A loop marker is similar to a multi-instance marker but it has a completion condition. Loop markers are currently not supported.

**Comment by npepinpe** [comment]
I will close as duplicate then, but take it into account to possibly reprioritize the other issue.
