### ISSUE TITLE
zeebe-1.0.0 atomix-cluster-heartbeat-sender error

### ISSUE THREAD

**Issue by 94236970** [camunda-cloud/zeebe#7046]
**Describe the bug**
Install zeebe-1.0.0 use docker,when start I got many error:
2021-05-14 00:56:38.186 [] [atomix-cluster-heartbeat-sender] WARN 
      io.atomix.cluster.messaging.impl.NettyMessagingService - An error occurred in a message handler:
com.esotericsoftware.kryo.KryoException: Unable to find class: x

**To Reproduce**
docker run --name zeebe -p 26500-26502:26500-26502 camunda/zeebe:1.0.0

**Expected behavior**
No Error found

**Log/Stacktrace**
2021-05-14 00:56:36.170 [] [atomix-cluster-heartbeat-sender] WARN 
      io.atomix.cluster.messaging.impl.NettyMessagingService - An error occurred in a message handler:
com.esotericsoftware.kryo.KryoException: Unable to find class: x
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:182) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:151) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[kryo-5.1.1.jar:?]
        at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:169) ~[zeebe-atomix-utils-1.0.0.jar:1.0.0]
        at io.atomix.utils.serializer.Serializer$1.decode(Serializer.java:75) ~[zeebe-atomix-utils-1.0.0.jar:1.0.0]
        at io.atomix.cluster.protocol.SwimMembershipProtocol.lambda$new$2(SwimMembershipProtocol.java:111) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$6(NettyMessagingService.java:225) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: x
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:176) ~[kryo-5.1.1.jar:?]
        ... 13 more
2021-05-14 00:56:38.186 [] [atomix-cluster-heartbeat-sender] WARN 
      io.atomix.cluster.messaging.impl.NettyMessagingService - An error occurred in a message handler:
com.esotericsoftware.kryo.KryoException: Unable to find class: x
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:182) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:151) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[kryo-5.1.1.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[kryo-5.1.1.jar:?]
        at io.atomix.utils.serializer.Namespace.deserialize(Namespace.java:169) ~[zeebe-atomix-utils-1.0.0.jar:1.0.0]
        at io.atomix.utils.serializer.Serializer$1.decode(Serializer.java:75) ~[zeebe-atomix-utils-1.0.0.jar:1.0.0]
        at io.atomix.cluster.protocol.SwimMembershipProtocol.lambda$new$2(SwimMembershipProtocol.java:111) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$6(NettyMessagingService.java:225) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: x
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:176) ~[kryo-5.1.1.jar:?]
        ... 13 more

**Environment:**
 - OS: centos7+docker18.06.3-ce
 - Zeebe Version: 1.0.0
 - Configuration:

**Comment by npepinpe** [comment]
Hi @94236970, I cannot reproduce this. The errors you get seem to be related with the network layer receiving messages which it doesn't know how to interpret. Are there any other nodes running on the same network which might interact with your container?

**Comment by 94236970** [comment]
Hi @npepinpe, only one zeebe-broker running on the network. I use "docker run --name zeebe -p 26500-26502:26500-26502 camunda/zeebe:1.0.0" cmd to run a standalone broker on my computer..
how to explian "Caused by: java.lang.ClassNotFoundException: x" ? is there any class in zeebe named x? it`s very strange
this problem only appear in zeebe:1.0.0 , in zeebe:0.26 or early version every thing goes fine.

**Comment by 94236970** [comment]
execute "docker run --name zeebe -p 26500-26502:26500-26502 camunda/zeebe:1.0.0" command，wait about one minute.you will see the exception. the exception occurs every 2 seconds.

**Comment by 94236970** [comment]
Hi @npepinpe I set ATOMIX_LOG_LEVEL=error  manually, and the warn not print.
docker command like below:
docker run --name zeebe -e **ATOMIX_LOG_LEVEL=error**  -p 26500-26502:26500-26502 camunda/zeebe:1.0.0

do not print the log doesn't mean it didn't happen,can you find the reason of this warn exception and fixed it?

**Comment by npepinpe** [comment]
I'm afraid I can't reproduce it. Running the command you gave and waiting a few minutes, even with the ATOMIX_LOG_LEVEL set to INFO, I see no errors. Are you sure it's not picking up an old volume or something? And no other node is trying to connect to it? In 1.0, Kryo is now only used for the network layer, so there would need to be some interaction via the network (other nodes in the cluster, or a client sending something).

**Comment by 94236970** [comment]
Hi @npepinpe ,as you say I review my environment and I find an old version  zeebe-broker deployed in cluster mode is still alive . I think it send SWIM messages to the single zeebe-broker-1.0.0 node . then i stop old version  zeebe-broker the bug disappear . thank you very much..
