### ISSUE TITLE
NPE in SegmentedJournalReader.seekToAsqn ()

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7050]
**Describe the bug**
Observed in ultratest logs:
https://console.cloud.google.com/errors/CNDP74D9iszabA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

followed immediately by:
https://console.cloud.google.com/errors/CMndrd7jo5yD2AE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.journal.file.SegmentedJournalReader.seekToAsqn(SegmentedJournalReader.java:139) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.storage.log.RaftLogReader.seekToAsqn(RaftLogReader.java:95) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.seek(AtomixLogStorageReader.java:58) ~[zeebe-logstreams-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:100) ~[zeebe-logstreams-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:268) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:185) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:129) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
```

Follow up exception:
```
io.zeebe.journal.StorageException$InvalidIndex: Expected to read a record with next index 47685197, but found 47718818
	at io.zeebe.journal.file.record.JournalRecordReaderUtil.read(JournalRecordReaderUtil.java:78) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.readNext(MappedJournalSegmentReader.java:124) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.reset(MappedJournalSegmentReader.java:83) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.seek(MappedJournalSegmentReader.java:90) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.rewind(SegmentedJournalReader.java:174) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.seek(SegmentedJournalReader.java:96) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournal.resetTail(SegmentedJournal.java:561) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalWriter.lambda$deleteAfter$0(SegmentedJournalWriter.java:95) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.10.0.jar:?]
	at io.zeebe.journal.file.JournalMetrics.observeSegmentTruncation(JournalMetrics.java:78) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalWriter.deleteAfter(SegmentedJournalWriter.java:82) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournal.deleteAfter(SegmentedJournal.java:109) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.storage.log.RaftLog.truncate(RaftLog.java:178) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:583) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:532) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:390) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:194) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$10(RaftContext.java:229) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$17(RaftContext.java:240) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-1.0.0-alpha4.jar:1.0.0-alpha4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
</p>
</details>

<details><summary>Log</summary>
<a href="https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-13T08:09:47.342000000Z&dateRangeStart=2021-05-13T07:09:47.342Z&dateRangeEnd=2021-05-13T09:09:47.342Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=severity!%3DDEBUG%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%2299936d0e-e21b-493c-8b96-6d79ac11c40d-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-13T08:10:30.413563000Z&pinnedLogId=1l6a9bog54m9a5z&pinnedLogTimestamp=2021-05-13T08:09:17.342710Z">Log</a>
 <p>

```
E 2021-05-13T08:08:52.337177Z Catched exception class io.zeebe.engine.processing.bpmn.BpmnProcessingException with message Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. [context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, elementInstanceKey=2251799830767258, flowScopeKey=2251799830689014, processInstanceKey=2251799830689014, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}], will retry... 
E 2021-05-13T08:08:52.337537Z Catched exception class io.zeebe.engine.processing.bpmn.BpmnProcessingException with message Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. [context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, elementInstanceKey=2251799830767258, flowScopeKey=2251799830689014, processInstanceKey=2251799830689014, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}], will retry... 
I 2021-05-13T08:08:56.820630Z Recovered state of partition 2 from snapshot at position 71379937 
I 2021-05-13T08:08:56.821506Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3d8e8725)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1754ee26, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@474c38bd, configuration: Configuration(false)] 
I 2021-05-13T08:08:56.822769Z Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@4cdced30)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@5a2fc21, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@35b7176d, configuration: Configuration(false)] 
E 2021-05-13T08:08:56.825504Z Partition-2 failed, marking it as unhealthy 
I 2021-05-13T08:08:57.390470Z Exporter opened 
I 2021-05-13T08:09:16.982367Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Accepted PollRequest{term=11306, candidate=0, lastLogIndex=48708558, lastLogTerm=11306}: candidate's log is up-to-date 
I 2021-05-13T08:09:17.004140Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Accepted VoteRequest{term=11307, candidate=0, lastLogIndex=48708558, lastLogTerm=11306}: candidate's log is up-to-date 
I 2021-05-13T08:09:17.063391Z RaftServer{raft-partition-partition-2} - Found leader 0 
I 2021-05-13T08:09:17.213758Z RaftServer{raft-partition-partition-2} - Received successful append response higher term (11307 > 11306) from DefaultRaftMember{id=0, type=ACTIVE, updated=2021-04-07T08:25:28.942Z}, implying there is a new leader - transitioning to follower 
I 2021-05-13T08:09:17.220194Z RaftServer{raft-partition-partition-2} - Transitioning to FOLLOWER 
I 2021-05-13T08:09:17.221316Z RaftServer{raft-partition-partition-2} - Found leader 0 
I 2021-05-13T08:09:17.269748Z Exporter closed 
E 2021-05-13T08:09:17.342469Z Actor Broker-2-StreamProcessor-2 failed in phase STARTED. 
E 2021-05-13T08:09:17.342710Z RaftServer{raft-partition-partition-2} - An uncaught exception occurred, transition to inactive role 
I 2021-05-13T08:09:17.344867Z RaftServer{raft-partition-partition-2} - Transitioning to INACTIVE 
E 2021-05-13T08:09:17.346081Z ZeebePartition-2 failed, marking it as unhealthy 
E 2021-05-13T08:09:17.346183Z Raft-2 failed, marking it as unhealthy 
W 2021-05-13T08:09:20.287659Z Failed to activate jobs for type camunda:worker:email from partition 2 
E 2021-05-13T08:09:20.290058Z Uncaught exception in 'GatewayLongPollingJobHandler' in phase 'STARTED'. Continuing with next job. 
W 2021-05-13T08:09:30.300497Z Failed to activate jobs for type camunda:worker:email from partition 2 
W 2021-05-13T08:09:40.304539Z Failed to activate jobs for type camunda:worker:email from partition 2 

```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version/Configuration: Zeebe 1.0.0-alpha4, Camunda Cloud

**Comment by pihme** [comment]
Impact assessment is difficult. 

The cluster runs on ultratest, not in production. 

The log It is littered with exceptions from the engine which indicate that it cannot make progress.

```
E 2021-05-13T08:08:52.337177Z Catched exception class io.zeebe.engine.processing.bpmn.BpmnProcessingException with message Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. [context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, elementInstanceKey=2251799830767258, flowScopeKey=2251799830689014, processInstanceKey=2251799830689014, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}], will retry... 
E 2021-05-13T08:08:52.337537Z Catched exception class io.zeebe.engine.processing.bpmn.BpmnProcessingException with message Expected to take tr
```

**Comment by deepthidevaki** [comment]
This is most probably due to #4198 triggered by back-to-back role changes. This should be fixed in 1.0.

**Comment by npepinpe** [comment]
Was this closed then? Can we close this?

**Comment by deepthidevaki** [comment]
I didn't have a detailed look at this issue. But I'm almost sure it is due to #4198. So we can close this. We can always reopen if we see this again.
