### ISSUE TITLE
Warning logs in the job worker

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7061]
**Description**

In the worker we log several things, one of it is the following warning:
```
01:42:49.069 [grpc-default-executor-399] WARN io.camunda.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
```

I'm questioning whether this really make sense, since in the worker it is expected that from time to time there are no jobs to be activated. This will cause flooding the customers logs with useless information. This happens also in our benchmarks. 

If we take a window of ~10 minutes it was logged in our cluster ~80k times.

[![log](https://user-images.githubusercontent.com/2758593/118604110-11c4b600-b7b5-11eb-8a4a-672ab072a059.png)](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22%0AtextPayload:%22Failed%20to%20activated%20jobs%20for%20worker%20benchmark-worker%20and%20job%20type%20benchmark-task%22;timeRange=2021-05-18T02:35:00.000Z%2F2021-05-18T02:42:00.000Z;summaryFields=:true:32:beginning;cursorTimestamp=2021-05-18T02:41:59.937941777Z?customFacets=&scrollTimestamp=2021-05-18T01:42:52.266113777Z&authuser=1&project=zeebe-io)

Furthermore we log in the worker RESOURCE_EXHAUSTED exceptions, which I expected are ignored?

```
I 2021-05-18T01:42:49.069958278Z io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Expected to activate jobs of type 'benchmark-task', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[app.jar:1.1.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [app.jar:1.1.0-SNAPSHOT]
	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [app.jar:1.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2021-05-18T01:42:49.148067121Z 01:42:49.147 [grpc-default-executor-396] WARN  io.camunda.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
 
```

Example log https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-05-18T01:41:31.243000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-20-f8b1a83e1-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22&scrollTimestamp=2021-05-18T01:42:49.707280450Z&dateRangeStart=2021-05-18T00:41:31.243Z&dateRangeEnd=2021-05-18T02:41:31.243Z

**Comment by Zelldon** [comment]
Proposal would be to catch the rpc exception and based on the state log it on different levels

**Comment by npepinpe** [comment]
I would propose to filter out RESOURCE_EXHAUSTED as the worker already correctly back offs (which is what you should do when receiving it), so there's nothing for the user to be done.
