### ISSUE TITLE
Gateway flood log with errors on connectivity issues

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7074]
**Description**

Currently if we can't reach any broker or were not able to send a request to a partition, we log an error `Expected to handle gRPC request, but an unexpected error occurred`, with an exception like:

```
  exception: "io.camunda.zeebe.gateway.impl.broker.RequestRetriesExhaustedException: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator
	at io.camunda.zeebe.gateway.impl.broker.RequestRetryHandler.sendRequestWithRetry(RequestRetryHandler.java:126) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.impl.broker.RequestRetryHandler.lambda$sendRequestWithRetry$1(RequestRetryHandler.java:113) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:194) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:143) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: medic-cw-19-8906ada43-benchmark-zeebe-2.medic-cw-19-8906ada43-benchmark-zeebe.medic-cw-19-8906ada43-benchmark.svc.cluster.local/10.0.28.5:26501
	Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
		at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.unix.Socket.finishConnect(Socket.java:278) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
		at java.lang.Thread.run(Thread.java:834) ~[?:?]
	Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: medic-cw-19-8906ada43-benchmark-zeebe-2.medic-cw-19-8906ada43-benchmark-zeebe.medic-cw-19-8906ada43-benchmark.svc.cluster.local/10.0.28.5:26501
	Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
		at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.unix.Socket.finishConnect(Socket.java:278) ~[netty-transport-native-unix-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
		at java.lang.Thread.run(Thread.java:834) ~[?:?]
	Suppressed: io.camunda.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (RESOURCE_EXHAUSTED): Reached maximum capacity of requests handled
		at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:194) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:143) ~[zeebe-gateway-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
		at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
" 
```

Happens quite often in our benchmarks, see this [example log](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-19T01:43:40.150000000Z&dateRangeEnd=2021-05-19T02:43:40.150Z&project=zeebe-io&authuser=1&folder&organizationId&supportedpurview=project&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=error_group(%22CMCDuu-JqtG2PA%22)%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-19-8906ada43-benchmark%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-19T01:43:10.150368000Z&dateRangeUnbound=backwardInTime&pinnedLogId=17aa786g2ftw4ay&pinnedLogTimestamp=2021-05-19T01:43:07.749972Z), Here one of the brokers were restarted at this time.

![request](https://user-images.githubusercontent.com/2758593/118767168-b14d7b80-b87d-11eb-8208-7417c30093bd.png)

**Proposal**

In general if it is an transient issue I see no need to log it, but it could also some more problematic things which we will not see if we not log it. As a compromise we could say we count to 1000 or some other magic value and only then we log it as error.

**Comment by Zelldon** [comment]
Related error groups:

 * https://console.cloud.google.com/errors/CKKbi-TGnvvJcQ?service=zeebe-gateway&time=P7D&project=zeebe-io&authuser=1&folder&organizationId&supportedpurview=project
 * https://console.cloud.google.com/errors/CMCDuu-JqtG2PA?service=zeebe-gateway&time=P7D&project=zeebe-io&authuser=1&folder&organizationId&supportedpurview=project

**Comment by npepinpe** [comment]
Please downgrade these to warnings. Potentially adding a circuit breaker in the transport layer would be useful, but it's unclear what the impact would be yet, and I need to think about it a little more. For now for sure we can downgrade the log to warning, and I can write up another issue around the circuit breaker.
