### ISSUE TITLE
Failing to process boundary event on embedded sub process on event sub process

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7097]
**Describe the bug**

See the following process:

![medic](https://user-images.githubusercontent.com/2758593/119088896-ac1d3780-ba09-11eb-9472-eda2f019abba.png)
<sub>**Note:** the process can be found here https://github.com/zeebe-io/zeebe-medic-process/blob/master/src/main/resources/medic-week.bpmn</sub>

The event sub process and its embedded sub process is active, when now the boundary event is triggered the processing fails with a class cast exception and blacklist the instance. This is hard to detect and impossible to find out for cloud users.

```
E 2021-05-20T15:00:00.017334Z Expected to successfully process event 'LoggedEvent [type=0, version=0, streamId=1, position=99550, key=2251799813731922, timestamp=1621522800007, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, intentValue=255, intent=TRIGGER, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=TIMER, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=1.0.0}' with processor, but caught an exception. Skip this event. 
E 2021-05-20T15:00:00.040708Z Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=TRIGGER, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=TIMER, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=1.0.0}, value={"elementInstanceKey":2251799813731921,"processInstanceKey":2251799813714841,"dueDate":1621522799998,"targetElementId":"Event_15xboop","repetitions":1,"processDefinitionKey":2251799813714572}}' without errors, but exception occurred with message 'class io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableBoundaryEvent cannot be cast to class io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableStartEvent (io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableBoundaryEvent and io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableStartEvent are in unnamed module of loader 'app')'. 
W 2021-05-20T15:00:00.042468Z Blacklist process instance 2251799813714841, due to previous errors. 
I 2021-05-20T15:00:00.043535Z Error record was written at 99552, we will continue with processing if event was committed. Current commit position is 99550. 
```

Good thing is that we found it out because we use our own tools for automating our processes :clap: 

**To Reproduce**

Event sub process with embedded sub process and boundary event will cause this.

**Expected behavior**

Boundary event is triggered without any issues.

**Log/Stacktrace**

<details><summary>java.lang.ClassCastException</summary>
 <p>

```
java.lang.ClassCastException: class io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableBoundaryEvent cannot be cast to class io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableStartEvent (io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableBoundaryEvent and io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableStartEvent are in unnamed module of loader 'app')
	at io.camunda.zeebe.engine.processing.common.EventHandle.activateElement(EventHandle.java:119) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.common.EventHandle.activateElement(EventHandle.java:96) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.timer.TriggerTimerProcessor.processRecord(TriggerTimerProcessor.java:119) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:296) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:286) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:254) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:219) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:210) ~[zeebe-workflow-engine-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
```

</p>
</details>

**Environment:**
 - OS: cloud
 - Zeebe Version: 1.0.0

**Comment by Zelldon** [comment]
Related error group https://console.cloud.google.com/errors/CJbOoKjByoGUbA?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1&organizationId=669107107215&supportedpurview=project
