### ISSUE TITLE
Zeebe-broker-1 and zeebe-broker-2 will remind "warn" every five minutes  io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot"

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7098]
**Describe the bug**

Zeebe-broker-1 and zeebe-broker-2 will remind "warn" every five minutes  io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot"，Is this a mistake or a good reminder？ 

Can you tell me why it's so designed？ 

Thank you very much!

The complete log is as follows：

2021-05-21 10:14:15.481 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-0] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 129247 is committed, current commit position is 129247. After that snapshot can be marked as valid. 
2021-05-21 10:14:15.568 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 129247 >= 129247, snapshot 127818-60-129246-129247 is valid and has been persisted. 
2021-05-21 10:14:15.568 [Broker-2-SnapshotStore-3] [Broker-2-zb-fs-workers-0] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/pending/127752-60-129180-129181, checksum=3348850325, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@3a122807, metadata=FileBasedSnapshotMetadata{index=127752, term=60, processedPosition=129180, exporterPosition=129181}} 
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/3/pending/127752-60-129180-129181 
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0] 
2021-05-21 10:19:15.507 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 129353 is committed, current commit position is 129353. After that snapshot can be marked as valid. 
2021-05-21 10:19:15.577 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-0] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 129353 >= 129353, snapshot 127896-60-129352-129353 is valid and has been persisted. 
2021-05-21 10:19:15.577 [Broker-2-SnapshotStore-3] [Broker-2-zb-fs-workers-1] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/pending/127818-60-129246-129247, checksum=1829222746, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@3a122807, metadata=FileBasedSnapshotMetadata{index=127818, term=60, processedPosition=129246, exporterPosition=129247}} 
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/3/pending/127818-60-129246-129247 
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0] 
2021-05-21 10:24:15.534 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-0] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 129421 is committed, current commit position is 129421. After that snapshot can be marked as valid. 
2021-05-21 10:24:15.620 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 129421 >= 129421, snapshot 127964-60-129420-129421 is valid and has been persisted. 
2021-05-21 10:24:15.620 [Broker-2-SnapshotStore-3] [Broker-2-zb-fs-workers-0] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/pending/127896-60-129352-129353, checksum=4116217319, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@3a122807, metadata=FileBasedSnapshotMetadata{index=127896, term=60, processedPosition=129352, exporterPosition=129353}} 
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/3/pending/127896-60-129352-129353 
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?] 
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?] 
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0] 
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0] 

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: k8s
 - Zeebe Version: 1.0.0
 - Configuration:  
 - clusterSize: "3"
partitionCount: "3"
replicationFactor: "3"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "9Gi"

**Comment by thirteen13Floor** [comment]
Can you tell me what is the scheduled task to perform a snapshot deletion in less than 5 minutes？Thank you very much.
