### ISSUE TITLE
MultiPartitionRecoveryTest.shouldCreateProcessInstanceOnAllPartitionsAfterRestart is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#7104]
**Summary**

- How often does the test fail? at least twice
- Does it block your work? no
- Do we suspect that it is a real failure? don't think so

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
[2021-05-21T08:08:01.749Z] [ERROR] MultiPartitionRecoveryTest.shouldCreateProcessInstanceOnAllPartitionsAfterRestart  Time elapsed: 73.794 s  <<< ERROR!

[2021-05-21T08:08:01.749Z] org.awaitility.core.ConditionTimeoutException: Condition with alias 'createInstancesOnAllPartitions' didn't complete within 10 seconds because condition with lambda expression in io.camunda.zeebe.broker.it.startup.MultiPartitionRecoveryTest was not fulfilled.

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)

[2021-05-21T08:08:01.750Z] 	at io.camunda.zeebe.broker.it.startup.MultiPartitionRecoveryTest.shouldCreateProcessInstanceOnAllPartitionsAfterRestart(MultiPartitionRecoveryTest.java:98)

[2021-05-21T08:08:01.750Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-05-21T08:08:01.750Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-05-21T08:08:01.750Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-05-21T08:08:01.750Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2021-05-21T08:08:01.750Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2021-05-21T08:08:01.750Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2021-05-21T08:08:01.750Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2021-05-21T08:08:01.750Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-05-21T08:08:01.750Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2021-05-21T08:08:01.750Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)

[2021-05-21T08:08:01.750Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)

[2021-05-21T08:08:01.750Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2021-05-21T08:08:01.750Z] 	at java.base/java.lang.Thread.run(Thread.java:834)

[2021-05-21T08:08:01.750Z] Caused by: java.util.concurrent.TimeoutException

[2021-05-21T08:08:01.750Z] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)

[2021-05-21T08:08:01.750Z] 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)

[2021-05-21T08:08:01.750Z] 	... 24 more

</pre>
</details>

**Logs**

Logs: https://gist.github.com/npepinpe/2800df66d32fc448485922106d26afe6

Had to paste it somewhere else cause it was so long...

**Comment by deepthidevaki** [comment]
Has this failed recently? I can't reproduce it locally.

**Comment by npepinpe** [comment]
Not sure. Not as far as I've seen - typically it's the AdvertisedAddress and another one about processing, but not this one. But I can't be sure, I don't scour the builds to check :smile:

**Comment by npepinpe** [comment]
Let's close it for now, we can reopen it if we see it again then.

**Comment by npepinpe** [comment]
Happened to me right now: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/7241-tests/16/tests

The failure was a bit different.

<details><summary>Failure</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2211)
	at app//io.camunda.zeebe.test.util.record.RecordingExporter$RecordIterator.hasNext(RecordingExporter.java:265)
	at java.base@11.0.10/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.10/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at app//io.camunda.zeebe.test.util.stream.StreamWrapper.exists(StreamWrapper.java:67)
	at app/zeebe.qa.integration.tests@1.1.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.lambda$waitUntilDeploymentIsDone$3(GrpcClientRule.java:102)
	at app/zeebe.qa.integration.tests@1.1.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule$$Lambda$1529/0x00000007c09b4840.getAsBoolean(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:36)
	at app//io.camunda.zeebe.test.util.TestUtil$$Lambda$1531/0x00000007c09b5040.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:89)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation$$Lambda$1533/0x00000007c09b5840.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:179)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:149)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:88)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at app//io.camunda.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at app/zeebe.qa.integration.tests@1.1.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.waitUntilDeploymentIsDone(GrpcClientRule.java:98)
	at app/zeebe.qa.integration.tests@1.1.0-SNAPSHOT/io.camunda.zeebe.broker.it.startup.MultiPartitionRecoveryTest.deploy(MultiPartitionRecoveryTest.java:132)
	at app/zeebe.qa.integration.tests@1.1.0-SNAPSHOT/io.camunda.zeebe.broker.it.startup.MultiPartitionRecoveryTest.shouldCreateProcessInstanceOnAllPartitionsAfterRestart(MultiPartitionRecoveryTest.java:94)
```

</details>

The logs are much, much too long to paste here :smile:

**Comment by npepinpe** [comment]
We can now track flakiness of tests individually via the build result dashboard. I'm closing these issues and we can reopen as we see them occur.
