### ISSUE TITLE
Failed to compute checksum

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#7179]
**Describe the bug**
A broker failed to compute a checksum when reading an entry with: `java.lang.IllegalArgumentException: mark > position: (3382775 > 3382774)`. The complete exception and stack trace can be found below. The logs also had a lot of BpmnProcessingExceptions (in the order of millions), which may be related:

```
io.zeebe.engine.processing.bpmn.BpmnProcessingException: Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. [context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, elementInstanceKey=2251799830767258, flowScopeKey=2251799830689014, processInstanceKey=2251799830689014, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.verifyTransition(BpmnStateTransitionBehavior.java:175) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionTo(BpmnStateTransitionBehavior.java:161) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToActivated(BpmnStateTransitionBehavior.java:92) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onActivating$1(SubProcessProcessor.java:53) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onActivating(SubProcessProcessor.java:52) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onActivating(SubProcessProcessor.java:23) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:165) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:106) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.reprocessRecord(ReProcessingStateMachine.java:405) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$7(ReProcessingStateMachine.java:371) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$4(ReProcessingStateMachine.java:343) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
```

**Log/Stacktrace**

https://console.cloud.google.com/errors/CN-1hYHWy96NSg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911&authuser=1&folder&organizationId=669107107215
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalArgumentException: mark > position: (3382775 > 3382774)
	at java.nio.Buffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.MappedByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.DirectByteBufferR.<init>(Unknown Source) ~[?:?]
	at java.nio.DirectByteBufferR.duplicate(Unknown Source) ~[?:?]
	at java.nio.DirectByteBufferR.asReadOnlyBuffer(Unknown Source) ~[?:?]
	at io.zeebe.journal.file.ChecksumGenerator.compute(ChecksumGenerator.java:27) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.record.JournalRecordReaderUtil.read(JournalRecordReaderUtil.java:64) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.readNext(MappedJournalSegmentReader.java:124) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.next(MappedJournalSegmentReader.java:73) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.MappedJournalSegmentReader.seek(MappedJournalSegmentReader.java:102) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalReader.seek(SegmentedJournalReader.java:100) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournal.resetTail(SegmentedJournal.java:561) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalWriter.lambda$deleteAfter$0(SegmentedJournalWriter.java:95) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.prometheus.client.Histogram$Child.time(Histogram.java:204) ~[simpleclient-0.10.0.jar:?]
	at io.zeebe.journal.file.JournalMetrics.observeSegmentTruncation(JournalMetrics.java:78) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournalWriter.deleteAfter(SegmentedJournalWriter.java:82) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.journal.file.SegmentedJournal.deleteAfter(SegmentedJournal.java:109) ~[zeebe-journal-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.storage.log.RaftLog.truncate(RaftLog.java:178) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:583) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:532) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:390) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:194) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$10(RaftContext.java:229) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$17(RaftContext.java:240) ~[atomix-cluster-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-1.0.0-alpha4.jar:1.0.0-alpha4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.0.0-alpha4
 - Configuration:

**Comment by npepinpe** [comment]
As this is in alpha4, do we think it would still affect 1.0 or would we have fixed it/prevent it?

**Comment by npepinpe** [comment]
Looking at the logs, we can see that zeebe-2 first becomes leader, then quickly becomes follower again. In alpha4 we still had issues with concurrent writing/reading, which is most likely what happened here. Let's close it and see if it happens in the latest stable versions.
