### ISSUE TITLE
io.camunda.zeebe.broker.exporter.repo.ExporterLoadException: Cannot load exporter [elasticsearch]

### ISSUE THREAD

**Issue by denissabramovs** [camunda-cloud/zeebe#7185]
**Describe the bug**
Can't start pods with brokers. Errors in the logs:

`io.camunda.zeebe.broker.exporter.repo.ExporterLoadException: Cannot load exporter [elasticsearch]: cannot load specified class`

**Others errors are below in the stack.**

**To Reproduce**
Upgrade from v1 to latest.

**Expected behavior**
All work fine and pods are starting.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889773342Z Caused by: java.lang.ClassNotFoundException: io.zeebe.exporter.ElasticsearchExporter
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889779855Z      at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889784353Z      at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889791726Z      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889797027Z      at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:78) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889802317Z      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:438) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.889807496Z      ... 23 more
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.897715013Z 2021-06-03 13:26:52.895 [] [main] INFO 
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.897753535Z       org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.897762232Z 
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.897767711Z Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971794287Z 2021-06-03 13:26:52.967 [] [main] ERROR
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971847757Z       org.springframework.boot.SpringApplication - Application run failed
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971858216Z java.lang.IllegalStateException: Failed to execute CommandLineRunner
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971864127Z      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971870740Z      at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971877673Z      at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971882963Z      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971888213Z      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971912028Z      at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [camunda-cloud-zeebe-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971917498Z Caused by: io.camunda.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971922307Z      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:188) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971927577Z      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971952553Z      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971958856Z      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971963494Z      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971968503Z      ... 5 more
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971973693Z Caused by: java.lang.IllegalStateException: Failed to load exporter with configuration: ExporterCfg{, jarPath='null', className='io.zeebe.exporter.ElasticsearchExporter', args={url=http://elasticsearch-master:9200}}
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971979143Z      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:440) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971984113Z      at io.camunda.zeebe.broker.Broker.lambda$partitionsStep$22(Broker.java:408) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.971993311Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972001897Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972013139Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972018509Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972023588Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972028818Z      at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:426) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972033677Z      at io.camunda.zeebe.broker.Broker.lambda$initStart$10(Broker.java:234) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972040530Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972047683Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972055057Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972062180Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972069164Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972076287Z      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972092287Z      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972099390Z      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972105111Z      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972111914Z      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972118466Z      ... 5 more
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972123636Z Caused by: io.camunda.zeebe.broker.exporter.repo.ExporterLoadException: Cannot load exporter [elasticsearch]: cannot load specified class
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972129036Z      at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:81) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972134336Z      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:438) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972139476Z      at io.camunda.zeebe.broker.Broker.lambda$partitionsStep$22(Broker.java:408) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972145687Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972150746Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972156688Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972163100Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972169462Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972178349Z      at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:426) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972184911Z      at io.camunda.zeebe.broker.Broker.lambda$initStart$10(Broker.java:234) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972190741Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972197224Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972203576Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972210589Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972219225Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972232560Z      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972237951Z      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972242920Z      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972251367Z      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972258119Z      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972264561Z      ... 5 more
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972269320Z Caused by: java.lang.ClassNotFoundException: io.zeebe.exporter.ElasticsearchExporter
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972274660Z      at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972279048Z      at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972284118Z      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972289398Z      at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:78) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972296882Z      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:438) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972302122Z      at io.camunda.zeebe.broker.Broker.lambda$partitionsStep$22(Broker.java:408) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972306871Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972313313Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972320386Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972327960Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972334483Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972341546Z      at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:426) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972346525Z      at io.camunda.zeebe.broker.Broker.lambda$initStart$10(Broker.java:234) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972351475Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972356814Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972367986Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972373045Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972377844Z      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972383084Z      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972388083Z      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972392892Z      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972397611Z      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972402440Z      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T13:26:52.972407429Z      ... 5 more
```

</p>
</details>

**Environment:**
 - OS: Linux/Kubernetes
 - Zeebe Version: 1.1.0-alpha1
 - Configuration: default

**Comment by denissabramovs** [comment]
Ok, this one is probably related to this:
https://github.com/camunda-community-hub/zeebe-cluster-helm/commit/404d1d7d6c0b66443bb34b49a7f5c1d4081a1548

**Comment by denissabramovs** [comment]
Closing this one. It fixed it.
