### ISSUE TITLE
Failed to take snapshot because RocksDb is shutting down

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#7188]
**Describe the bug**
Taking a snapshot in middle of shutting down resulted in: `io.camunda.zeebe.db.ZeebeDbException: Failed to take snapshot in path /usr/local/zeebe/data/raft-partition/partitions/1/pending/270685-24-270663-270664.`. We can prevent this by looking at the exception's status and ignore it if it's due to a shutdown being in progress.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CNON5Mv1u8qCiQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.db.ZeebeDbException: Failed to take snapshot in path /usr/local/zeebe/data/raft-partition/partitions/1/pending/270685-24-270663-270664.
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.createSnapshot(ZeebeTransactionDb.java:131) ~[zeebe-db-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.lambda$takeSnapshot$0(StateControllerImpl.java:178) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.takeInternal(FileBasedTransientSnapshot.java:67) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$take$0(FileBasedTransientSnapshot.java:53) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: org.rocksdb.RocksDBException: ShutdownInProgress
	at org.rocksdb.Checkpoint.createCheckpoint(Native Method) ~[rocksdbjni-6.19.3.jar:?]
	at org.rocksdb.Checkpoint.createCheckpoint(Checkpoint.java:51) ~[rocksdbjni-6.19.3.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.createSnapshot(ZeebeTransactionDb.java:128) ~[zeebe-db-1.0.0.jar:1.0.0]
	... 9 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by npepinpe** [comment]
What's the impact? I imagine it's just noise, but it would affect how we triage it.

**Comment by MiguelPires** [comment]
Yes, at this stage the state controller is already closing so I think the impact is minimal

**Comment by Zelldon** [comment]
This is still occurring. https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T13:02:54.303924780Z&dateRangeStart=2021-09-20T12:13:59.690Z&dateRangeEnd=2021-09-20T14:13:59.690Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&pinnedLogId=y50stymydiicngag&pinnedLogTimestamp=2021-09-20T13:02:50.806483Z&scrollTimestamp=2021-09-20T13:02:56.600010000Z

**Comment by npepinpe** [comment]
To clarify, this is due to the broker taking a snapshot while we're shutting down/transitioning? Aren't we closing the snapshot director first?

**Comment by Zelldon** [comment]
Yes but i created today several issues where we it seem we still take snapshots 🤷‍♂️

**Comment by npepinpe** [comment]
Fixed in 1.2.0
