### ISSUE TITLE
Nightly QA run against stable/0.26 is not able to start

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7237]
**Description**

The nightly QA run against `stable/0.26` has not been able to start recently, because the generation (`Zeebe 0.26.1`) could not be found.

```
java.lang.IllegalArgumentException: Unable to find generation 'Zeebe 0.26.1'; closest candidates: ['Zeebe 0.26.4', 'Zeebe 1.0.0', 'Zeebe SNAPSHOT']; available candidates: ['Zeebe 0.26.4', 'Zeebe 1.0.0', 'temp_JkwthydS5w', 'Zeebe SNAPSHOT', 'temp_dhfJjCvNe3', 'Zeebe 1.1.0-alpha1', 'temp_awAFAx7ivg', 'temp_h9pALGolXe', 'temp_TJMBiOnciF', 'temp_wElO5ghnr1', 'temp_nVMSuXByOh', 'temp_YZm9zJlz4J', 'temp_1y1KWnbj0A', 'temp_md16fhQy9I', 'temp_Msl2rIoTkL', 'temp_1JkAmfNm35', 'temp_guiWpq9Duz', 'temp_GqvPofODce', 'temp_f3ECcg4Oah'] at io.zeebe.clustertestbench.handler.CreateGenerationInCamundaCloudHandler.lambda$lookupTemplate$1(CreateGenerationInCamundaCloudHandler.java:92) at io.vavr.control.Either.getOrElseThrow(Either.java:342) at io.zeebe.clustertestbench.handler.CreateGenerationInCamundaCloudHandler.lookupTemplate(CreateGenerationInCamundaCloudHandler.java:92) at io.zeebe.clustertestbench.handler.CreateGenerationInCamundaCloudHandler.handle(CreateGenerationInCamundaCloudHandler.java:34) at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by korthout** [comment]
Should've been closed by #7238, but somehow didn't close on merge
