### ISSUE TITLE
Failed to purge pending snapshots

### ISSUE THREAD

**Issue by denissabramovs** [camunda-cloud/zeebe#7245]
**Describe the bug**
Can't communicate to zeebe. Timeouts happening in our apps. From logs we found this:

`Failed to purge pending snapshots, which may result in unnecessary disk usage and should be monitored`

**To Reproduce**
Use latest alpha image in kubernetes/docker

**Expected behavior**
All brokers are up and running.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931825252Z       io.atomix.raft.roles.LeaderRole - RaftServer{raft-partition-partition-1}{role=LEADER} - Failed to purge pending snapshots, which may result in unnecessary disk usage and should be monitored
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931830592Z java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout after: 2147483647 MILLISECONDS
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931834502Z      at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:110) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931868172Z      at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931872082Z      at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931876002Z      at io.atomix.raft.roles.PassiveRole.stop(PassiveRole.java:85) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931879912Z      at io.atomix.raft.roles.LeaderRole.stop(LeaderRole.java:96) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931910213Z      at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:509) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931914223Z      at io.atomix.raft.roles.LeaderAppender.failAttempt(LeaderAppender.java:178) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931917953Z      at io.atomix.raft.roles.AbstractAppender.handleAppendResponseFailure(AbstractAppender.java:213) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931921833Z      at io.atomix.raft.roles.LeaderAppender.handleAppendResponseFailure(LeaderAppender.java:150) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931925583Z      at io.atomix.raft.roles.AbstractAppender.lambda$sendAppendRequest$0(AbstractAppender.java:198) ~[atomix-cluster-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931929473Z      at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931933813Z      at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931937563Z      at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931941233Z      at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931946713Z      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931950433Z      at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931954023Z      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931957713Z      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931961263Z      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931964873Z      at java.lang.Thread.run(Unknown Source) [?:?]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931968473Z Caused by: java.util.concurrent.TimeoutException: Timeout after: 2147483647 MILLISECONDS
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931972473Z      at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931976293Z      at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108) ~[zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:28.931980063Z      ... 19 more
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:38.724951352Z 2021-06-09 23:58:38.724 [] [raft-server-0-raft-partition-partition-1] WARN 
zeebe-cluster-zeebe-0 zeebe-cluster 2021-06-09T23:58:38.724981492Z       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Poll request to 2 failed: java.util.concurrent.TimeoutException: Request type raft-partition-partition-1-poll timed out in 5000 milliseconds
zeebe-cluster-zeebe-1 zeebe-cluster 2021-06-10T10:44:24.370947589Z 2021-06-10 10:44:24.370 [] [raft-server-1-raft-partition-partition-3] WARN 
zeebe-cluster-zeebe-1 zeebe-cluster 2021-06-10T10:44:24.370994177Z       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 2 failed: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-poll timed out in 5000 milliseconds
```

</p>
</details>

**Environment:**
 - OS: Linux/Kubernetes
 - Zeebe Version: 1.1.0-alpha1
 - Configuration: default

**Comment by npepinpe** [comment]
Hey @denissabramovs! The most interesting part for me is the gigantic time out:

```
java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout after: 2147483647 MILLISECONDS
```

i.e. 2147483 seconds, or ~24 days. The error itself  (the failure to purge pending snapshots) is typically not too important, as it just means you have some garbage and may use too much disk. This can sometimes happen due to transient errors (it's I/O after all), but I'm not expecting it to take 24 days :scream: 

It sounds to me like that error is just a symptom of something else. You said that Zeebe is completely unresponsive? Can elaborate? What error code is returned when you send a request? Is it every request as well, or most of them? When did it start being unresponsive? If you could share the logs from around the time it started being unresponsive - something like 12 hours before and 12 hours after?

Also if you could share some metrics, that would be great. If you're running Grafana with our standard dashboard, it would be great if you could share the snapshot publicly, for example via Raintank: https://grafana.com/docs/grafana/latest/sharing/share-dashboard/#publish-a-snapshot

That would help us a lot to diagnose what happened at the time.

**Comment by npepinpe** [comment]
Marking as stale for now due to lack of activity, and closing in a month (barring any new information of course)
