### ISSUE TITLE
Following Java Cliente Instructions

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7277]
Hello,

I am following the Java Client steps and when I have to deploy I get an exception...

This is the code in my main(I changed the name of the bpmn file, I know):

final ZeebeClient client = ZeebeClient.newClientBuilder()
                // change the contact point if needed
                .gatewayAddress("127.0.0.1:26500")
                .usePlaintext()
                .build();

        System.out.println("Connected.");

        final DeploymentEvent deployment = client.newDeployCommand()
                .addResourceFromClasspath("proceso-order.bpmn")
                .send()
                .join();

        final int version = deployment.getWorkflows().get(0).getVersion();
        System.out.println("Workflow deployed. Version: " + version);

        client.close();
        System.out.println("Closed.");

This is the code in my POM.XML

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>APorEllo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.zeebe</groupId>
            <artifactId>zeebe-client-java</artifactId>
            <version>0.26.0</version>
        </dependency>
    </dependencies>

</project>

And this is the exception I get

Connected.
Exception in thread "main" io.zeebe.client.api.command.ClientStatusException: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at App.main(App.java:20)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Lzgabel** [comment]
Hi @nachoroncero, what is your broker version?  
If your broker version is 1.0.0, you should switch the client version to 1.0.0 

```
<dependency>
      <groupId>io.camunda</groupId>
      <artifactId>zeebe-client-java</artifactId>
      <version>1.0.0</version>
</dependency>
```

**Comment by nachoroncero** [comment]
Hello,

I did that, but now the IDE cannot resolve the methods or the ZeebeClient…
it is in red like it cannot be found

**Comment by Lzgabel** [comment]
Hi @nachoroncero, maybe you should check your broker and gateway version.

**Comment by nachoroncero** [comment]
I use docker compose with Zeebe.

Where can I see the versions?

**Comment by Lzgabel** [comment]
>  final int version = deployment.getWorkflows()

This code should be changed to

>  final int version = deployment.geprocess()

**Comment by nachoroncero** [comment]
deployment.getProcess() you mean?

or deployment.getProcesses?

**Comment by Lzgabel** [comment]
> deployment.getProcesses
Sorry, my problem, the input is missing, I have completed it.

**Comment by Lzgabel** [comment]
Hi @nachoronce, since version 1.0.0, workflow has been renamed to process. [#6843](https://github.com/camunda-cloud/zeebe/pull/6843)

**Comment by nachoroncero** [comment]
Ok, great! Thank you very much for your help!

Now it is working
