### ISSUE TITLE
Gateway misses to report failed request as metric

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7308]
**Describe the bug**

During preparing for the ZEP https://github.com/zeebe-io/enhancements/pull/16 I did some experiments to find good metrics which could show us how we can improve fail over and what the current state is.

I run a benchmark with one partition and when the leader is restarted we can see that the processing etc drops, which is expected.

![general](https://user-images.githubusercontent.com/2758593/122369623-a4947400-cf5e-11eb-9568-b7b8e47d7a30.png)

We have metrics for the gateway which should show failure rates, but they are missing data points in this particular event, which is unexpected. To note we using standalone gateway.

![grpc-error](https://user-images.githubusercontent.com/2758593/122375566-9eed5d00-cf63-11eb-8562-2cc362351c88.png)

In the logs we can see that the requests are failing.

```
I 2021-06-16T14:01:11.557431017Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at io.zeebe.ResponseChecker.run(ResponseChecker.java:41) [app.jar:1.0.0-alpha7]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[app.jar:1.0.0-alpha7]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[app.jar:1.0.0-alpha7]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:1.0.0-alpha7]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:1.0.0-alpha7]
	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:1.0.0-alpha7]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar:1.0.0-alpha7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
 
I 2021-06-16T14:01:11.567708552Z 14:01:11.567 [Thread-2] WARN  io.zeebe.ResponseChecker - Request failed
``` 

If we take a look at the grpc metrics, then we see the reason. Requests are rejected with RESOURCE_EX, which is ignored by our gateways as failure.

![reason](https://user-images.githubusercontent.com/2758593/122375663-b9bfd180-cf63-11eb-89c1-843e8fc7a4fa.png)

The problem is that the command api is turned on to early. Before the reprocessing of the stream processor is done. This is because the openFuture of the StreamProcessor is already completed [before the ReprocessingStateMachine is started](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java#L123-L145).

```java
      healthCheckTick();
      openFuture.complete(null);

      final ReProcessingStateMachine reProcessingStateMachine =
          new ReProcessingStateMachine(processingContext);

      // disable writing to the log stream but for reprocessing checks
      processingContext.disableLogStreamWriter();
      processingContext.enableReprocessingStreamWriter();

      recoverFuture = reProcessingStateMachine.startRecover(snapshotPosition);

      actor.runOnCompletion(
          recoverFuture,
          (lastReprocessedPosition, throwable) -> {
            if (throwable != null) {
              LOG.error("Unexpected error on recovery happens.", throwable);
              onFailure(throwable);
            } else {
              onRecovered(lastReprocessedPosition);
              new StreamProcessorMetrics(partitionId)
                  .recoveryTime(System.currentTimeMillis() - startTime);
            }
          });
```

This behavior distorted the metrics, like backpressure but also failure rates etc.

**To Reproduce**

Run benchmark with one partition, delete the leader and check the metrics.

**Expected behavior**

I would expect that the stream processor is only marked as open if it can work on new commands, which means after reprocessing/replay. We shoul'd only enable the command api for that partition if we are really able to handle incoming traffic.

**Environment:**
 - OS: k8
 - Zeebe Version: 1.0/snapshot/0..26/always
 - Configuration: 1 partition 3 replica

**Comment by Zelldon** [comment]
I moved on a branch the opening after reprocessing and scheduling the processing

## Base

![base-general](https://user-images.githubusercontent.com/2758593/122400850-627a2b00-cf7c-11eb-9178-2518a196f89b.png)
![base-grpc](https://user-images.githubusercontent.com/2758593/122400853-6312c180-cf7c-11eb-821c-c3683dfba766.png)
![base-gw](https://user-images.githubusercontent.com/2758593/122400857-63ab5800-cf7c-11eb-8e7c-92c1cb81c2e0.png)

## Change

![change-general](https://user-images.githubusercontent.com/2758593/122400881-68700c00-cf7c-11eb-9625-4ea360f5549f.png)
![change-grpc](https://user-images.githubusercontent.com/2758593/122400886-69a13900-cf7c-11eb-94d3-573bd3cba816.png)
![change-gw](https://user-images.githubusercontent.com/2758593/122400887-69a13900-cf7c-11eb-9445-f2e8e287972b.png)

## Results


We can see in the base that the exporting already starts before the processing after change it is more aligned. In general it looks a bit better, but not really satisfying. I played a bit with the rate interval and this changes also a lot, which we should keep in mind. It seems we currently are not really using consistenly the same value for the interval, which might lead to issues if we watch out for problems or want to correlated information.

Interesting read regarding this https://www.metricfire.com/blog/understanding-the-prometheus-rate-function/#Choosing-the-time-range-for-range-vectors

> What time range should we choose? There is no silver bullet here: at the very minimum it should be two times the scrape interval. However, in this case the result will be very “sharp”: all of the changes in the value would reflect in the results of the function faster than any other time range. Thereafter, the result would become 0 again swiftly. Increasing the time range would achieve the opposite - the resulting line (if you plotted the results) would become “smoother” and it would be harder to spot the spikes.

I choose for the images 30 s, our scrape interval is currently 15s. I think it is a good idea to introduce a separate variable to play around with it.
