### ISSUE TITLE
Broker doesn't come up since 9 days

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7416]
**Describe the bug**

During my morning benchmark checks I saw that we have on the `medic-cw-24-2804fc2a57-benchmark` since 21.06.2021 a Broker (Zeebe-1) which doesn't get ready.

In general the cluster seem to work, but this means we can't lose more brokers. For me it is unexpected that a Broker never comes up.

![general](https://user-images.githubusercontent.com/2758593/124078542-42e90500-da48-11eb-80df-627342c45fa4.png)

I see in the logs from today:

```
2021-07-01T06:37:57.416193Z RaftServer{raft-partition-partition-3} - AppendRequest{term=63, leader=0, prevLogIndex=1225696049, prevLogTerm=62, entries=0, commitIndex=1259914869} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message W 
2021-07-01T06:37:57.555678Z RaftServer{raft-partition-partition-2} - AppendRequest{term=69, leader=2, prevLogIndex=1227231519, prevLogTerm=68, entries=0, commitIndex=1262060697} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message W 
2021-07-01T06:37:57.740552Z RaftServer{raft-partition-partition-1} - AppendRequest{term=68, leader=0, prevLogIndex=1226706736, prevLogTerm=67, entries=0, commitIndex=1260859493} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message W 
2021-07-01T06:37:57.786647Z RaftServer{raft-partition-partition-3} - AppendRequest{term=63, leader=0, prevLogIndex=1225696049, prevLogTerm=62, entries=0, commitIndex=1259915175} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message W 
2021-07-01T06:37:57.963623Z Created segment: JournalSegment{id=43187, index=1259915369} D 
```

That the node is not reachable.

In the metrics but also in stackdriver we see that it started around ~16:12 on 21.06.2021
![gen1](https://user-images.githubusercontent.com/2758593/124078891-b723a880-da48-11eb-8899-f8eb2530a5b4.png)

```
I 2021-06-21T14:12:44.572529Z Processor starts reprocessing, until last source event position 1656232978 
W 2021-06-21T14:12:48.044536Z RaftServer{raft-partition-partition-3} - AppendRequest{term=21, leader=0, prevLogIndex=565361489, prevLogTerm=20, entries=0, commitIndex=565361490} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-06-21T14:12:48.690070Z RaftServer{raft-partition-partition-1} - AppendRequest{term=20, leader=0, prevLogIndex=565546475, prevLogTerm=19, entries=0, commitIndex=565546635} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-06-21T14:12:53.118579Z RaftServer{raft-partition-partition-2} - AppendRequest{term=22, leader=0, prevLogIndex=566109765, prevLogTerm=21, entries=0, commitIndex=566109913} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-06-21T14:13:04.189921Z RaftServer{raft-partition-partition-1} - AppendRequest{term=20, leader=0, prevLogIndex=565546475, prevLogTerm=19, entries=0, commitIndex=565546635} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
```

Taking a deeper look at stackdriver I found the following error:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 566002535, but found snapshot 0. A previous snapshot is most likely corrupted.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 566002535, but found snapshot 0. A previous snapshot is most likely corrupted.
	at io.atomix.raft.impl.RaftContext.verifySnapshotLogConsistent(RaftContext.java:195) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:171) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:258) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:232) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:148) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:106) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:120) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:200) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:202) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[zeebe-atomix-cluster-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[zeebe-atomix-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 8 more
```

https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=0&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-06-21T14:13:37.000000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-24-2804fc2a57-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-cw-24-2804fc2a57-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster-helm%22&scrollTimestamp=2021-06-21T14:13:36.440100000Z&dateRangeStart=2021-06-21T13:13:37.000Z&dateRangeEnd=2021-06-21T15:13:37.000Z&pinnedLogId=yrf602rlggj9lk4u&pinnedLogTimestamp=2021-06-21T14:11:32.110456Z

@deepthidevaki @npepinpe wasn't that something we fixed ?

**Environment:**
Medic CW 24 benchmark

**Comment by Zelldon** [comment]
If this https://github.com/camunda-cloud/zeebe/pull/7204 was the fix then I would say yes?

**Comment by deepthidevaki** [comment]
Yes. That's the fix. That means we have to investigate this :face_with_head_bandage:

**Comment by Sijoma** [comment]
I've created pvc snapshots from two brokers that were not able to start.  

[Slack discussion](https://camunda.slack.com/archives/CQZGZL03X/p1625472168001000)

Disk snapshots:

[Zeebe-0 of Namespace 46baab6e-7bcd-4cd0-8745-c3db800dd-zeebe](https://console.cloud.google.com/compute/snapshotsDetail/projects/camunda-cloud-240911/global/snapshots/trial-broker-does-not-come-up-46baab6e-7bcd-4cd0-8745-c3db800dd?project=camunda-cloud-240911)

[Zeebe-0 of Namespace 2e3e57e4-127f-43d9-87e2-80abeffe4-zeebe](https://console.cloud.google.com/compute/snapshotsDetail/projects/camunda-cloud-240911/global/snapshots/trial-broker-does-not-come-up-2e3e57e4-127f-43d9-87e2-80abeffe4?project=camunda-cloud-240911)

**Comment by Zelldon** [comment]
Haven't seen this again, I will close this for now
