### ISSUE TITLE
 Failed to activate jobs for type api from partition 14 io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-cluster-0.zeebe-cluster.uat.svc.cluster.local/192.1.3.69:26501 

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7442]
**Describe the bug**

2021-06-30 17:16:56.719 [io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-scheduler-zb-actors-0] WARN  io.camunda.zeebe.gateway - Failed to activate jobs for type api from partition 8 
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-cluster-0.zeebe-cluster.uat.svc.cluster.local/192.1.3.69:26501 
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused 
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:278) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final] 
	at java.lang.Thread.run(Unknown Source) ~[?:?] 
2021-06-30 17:16:56.747 [io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-scheduler-zb-actors-0] WARN  io.camunda.zeebe.gateway - Failed to activate jobs for type api from partition 14 
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-cluster-0.zeebe-cluster.uat.svc.cluster.local/192.1.3.69:26501 
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused 
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:278) ~[netty-transport-native-unix-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final] 
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final] 
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final] 
	at java.lang.Thread.run(Unknown Source) ~[?:?] 
**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration: 
clusterSize: "7"
partitionCount: "15"
replicationFactor: "3"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "14Gi"

**Comment by npepinpe** [comment]
Hi @thirteen13Floor - this is an expected warning. It means your gateway cannot connect to the broker. These warnings are to be expected in a distributed systems, as networks are not infallible. A warning typically indicate there is a transient issue which may indicate the system is degraded, but that it might also resolve itself. You should only need to look into it if it persists.

If you could elaborate on the issue: is this constant? What is your configuration? Can you sometimes send commands correctly?

**Comment by thirteen13Floor** [comment]
explain:

1. Zeebe server was restarted, but Zeebe gateway was not

2. 192.1.3.69:26501 this address is the IP address of Zeebe server before restart, which is requested by Zeebe gateway or the IP address of Zeebe server before restart

3. After restarting Zeebe gateway, no such alarm has been received

**Comment by thirteen13Floor** [comment]
> Hi @thirteen13Floor - this is an expected warning. It means your gateway cannot connect to the broker. These warnings are to be expected in a distributed systems, as networks are not infallible. A warning typically indicate there is a transient issue which may indicate the system is degraded, but that it might also resolve itself. You should only need to look into it if it persists.
> 
> If you could elaborate on the issue: is this constant? What is your configuration? Can you sometimes send commands correctly?

explain:

1. Zeebe server was restarted, but Zeebe gateway was not

2. 192.1.3.69:26501 this address is the IP address of Zeebe server before restart, which is requested by Zeebe gateway or the IP address of Zeebe server before restart

3. After restarting Zeebe gateway, no such alarm has been received

**Comment by npepinpe** [comment]
If I understand correctly:

1. Start broker with address zeebe-cluster-0.zeebe-cluster.uat.svc.cluster.local
2. Start standalone gateway 
3. Restart broker (presumably gets a new IP address?)
4. Gateway fails to connect to broker
5. Gateway restarts
6. Gateway can now connect to the broker

If so, it sounds like the DNS address isn't being resolved in the gateway. Can you verify if the broker does get a new IP address after restart? Then we could confirm that it's the DNS entry not being refreshed, so it still tries to contact the old IP address. That's definitely a bug, as it shouldn't happen (i.e. the TTL should be quite low for the local cache, so even if it fails it shouldn't last very long).
