### ISSUE TITLE
Operate Import Exception with latest Zeebe Docker image tagged 1.1.0

### ISSUE THREAD

**Issue by amitdash291** [camunda-cloud/zeebe#7462]
**Context**
Import on Operate (tagged [1.0.1](https://hub.docker.com/layers/camunda/operate/1.0.1/images/sha256-082039f63262c110a9863688c7663626f025eb0f20be04a9e4ed4fe1db1914c4?context=explore)) fails when one uses the latest Zeebe image tagged [1.1.0](https://hub.docker.com/layers/camunda/zeebe/1.1.0/images/sha256-dbb6c260c99013f576695be6c87a5a015e0cd6c8a50af91079ea38dd779934d4?context=explore)

**Exception Log**
```
ERROR 8 --- [import_1] i.c.o.z.ImportJob : Import is not possible for Zeebe version: 1.1
io.camunda.operate.exceptions.OperateRuntimeException: Import is not possible for Zeebe version: 1.1
 	at io.camunda.operate.zeebeimport.ImportBatchProcessorFactory.getImportBatchProcessor(ImportBatchProcessorFactory.java:40) ~[operate-qa-importer-1.0.1.jar!/:?]
 	at io.camunda.operate.zeebeimport.ImportJob.processOneIndexBatch(ImportJob.java:115) ~[operate-qa-importer-1.0.1.jar!/:?]
 	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:80) ~[operate-qa-importer-1.0.1.jar!/:?]
 	at io.camunda.operate.zeebeimport.RecordsReader.lambda$scheduleImport$1(RecordsReader.java:217) ~[operate-qa-importer-1.0.1.jar!/:?]
 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
 	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by sdorokhova** [comment]
Hi @amitdash291 ,
Operate of smaller version is not able to import Zeebe data of bigger version. It's working the other way around, Operate can import data from the same Zeebe version and one previous version.

You're slightly ahead of time, v.1.1.0 will be officially out next week (July 13). I would recommend you to use 1.0.1 for now.

Best regards,
Svetlana

**Comment by jwulf** [comment]
Operate 1.1.0 is now out.
