### ISSUE TITLE
AvailabilityTest is unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7475]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Regularly
- Does it block your work? YES
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2211)
	at app//io.camunda.zeebe.test.util.record.RecordingExporter$RecordIterator.hasNext(RecordingExporter.java:265)
	at java.base@11.0.10/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.10/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at app//io.camunda.zeebe.test.util.stream.StreamWrapper.exists(StreamWrapper.java:67)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.lambda$waitUntilDeploymentIsDone$3(GrpcClientRule.java:102)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule$$Lambda$1632/0x00000007c0963040.getAsBoolean(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:36)
	at app//io.camunda.zeebe.test.util.TestUtil$$Lambda$1634/0x00000007c0963c40.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:89)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation$$Lambda$1636/0x00000007c0964440.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:179)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:149)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:88)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at app//io.camunda.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.waitUntilDeploymentIsDone(GrpcClientRule.java:98)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.deployProcess(GrpcClientRule.java:177)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.clustering.AvailabilityTest.setup(AvailabilityTest.java:59)
	at java.base@11.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.10/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

What do I know

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[log.txt](https://github.com/camunda-cloud/zeebe/files/6795011/log.txt)

**Comment by Zelldon** [comment]
https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/develop/591/tests

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/765/tests
https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/763/tests/
https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/762/tests/ 

etc.

**Comment by npepinpe** [comment]
It started being flaky between the 8th and the 9th, so it's something we merged on the 8th. On the 8th, we only merged things related to the commit listeners and log streams, so it sounds like it might be something related to this.

**Comment by Zelldon** [comment]
@npepinpe yes was also my feeling and it seems to be fixed with https://github.com/camunda-cloud/zeebe/pull/7474, because here it is not failing anymore.

**Comment by npepinpe** [comment]
Alright, let's merge that and see if it occurs again before spending more time here then :+1:

**Comment by npepinpe** [comment]
Seems it's still flaky even with that PR - the merge build failed due to it.

**Comment by Zelldon** [comment]
```
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 1>.
10:52:37.786 [Broker-1-LogAppender-2] [Broker-1-zb-actors-0] ERROR io.camunda.zeebe.logstreams - Actor Broker-1-LogAppender-2 failed in phase STARTED.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 1>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by Zelldon** [comment]
I have the feeling it is related to Deployments and there positions.

Output from `shouldDistributeDeploymentAfterDiskSpaceAvailableAgain (Flaky Test) – DiskSpaceRecoveryClusteredTest(it-testrun)`

```
12:17:18.821 [Broker-1-ManagementRequestHandler] [Broker-1-zb-actors-0] DEBUG io.camunda.zeebe.broker.process.repository - Deployment DISTRIBUTE command for deployment 2251799813685250 was written on partition 2
12:17:18.823 [] [netty-messaging-event-epoll-client-22] WARN  io.camunda.zeebe.broker.process.repository - Received rejected deployment push due to error of type RESOURCE_EXHAUSTED: 'Broker 2 is out of disk space. Rejecting deployment request.'. Will be retried after a delay
12:17:18.933 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAwAAAAMAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3ODcwBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4yLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIQDAGpvYnNBdmFpbGFibOWnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTKnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTM=}
12:17:18.933 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - gateway - Member metadata changed Member{id=2, address=0.0.0.0:7881, properties={brokerInfo=EADJAAAAAwACAAAAAwAAAAMAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3ODgwBQABAwAAAAAMAAEDAAAAAQAAAAAAAAAOAAAAMS4yLjAtU05BUFNIT1QFAAEDAAAAAA==}}
12:17:18.933 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Member metadata changed Member{id=0, address=0.0.0.0:7871, properties={brokerInfo=EADJAAAAAwAAAAAAAwAAAAMAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3ODcwBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4yLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIQDAGpvYnNBdmFpbGFibOWnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTKnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTM=}}
12:17:18.934 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - gateway - Member metadata changed Member{id=0, address=0.0.0.0:7871, properties={brokerInfo=EADJAAAAAwAAAAAAAwAAAAMAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3ODcwBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4yLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIQDAGpvYnNBdmFpbGFibOWnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTKnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTM=}}
12:17:18.934 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.camunda.zeebe.gateway - Received metadata change from Broker 2, partitions {3=LEADER}, terms {3=1} and health {3=UNHEALTHY}.
12:17:18.934 [Broker-2-TopologyManager] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
12:17:18.934 [io.camunda.zeebe.broker.system.monitoring.DiskSpaceUsageMonitor] [Broker-2-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Disk space available again. Current available 107374182400 bytes
12:17:18.934 [Broker-2-SubscriptionApi] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Broker has disk space available again. All requests with topic subscription will be accepted.
12:17:18.934 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Member metadata changed Member{id=0, address=0.0.0.0:7871, properties={brokerInfo=EADJAAAAAwAAAAAAAwAAAAMAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3ODcwBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4yLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIQDAGpvYnNBdmFpbGFibOWnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTKnZGVwbG95bWVudC1yZXNwb25zZS0yMjUxNzk5ODEzNjg1MjUwLTM=}}
12:17:18.934 [Broker-2-ManagementRequestHandler] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.broker.clustering - Broker has disk space available again. All requests with topic deployment will be accepted.
12:17:18.934 [Broker-2-ZeebePartition-3] [Broker-2-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Disk space usage is below threshold. Resuming stream processor.
12:17:18.934 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.camunda.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=1} and health {1=HEALTHY}.
12:17:18.934 [Broker-1-TopologyManager] [Broker-1-zb-actors-1] DEBUG io.camunda.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
12:17:18.934 [Broker-2-StreamProcessor-3] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.logstreams - Resumed processing for partition 3
12:17:18.950 [] [raft-server-1-raft-partition-partition-2] ERROR io.camunda.zeebe.logstreams - Failed to append block with last event position 1.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 2 when appending positions <1, 1>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) [zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Output from `AvailabilityTest`:

```

12:11:58.782 [Broker-2-StreamProcessor-3] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.broker.process.repository - Distribute deployment 6755399441055746 to partition 2.
12:11:58.818 [Broker-1-ManagementRequestHandler] [Broker-1-zb-actors-1] DEBUG io.camunda.zeebe.broker.process.repository - Deployment DISTRIBUTE command for deployment 6755399441055746 was written on partition 2
12:11:58.819 [Broker-2-StreamProcessor-3] [Broker-2-zb-actors-1] DEBUG io.camunda.zeebe.broker.process.repository - Distribute deployment 6755399441055746 to partition 3.
12:11:58.823 [Broker-2-ManagementRequestHandler] [Broker-2-zb-actors-0] DEBUG io.camunda.zeebe.broker.process.repository - Deployment DISTRIBUTE command for deployment 6755399441055746 was written on partition 3
12:11:58.835 [] [raft-server-0-raft-partition-partition-1] ERROR io.camunda.zeebe.logstreams - Failed to append block with last event position 5.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 5>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) [zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
12:11:58.836 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
12:11:58.836 [Broker-2-LogAppender-3] [Broker-2-zb-actors-0] ERROR io.camunda.zeebe.logstreams - Actor Broker-2-LogAppender-3 failed in phase STARTED.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 5>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by Zelldon** [comment]
I think I found it. The problem is this https://github.com/camunda-cloud/zeebe/blob/a21fd6f79c3439732371f97b7878db9c9f384723/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStreamPartitionStep.java#L27 We have one step, which we use for more than one partition. We install partitions concurrently, and it can happen that we overwrite the field concurrently on opening, which causes that we reuse it on another logstream etc.


Nice to see here:

```
12:11:58.835 [] [raft-server-0-raft-partition-partition-1] ERROR io.camunda.zeebe.logstreams - Failed to append block with last event position 5.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 5>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) [zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
12:11:58.836 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
12:11:58.836 [Broker-2-LogAppender-3] [Broker-2-zb-actors-0] ERROR io.camunda.zeebe.logstreams - Actor Broker-2-LogAppender-3 failed in phase STARTED.
java.lang.IllegalStateException: Unexpected position 1 was encountered after position 1 when appending positions <1, 5>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

We get an exception on raft partition one and this is bubbled up to LogAppend from partition three, which should be unrelated right? The deployment distribution is correctly written the dispatcher (with pos 1, since it is the first on partition 3) but it uses the wrong LogStorage to write to.

**Comment by npepinpe** [comment]
Well I was planning on working on it today, but I guess if you already opened a PR :sweat_smile:

**Comment by npepinpe** [comment]
Generally we should be wary of reusing these step objects if they carry state internally. We should either make them stateless or duplicate them per partition context.
