### ISSUE TITLE
Unable to move valid snapshot because target directory not empty

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7530]
**Describe the bug**

The following exception occurred on ultrachaos: 
```
java.io.UncheckedIOException: java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/2/pending/1-1-1-2 -> /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/1-1-1-2: Directory not empty
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.moveToSnapshotDirectory(FileBasedSnapshotStore.java:477) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newSnapshot(FileBasedSnapshotStore.java:409) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:133) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:101) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.1.0.jar:1.1.0]
Caused by: java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/2/pending/1-1-1-2 -> /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/1-1-1-2: Directory not empty
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixCopyFile.move(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.move(Unknown Source) ~[?:?]
	at java.nio.file.Files.move(Unknown Source) ~[?:?]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.tryAtomicDirectoryMove(FileBasedSnapshotStore.java:505) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.moveToSnapshotDirectory(FileBasedSnapshotStore.java:468) ~[zeebe-snapshots-1.1.0.jar:1.1.0]
	... 10 more
```

**To Reproduce**

What happened on this broker `zeebe-1`, filtered for partition 2, and cherry-picked for usefulness:

```
Broker Zeebe-1 is starting up
04:28:26.585 INFO Bootstrap Broker-1 [5/13]: cluster services
...
04:28:26.664 WARN "Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/1-1-1-2 to have checksum 1569338647, but the actual checksum is 2661628009; the snapshot is most likely corrupted. The startup will fail if there is no other valid snapshot and the log has been compacted."
04:28:26.728 INFO "Found segment file: raft-partition-partition-2-1.log"
04:28:26.801 INFO "RaftServer{raft-partition-partition-2} - Transitioning to FOLLOWER"
04:28:26.808 INFO "RaftServer{raft-partition-partition-2} - Server join completed. Waiting for the server to be READY"
...
04:28:30.288 INFO "RaftServer{raft-partition-partition-2} - Transitioning to CANDIDATE"
04:28:30.317 INFO "RaftServer{raft-partition-partition-2} - Transitioning to LEADER"
04:28:30.496 INFO "Bootstrap Broker-1 [11/13]: zeebe partitions"
04:28:30.497 INFO "Bootstrap Broker-1 partitions [1/2]: partition 2"
...
04:28:31.235 INFO"Recovered state of partition 2 from snapshot at position -1"
04:28:31.367 INFO "Bootstrap Broker-1 succeeded. Started 13 steps in 5183 ms."
04:30:31.348 DEBUG "Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/2/pending/1-1-1-2."
04:30:31.377 INFO "Finished taking temporary snapshot, need to wait until last written event position -1 is committed, current commit position is 2. After that snapshot will be committed."
04:30:31.378 DEBUG "Current commit position 2 >= -1, committing snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/1-1-1-2, checksum=1499569296, metadata=FileBasedSnapshotMetadata{index=1, term=1, processedPosition=1, exporterPosition=2}}."
04:30:31.392 ERROR "Unexpected exception occurred on moving valid snapshot."
... closing broker-1
```

**Expected behavior**

It seems the broker already found a corrupted snapshot during startup, which was logged as a warning (correct). However, when it tried to create a new snapshot, the existing corrupted snapshot blocked the move of the new valid snapshot causing an error and a stepdown/shutdown (unexpected). 

Instead, we should probably either:
- expect this exception to occur (when we've already seen that the snapshot is corrupt), log it at warning level and gracefully stepdown
- or make sure the corrupted snapshot does not block the valid snapshot when moving it

**Environment:**
- Zeebe Version: Camunda Cloud 1.1.0 (ultrachaos)

```
!what bcedcc0d-a5d2-4942-a9b2-25c7d8102ffc
:yellow_heart: found cluster Meggle Test
Channel: Alpha
Generation: Zeebe 1.1 with Optimize Beta
ClusterPlan: Production - S v10 with Optimize
DataCenter: new chaos
Status: Healthy
- Zeebe: Healthy
- Elasticsearch: Healthy
- Operate: Healthy
- Tasklist: Healthy
- Optimize: Healthy
owned by Felix Muellers Organization
SalesPlan: Internal
Expired: null
```

**Comment by korthout** [comment]
I'm giving this `Severity: Low` because the broker was able to recover after restart

**Comment by npepinpe** [comment]
Increased the severity because it only recovers once it receives a higher snapshot, until then it's in an invalid state. I would like to have this fixed with the correct solution for 1.2. Note to @pihme - this might be something we want to look into during bootstrap, as the proper solution might affect the bootstrap process (e.g. should we stop the startup if the snapshot is corrupted? but if the log was never compacted, it's safe to continue - where is that check done, etc.)

**Comment by npepinpe** [comment]
As @deepthidevaki pointed out, the broker can actually recover by itself since it will be able to become leader and process anyway, allowing it to create a new snapshot by itself.

One thing to note, is that the corrupted snapshot will never be deleted, but I will create a different issue for this.

**Comment by deepthidevaki** [comment]
This will be solved by #7531. We delete corrupted snapshots on startup. Anything else to do in this issue?
