### ISSUE TITLE
Gateway unable to deal with invalid JSON as variables payload in completeJob command

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7537]
**Describe the bug**

Gateway tried to map a completeJob command to a completeJob request to the broker. Before doing so, it ensures that the variables (a string) is valid JSON. However, if it isn't it throws a `JsonParseException`. Since the protocol allows any string, we should not throw this exception and leave it unhandled, but instead deal with it like a client error (i.e. HTTP 4XX code).

**To Reproduce**

Use the [c# client](https://github.com/camunda-community-hub/zeebe-client-csharp) to send a complete job command with any non-valid json string as variables, e.g. `{ "say": "" "" }`

**Expected behavior**

Any CompleteJob command with variables that is not a valid json should not result in a unhandled exception, but should be returned to the client with a HTTP 4XX code.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
com.fasterxml.jackson.core.JsonParseException: Invalid JSON value: { "say": "" "" }
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at io.camunda.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:171) ~[zeebe-gateway-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.RequestMapper.toCompleteJobRequest(RequestMapper.java:87) ~[zeebe-gateway-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:320) [zeebe-gateway-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.EndpointManager.completeJob(EndpointManager.java:165) [zeebe-gateway-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.GatewayGrpcService.completeJob(GatewayGrpcService.java:67) [zeebe-gateway-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1479) [zeebe-gateway-protocol-impl-1.1.0.jar:1.1.0]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [grpc-stub-1.38.1.jar:1.38.1]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.38.1.jar:1.38.1]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.38.1.jar:1.38.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.38.1.jar:1.38.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [grpc-core-1.38.1.jar:1.38.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.38.1.jar:1.38.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.38.1.jar:1.38.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:746) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2513) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2494) ~[jackson-core-2.12.3.jar:2.12.3]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convert(MsgPackConverter.java:136) ~[zeebe-protocol-impl-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:76) ~[zeebe-protocol-impl-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:71) ~[zeebe-protocol-impl-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:161) ~[zeebe-gateway-1.1.0.jar:1.1.0]
	... 15 more

```

</p>
</details>

**Environment:**
```
!what 6c468153-f38e-49ab-8b43-839e0b5c5a80
found cluster <redacted>
Channel: Stable
Generation: Zeebe 1.1.0
ClusterPlan: Production - S v10 with Worker and Optimize
DataCenter: Europe West
Status: Healthy
- Zeebe: Healthy
- Elasticsearch: Healthy
- Operate: Healthy
- Tasklist: Healthy
- Optimize: no optimize, so sad
owned by <redacted> Organization
SalesPlan: Trial
Expired: false (Thu, 19 Aug 2021 07:46:28 GMT)
```

**Comment by npepinpe** [comment]
What does the client currently sees/gets? We should return the right gRPC code (I think INVALID_ARGUMENT?), and ideally with a more descriptive message.

**Comment by korthout** [comment]
Another similar [error](https://console.cloud.google.com/errors/detail/CLi8hbaj0cm52gE;service=zeebe;time=P7D?project=camunda-cloud-240911) was reported on 8.0.5: `JsonParseException: Invalid JSON value: {"say": " " at [Source: (ByteArrayInputStream); line: 1, column: 13]`

```
com.fasterxml.jackson.core.JsonParseException: Invalid JSON value: {"say": "  "
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
	at io.camunda.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:185) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.RequestMapper.toCompleteJobRequest(RequestMapper.java:101) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:333) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.EndpointManager.completeJob(EndpointManager.java:167) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.GatewayGrpcService.completeJob(GatewayGrpcService.java:69) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1593) ~[zeebe-gateway-protocol-impl-8.0.5.jar:8.0.5]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.45.1.jar:1.45.1]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[grpc-api-1.45.1.jar:1.45.1]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[grpc-api-1.45.1.jar:1.45.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.45.1.jar:1.45.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (ByteArrayInputStream); line: 1, column: 1])
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:682) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:494) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:511) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3039) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:756) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2566) ~[jackson-core-2.13.2.jar:2.13.2]
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2547) ~[jackson-core-2.13.2.jar:2.13.2]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convert(MsgPackConverter.java:136) ~[zeebe-protocol-impl-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:76) ~[zeebe-protocol-impl-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:71) ~[zeebe-protocol-impl-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:175) ~[zeebe-gateway-8.0.5.jar:8.0.5]
	... 15 more 
```

**Comment by korthout** [comment]
> What does the client currently sees/gets? We should return the right gRPC code (I think INVALID_ARGUMENT?), and ideally with a more descriptive message.

I tested it in an integration test (where I disabled the java-client's validation for variables in json format). The client receives the following:

```
io.camunda.zeebe.client.api.command.ClientStatusException: Invalid JSON value: { "say": "" "" }
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.camunda.zeebe.it.client.command.CompleteJobTest.lambda$shouldRejectIfVariablesAreInvalid$4(CompleteJobTest.java:97)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1210)
	at io.camunda.zeebe.it.client.command.CompleteJobTest.shouldRejectIfVariablesAreInvalid(CompleteJobTest.java:90)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid JSON value: { "say": "" "" }
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 38 more
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid JSON value: { "say": "" "" }
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

So the response to the client is `INVALID_ARGUMENT`, which is correct. However, we shouldn't report an error for this.

**Comment by skayliu** [comment]
Hi, @korthout , when run the test `io.camunda.zeebe.it.client.command.CompleteJobTest.shouldRejectIfVariablesAreInvalid` , we can get this logs.

```
15:06:16.274 [] [grpc-default-executor-2] DEBUG io.camunda.zeebe.gateway - Expected to handle gRPC request, but messagepack property was invalid
io.camunda.zeebe.msgpack.MsgpackPropertyException: Property 'variables' is invalid: Expected document to be a root level object, but was 'ARRAY'
	at io.camunda.zeebe.msgpack.property.DocumentProperty.setValue(DocumentProperty.java:37) ~[classes/:?]
	at io.camunda.zeebe.msgpack.property.DocumentProperty.setValue(DocumentProperty.java:29) ~[classes/:?]
	at io.camunda.zeebe.protocol.impl.record.value.job.JobRecord.setVariables(JobRecord.java:293) ~[classes/:?]
	at io.camunda.zeebe.gateway.impl.broker.request.BrokerCompleteJobRequest.<init>(BrokerCompleteJobRequest.java:22) ~[classes/:?]
	at io.camunda.zeebe.gateway.RequestMapper.toCompleteJobRequest(RequestMapper.java:105) ~[classes/:?]
	at io.camunda.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:338) ~[classes/:?]
	at io.camunda.zeebe.gateway.EndpointManager.completeJob(EndpointManager.java:167) ~[classes/:?]
	at io.camunda.zeebe.gateway.GatewayGrpcService.completeJob(GatewayGrpcService.java:71) ~[classes/:?]
	at io.camunda.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1710) ~[classes/:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.51.0.jar:1.51.0]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[grpc-api-1.51.0.jar:1.51.0]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[grpc-api-1.51.0.jar:1.51.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355) ~[grpc-core-1.51.0.jar:1.51.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:867) ~[grpc-core-1.51.0.jar:1.51.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.51.0.jar:1.51.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.51.0.jar:1.51.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Expected document to be a root level object, but was 'ARRAY'
	at io.camunda.zeebe.msgpack.value.DocumentValue.wrap(DocumentValue.java:43) ~[classes/:?]
	at io.camunda.zeebe.msgpack.property.DocumentProperty.setValue(DocumentProperty.java:34) ~[classes/:?]
	... 18 more

```

**Comment by korthout** [comment]
@skayliu Yes, it reaches the point where the exception is logged, but that test case doesn't assert that the expected exception is only responded to the client and **not** logged. 

We want that behavior because we consider it a fault the user produces. They need to be informed about what to do differently. But it is not a system error, so it does not have to be logged.

What needs to change is that the exception is no longer logged in the gateway. It should still be responded to the client.

**Comment by jwulf** [comment]
If you pass in an array - eg: `"[\"something\"]"`, at the moment (8.6.0-alpha5) you get an ACK back from the gRPC CompleteJob call. 

However, the job does not complete, and is sent for retry. But the retry count does not decrement, because the client is completing the job, so no incident is ever raised. 

See this issue: https://github.com/camunda/camunda-8-js-sdk/issues/247
