### ISSUE TITLE
Zeebe 1.2.0-alpha1 can't start on Windows

### ISSUE THREAD

**Issue by sdorokhova** [camunda-cloud/zeebe#7600]
**Describe the bug**
When starting Zeebe on Windows 10 machine, following exception is thrown:

```
2021-08-05 08:51:30.064 [] [main] ERROR
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [11/13]: zeebe partitions failed with unexpected exception.
io.camunda.zeebe.journal.JournalException: Failed to flush journal directory after creating segment C:\programs\camunda-cloud-zeebe-1.2.0-alpha1\data\raft-partition\partitions\1\raft-partition-partition-1-1.log
        at io.camunda.zeebe.journal.file.SegmentedJournal.createSegment(SegmentedJournal.java:653) ~[zeebe-journal-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.journal.file.SegmentedJournal.open(SegmentedJournal.java:252) ~[zeebe-journal-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.journal.file.SegmentedJournal.<init>(SegmentedJournal.java:93) ~[zeebe-journal-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:133) ~[zeebe-journal-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.storage.log.RaftLogBuilder.build(RaftLogBuilder.java:123) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:175) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:176) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:258) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:232) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:189) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:156) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:114) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:120) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:204) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:206) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:63) ~[zeebe-atomix-cluster-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.start(PartitionManagerImpl.java:48) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:414) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.Broker.lambda$initStart$9(Broker.java:258) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:64) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:93) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:62) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:93) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:47) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:203) ~[zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) [zeebe-util-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.Broker.start(Broker.java:183) [zeebe-broker-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) [camunda-cloud-zeebe-1.2.0-alpha1.jar:1.2.0-alpha1]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.3.jar:2.5.3]
        at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [camunda-cloud-zeebe-1.2.0-alpha1.jar:1.2.0-alpha1]
Caused by: java.nio.file.AccessDeniedException: C:\programs\camunda-cloud-zeebe-1.2.0-alpha1\data\raft-partition\partitions\1
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:116) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
        at io.camunda.zeebe.util.FileUtil.flush(FileUtil.java:46) ~[zeebe-util-1.2.0-alpha1.jar:1.2.0-alpha1]
        at io.camunda.zeebe.journal.file.SegmentedJournal.createSegment(SegmentedJournal.java:650) ~[zeebe-journal-1.2.0-alpha1.jar:1.2.0-alpha1]
```

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: Win 10
 - Zeebe Version: 1.2.0-alpha1
 - Configuration: Elasticsearch exporter

**Comment by npepinpe** [comment]
1. Let's introduce OS detection so that we have an easy way to poll what the current platform is. For now, it's enough to simply distinguish between Unix and Windows like the JVM does.
1. Make flushing a directory a noop on Windows.

The next steps would be to add a smoke test using GitHub actions - you can run actions on Windows machine. I'm not yet sure what it should be (ideas welcome), but for now just focus on the above.
