### ISSUE TITLE
Message is published in an endless loop

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7619]
**Describe the bug**

![medic-process-instance](https://user-images.githubusercontent.com/2758593/128707951-00e4fc44-53d3-469a-b332-63e84aafbce0.png)

I published one message:

```
$ zbctl publish message "daily-duty" --correlationKey="medic"
{
  "key":  "2251799814679118"
}
```

This caused an endless loop of published messages and creation of process instances. 

![instances](https://user-images.githubusercontent.com/2758593/128707764-662ab40b-f0c4-4194-a80e-db7725e99e96.png)

The instances are created every 30 seconds. Hint from @saig0 seems to be the timeout of the message publish retry. 

![instances-every-30s](https://user-images.githubusercontent.com/2758593/128708081-cadf4fa0-82ec-46cc-a7ee-caeef43d2721.png)

When this happen on the medic cluster we had the following status:

```
$ zbctl status
Cluster size: 3
Partitions count: 2
Replication factor: 3
Gateway version: 1.1.1
Brokers:
  Broker 0 - zeebe-0.zeebe-broker-service.5e3f5d89-61ab-4acb-a8e4-dbf7aaf07ee3-zeebe.svc.cluster.local:26501
    Version: 1.1.1
    Partition 1 : Leader, Healthy
    Partition 2 : Leader, Healthy
  Broker 1 - zeebe-1.zeebe-broker-service.5e3f5d89-61ab-4acb-a8e4-dbf7aaf07ee3-zeebe.svc.cluster.local:26501
    Version: 1.1.1
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy  Broker 2 - zeebe-2.zeebe-broker-service.5e3f5d89-61ab-4acb-a8e4-dbf7aaf07ee3-zeebe.svc.cluster.local:26501
    Version: 1.1.1
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
```

Based on the message key `2251799814679118` and instance key `2251799814674814` we know that the message needs to be published on the same partition. It seems we don't get an ack (?), since we published it again and again. We also accept it on the partition side, where this should be normally ignored for the same message?

**To Reproduce**

Not sure yet.

**Expected behavior**

The message is published once and one instance is created!

**Log/Stacktrace**

I see nothing in the stackdriver logs which indicate an error.

**Environment:**
 - OS: k8 - camunda cloud int
 - Zeebe Version: 1.1.1
 - Configuration: Production - S(Production - S v9 with worker)

**Comment by Zelldon** [comment]
Small update: I investigate with zdb and it seems there are no messages persisted on the partition one, which doesn't make any sense. At least on the last snapshot. Runtime I was not able to read, since it was corrupted (due to copy the data folder).

**Comment by Zelldon** [comment]
Another update:

I can't read the log of 1.1 with zdb (which was build for 1.0). Did we changed something in the journal @deepthidevaki between the versions?



```
java.lang.IllegalArgumentException: newPosition > limit: (9 > 0)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
	at java.base/java.nio.Buffer.position(Buffer.java:293)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
	at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:226)
	at io.camunda.zeebe.journal.file.MappedJournalSegmentWriter.reset(MappedJournalSegmentWriter.java:199)
	at io.camunda.zeebe.journal.file.MappedJournalSegmentWriter.<init>(MappedJournalSegmentWriter.java:63)
	at io.camunda.zeebe.journal.file.JournalSegment.createWriter(JournalSegment.java:149)
	at io.camunda.zeebe.journal.file.JournalSegment.<init>(JournalSegment.java:61)
	at io.camunda.zeebe.journal.file.SegmentedJournal.newSegment(SegmentedJournal.java:458)
	at io.camunda.zeebe.journal.file.SegmentedJournal.loadSegment(SegmentedJournal.java:468)
	at io.camunda.zeebe.journal.file.SegmentedJournal.loadSegments(SegmentedJournal.java:516)
	at io.camunda.zeebe.journal.file.SegmentedJournal.open(SegmentedJournal.java:225)
	at io.camunda.zeebe.journal.file.SegmentedJournal.<init>(SegmentedJournal.java:82)
	at io.camunda.zeebe.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:133)
	at io.atomix.raft.storage.log.RaftLogBuilder.build(RaftLogBuilder.java:137)
	at io.zell.zdb.log.LogFactory$Companion.newReader(LogFactory.kt:23)
	at io.zell.zdb.log.LogStatus.<init>(LogStatus.kt:9)
	at io.zell.zdb.LogCommand.status(LogCommand.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1952)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at io.zell.zdb.ZeebeDebugger.main(ZeebeDebugger.java:51)
```

**Comment by deepthidevaki** [comment]
None that I'm aware of. Is this segment file empty?

**Comment by Zelldon** [comment]
Ah good point @deepthidevaki 

```
$ ll
total 131092
drwxr-xr-x 2 zell users      4096 Aug  9 15:13 pending
-rw-r--r-- 1 zell users         0 Aug  9 15:13 raft-partition-partition-1-0.log
-rw-r--r-- 1 zell users         0 Aug  9 15:13 raft-partition-partition-1-1883872643.log
-rw-r--r-- 1 zell users 134217728 Aug  9 15:13 raft-partition-partition-1-2.log
-rw-r--r-- 1 zell users        78 Aug  9 15:13 raft-partition-partition-1.conf
-rw-r--r-- 1 zell users       256 Aug  9 15:13 raft-partition-partition-1.meta
drwxr-xr-x 2 zell users      4096 Aug  9 15:13 runtime
drwxr-xr-x 3 zell users      4096 Aug  9 15:13 snapshots
```

Might be due to my copy action :see_no_evil: thanks @deepthidevaki

**Comment by Zelldon** [comment]
Another update:

**I was able to reproduce it! I** just created a new Prod S cluster on int (with worker) deployed all processed from here https://github.com/zeebe-io/zeebe-medic-process and published one message. It shows the same behavior!



![othercluster](https://user-images.githubusercontent.com/2758593/128724397-9df5c1e3-9959-4f92-b519-80a66611cbf0.png)

\cc @saig0

**Comment by Zelldon** [comment]
We have now at ~800 process instances on our medic process, it keeps going. There was no restart of the pods yet. Would be interesting how it behaves after that.

**Comment by Zelldon** [comment]
Quite easy to reproduce with a unit test. (I told you @saig0 maybe it happens always :laughing: )

It just added a `ENGINE.getClock().addTime(Duration.ofMinutes(5));` on the [NonInterruptingEventSubprocessTest.java#shouldTriggerEventSubprocess](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/subprocess/NonInterruptingEventSubprocessTest.java#L123)

```
C DEPLOYMENT         CREATE         - #045->  -1   -1 - 
E PROC               CREATED        - #046->#045 K017 - process.xml -> "proc" (version:2)
E DEPLOYMENT         CREATED        - #047->#045 K018 - process.xml
E DEPLOYMENT         FULLY_DISTR    - #048->#045 K018 - 
C PROC_INST_CREATION CREATE         - #049->  -1   -1 - new <process "proc"> with variables: {key=message-123}
E VAR                CREATED        - #050->#049 K020 - key->"message-123" in <process [K019]>
C PROC_INST          ACTIVATE       - #051->#049 K019 - PROCESS "proc" in <process "proc"[K019]>
E PROC_INST_CREATION CREATED        - #052->#049 K021 - new <process "proc"> with variables: {key=message-123}
E PROC_INST          ACTIVATING     - #053->#051 K019 - PROCESS "proc" in <process "proc"[K019]>
E PROC_MSG_SUB       CREATING       - #054->#051 K022 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATED      - #055->#051 K019 - PROCESS "proc" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #056->#051   -1 - START_EVENT "start_proc" in <process "proc"[K019]>
C MSG_SUB            CREATE         - #057->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATING     - #058->#056 K023 - START_EVENT "start_proc" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #059->#056 K023 - START_EVENT "start_proc" in <process "proc"[K019]>
C PROC_INST          COMPLETE       - #060->#056 K023 - START_EVENT "start_proc" in <process "proc"[K019]>
E MSG_SUB            CREATED        - #061->#057 K024 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
C PROC_MSG_SUB       CREATE         - #062->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" @[K019] in <process ?[K019]> (no vars)
E PROC_INST          COMPLETING     - #063->#060 K023 - START_EVENT "start_proc" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #064->#060 K023 - START_EVENT "start_proc" in <process "proc"[K019]>
E PROC_INST          SEQ_FLOW_TAKEN - #065->#060 K025 - SEQUENCE_FLOW "sequenc..12fa022" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #066->#060 K026 - SERVICE_TASK "task" in <process "proc"[K019]>
E PROC_MSG_SUB       CREATED        - #067->#062 K022 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATING     - #068->#066 K026 - SERVICE_TASK "task" in <process "proc"[K019]>
E JOB                CREATED        - #069->#066 K027 - K027 "type" @"task"[K026] 3 retries, in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATED      - #070->#066 K026 - SERVICE_TASK "task" in <process "proc"[K019]>
C MSG                PUBLISH        - #071->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 (no vars)
E MSG                PUBLISHED      - #072->#071 K028 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 (no vars)
E MSG_SUB            CORRELATING    - #073->#071 K024 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
C PROC_MSG_SUB       CORRELATE      - #074->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_MSG_SUB       CORRELATED     - #075->#074 K022 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_EVNT          TRIGGERING     - #076->#074 K029 -  @"event_sub_start"[K019] in <process K017[K019]> (no vars)
E PROC_EVNT          TRIGGERED      - #077->#074 K029 -  @"event_sub_start"[K019] in <process K017[K019]> (no vars)
E PROC_INST          ACTIVATING     - #078->#074 K030 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #079->#074 K030 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #080->#074   -1 - START_EVENT "event_sub_start" in <process "proc"[K019]>
C MSG_SUB            CORRELATE      - #081->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" (inter.) @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATING     - #082->#080 K031 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #083->#080 K031 - START_EVENT "event_sub_start" in <process "proc"[K019]>
C PROC_INST          COMPLETE       - #084->#080 K031 - START_EVENT "event_sub_start" in <process "proc"[K019]>
C TIMER              TRIGGER        - #085->  -1 K013 -  @"event_sub_start"[K003]  in <process "K001"[K003]> due T09:08:40.796
C PROC_MSG_SUB       CORRELATE      - #086->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E MSG_SUB            CORRELATED     - #087->#081 K024 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          COMPLETING     - #088->#084 K031 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #089->#084 K031 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          SEQ_FLOW_TAKEN - #090->#084 K032 - SEQUENCE_FLOW "sequenc..dae14dc" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #091->#084 K033 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E TIMER              TRIGGERED      - #092->#085 K013 -  @"event_sub_start"[K003]  in <process "K001"[K003]> due T09:08:40.796
E PROC_EVNT          TRIGGERING     - #093->#085 K034 -  @"event_sub_start"[K003] in <process K001[K003]> (no vars)
E PROC_EVNT          TRIGGERED      - #094->#085 K034 -  @"event_sub_start"[K003] in <process K001[K003]> (no vars)
E PROC_INST          ACTIVATING     - #095->#085 K035 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K003]>
E PROC_INST          ACTIVATED      - #096->#085 K035 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K003]>
C PROC_INST          ACTIVATE       - #097->#085   -1 - START_EVENT "event_sub_start" in <process "proc"[K003]>
E TIMER              CREATED        - #098->#085 K036 -  @"event_sub_start"[K003]  in <process "K001"[K003]> due T09:13:41.324
E PROC_MSG_SUB       CORRELATED     - #099->#086 K022 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_EVNT          TRIGGERING     - #100->#086 K037 -  @"event_sub_start"[K019] in <process K017[K019]> (no vars)
E PROC_EVNT          TRIGGERED      - #101->#086 K037 -  @"event_sub_start"[K019] in <process K017[K019]> (no vars)
E PROC_INST          ACTIVATING     - #102->#086 K038 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #103->#086 K038 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #104->#086   -1 - START_EVENT "event_sub_start" in <process "proc"[K019]>
C MSG_SUB            CORRELATE      - #105->  -1   -1 - "message-shouldTriggerEventSubprocess[message event subprocess]" (inter.) @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          ACTIVATING     - #106->#091 K033 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #107->#091 K033 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          COMPLETING     - #108->#091 K033 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #109->#091 K033 - END_EVENT "event_sub_end" in <process "proc"[K019]>
C PROC_INST          COMPLETE       - #110->#091 K030 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          ACTIVATING     - #111->#097 K039 - START_EVENT "event_sub_start" in <process "proc"[K003]>
E PROC_INST          ACTIVATED      - #112->#097 K039 - START_EVENT "event_sub_start" in <process "proc"[K003]>
C PROC_INST          COMPLETE       - #113->#097 K039 - START_EVENT "event_sub_start" in <process "proc"[K003]>
E PROC_INST          ACTIVATING     - #114->#104 K040 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #115->#104 K040 - START_EVENT "event_sub_start" in <process "proc"[K019]>
C PROC_INST          COMPLETE       - #116->#104 K040 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E MSG_SUB            CORRELATED     - #117->#105 K024 - "message-shouldTriggerEventSubprocess[message event subprocess]" correlationKey: message-123 @[K019] in <process "proc"[K019]> (no vars)
E PROC_INST          COMPLETING     - #118->#110 K030 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #119->#110 K030 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          COMPLETING     - #120->#113 K039 - START_EVENT "event_sub_start" in <process "proc"[K003]>
E PROC_INST          COMPLETED      - #121->#113 K039 - START_EVENT "event_sub_start" in <process "proc"[K003]>
E PROC_INST          SEQ_FLOW_TAKEN - #122->#113 K041 - SEQUENCE_FLOW "sequenc..82b2076" in <process "proc"[K003]>
C PROC_INST          ACTIVATE       - #123->#113 K042 - END_EVENT "event_sub_end" in <process "proc"[K003]>
E PROC_INST          COMPLETING     - #124->#116 K040 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #125->#116 K040 - START_EVENT "event_sub_start" in <process "proc"[K019]>
E PROC_INST          SEQ_FLOW_TAKEN - #126->#116 K043 - SEQUENCE_FLOW "sequenc..dae14dc" in <process "proc"[K019]>
C PROC_INST          ACTIVATE       - #127->#116 K044 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          ACTIVATING     - #128->#123 K042 - END_EVENT "event_sub_end" in <process "proc"[K003]>
E PROC_INST          ACTIVATED      - #129->#123 K042 - END_EVENT "event_sub_end" in <process "proc"[K003]>
E PROC_INST          COMPLETING     - #130->#123 K042 - END_EVENT "event_sub_end" in <process "proc"[K003]>
E PROC_INST          COMPLETED      - #131->#123 K042 - END_EVENT "event_sub_end" in <process "proc"[K003]>
C PROC_INST          COMPLETE       - #132->#123 K035 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K003]>
E PROC_INST          ACTIVATING     - #133->#127 K044 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          ACTIVATED      - #134->#127 K044 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          COMPLETING     - #135->#127 K044 - END_EVENT "event_sub_end" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #136->#127 K044 - END_EVENT "event_sub_end" in <process "proc"[K019]>
C PROC_INST          COMPLETE       - #137->#127 K038 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          COMPLETING     - #138->#132 K035 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K003]>
E PROC_INST          COMPLETED      - #139->#132 K035 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K003]>
E PROC_INST          COMPLETING     - #140->#137 K038 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
E PROC_INST          COMPLETED      - #141->#137 K038 - EVENT_SUB_PROCESS "event_sub_proc" in <process "proc"[K019]>
```

**Comment by saig0** [comment]
**Update**

The issue is easy to reproduce.

1. deploy a process with a non-interrupting message boundary event (or event subprocess)
2. create a new instance of this process
3. drive the instance to a point where the message can be correlated
4. publish the message once 
5. verify that the message is correlated 
6. await 30 seconds and verify that the same message is correlated again     

![image](https://user-images.githubusercontent.com/4305769/130007812-ec77b864-65e0-4b66-a177-6ecf74dad28e.png)

**Comment by saig0** [comment]
:information_source: The issue was reported by a customer: https://jira.camunda.com/browse/SUPPORT-11467
