### ISSUE TITLE
throw io.zeebe.client.api.command.ClientStatusException: RST_STREAM closed stream. HTTP/2 error code: CANCEL when messageSize reaches 3M

### ISSUE THREAD

**Issue by gakkiyomi** [camunda-cloud/zeebe#7632]
Describe the bug

Happened in every time

when variables size more than 3M ,zeebe cannot work

![image](https://user-images.githubusercontent.com/41406557/129192774-ddb8dfc1-bd12-436f-8041-58c6e4d0b35d.png)

`result['VMPolicyContent'] = new byte[1024 * 1024 * 3]
  client.newCompleteCommand(job.getKey()).variables(result).send().join()`
                

Related LOG output:

2021-08-12 18:54:37.571 [pool-3-thread-10] [] ERROR worker.Worker - transfer Paloalto 32e6f0a8-28b8-430f-9d70-99a318ffcfe0 policy error,reason:
io.zeebe.client.api.command.ClientStatusException: RST_STREAM closed stream. HTTP/2 error code: CANCEL
	at io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.zeebe.client.api.ZeebeFuture$join.call(Unknown Source)
	at worker.Worker$_registerPolicyWorker_closure9.doCall(Worker.groovy:340)
	at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
	at com.sun.proxy.$Proxy19.handle(Unknown Source)
	at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 22 common frames omitted

when i set size 2M ,zeebe will success work
![image](https://user-images.githubusercontent.com/41406557/129192721-23010b99-1385-4b30-8914-040daf015731.png)
`

Environment:

OS: Centos7 k3s
Zeebe Version: 1.0.0
worker(use groovy)
zeebeclient Version:  io.zeebe:mzeebe-client-java:0.26.5

**Comment by Zelldon** [comment]
might related to https://github.com/camunda-cloud/zeebe/issues/4928

**Comment by npepinpe** [comment]
Hi @gakkiyomi! There is a max message size in Zeebe, although normally you would be receiving an application specific error. That you receive a RST_STREAM hints to me that possibly you have a reverse proxy in between which is limiting the size of your messages? Are you on Camunda Cloud? If not, do you run an ingress and/or reverse proxy in front of your gateway?

**Comment by gakkiyomi** [comment]
i use elasticsearch for my temp data storage now

**Comment by npepinpe** [comment]
Closing in favor of #4928. AFAIK, cancelled is returned in this case because the server (or a proxy in between) cancelled the call. If you have no proxy in between, then make sure your Zeebe `maxMessageSize` is at least greater than that. Although in the gateway, this is currently hardcoded to 4M - something we should improve in the future.
