### ISSUE TITLE
Failed to recover Broker because snapshot position was not found.

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7662]
**Describe the bug**

It seems due to latest changes we have now problems on restarting nodes. 

In general it seems to run (normal throughput etc.) but one node is not able to come up

![broker](https://user-images.githubusercontent.com/2758593/130206676-4760d49b-88a1-45bc-b5c7-8b607fc56482.png)

We see the following error on starting the corresponding broker `java.lang.IllegalStateException: Expected to find event with the snapshot position 18568732 in log stream, but nothing was found. Failed to recover 'Broker-1-StreamProcessor-2'.`

See related [stackdriver logs](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=0&project=zeebe-io&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-08-20T08:36:48.390000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-state-on-followers%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-state-on-followers%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster-helm%22%0AjsonPayload.context.loggerName!%3D%22org.elasticsearch.client.RestClient%22&scrollTimestamp=2021-08-20T08:34:22.149121000Z&pinnedLogId=fzyda4yylyezfnsr&pinnedLogTimestamp=2021-08-20T08:34:22.149121Z&dateRangeStart=2021-08-20T07:36:48.390Z&dateRangeEnd=2021-08-20T09:36:48.390Z)

**To Reproduce**

Run a benchmark from develop.

**Expected behavior**

No issues on restart.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to find event with the snapshot position 18568732 in log stream, but nothing was found. Failed to recover 'Broker-1-StreamProcessor-2'.
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:269) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:116) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: k8
 - Zeebe Version: develop 
 - Configuration: benchmark

**Comment by Zelldon** [comment]
Might be related to install request which has been send before OR https://github.com/camunda-cloud/zeebe/issues/7597 ?

**Comment by deepthidevaki** [comment]
It fails here https://github.com/camunda-cloud/zeebe/blob/bc1eeb90ab8463f892491714a4b21c634e216235/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java#L266
because the node has just received a new snapshot and has reset the log. But the events after the snapshot has not been received. So it cannot seek to that position. For a follower this is acceptable. 

My proposal is : it should fail here only if it is in PROCESSING mode. If it is on REPLAY mode, it can seek to the last event before snapshotPosition and wait for the events to be available. However it should replay the events only after the snapshot position.
