### ISSUE TITLE
Followers are exporting

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7695]
**Describe the bug**

It looks like followers are trying to export. Observed in [cw-34 benchmark](https://console.cloud.google.com/logs/viewer?interval=PT1H&project=zeebe-io&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-08-24T15%3A00%3A15.340000000Z&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22medic-cw-34-4e1897f25b-benchmark%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22medic-cw-34-4e1897f25b-benchmark-zeebe-1%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Atimestamp%3D%222021-08-24T12%3A51%3A06.055442000Z%22%0AinsertId%3D%22g943s7tngwoqy0i1%22&scrollTimestamp=2021-08-24T12%3A51%3A50.114491000Z&dateRangeEnd=2021-08-24T15%3A00%3A13.373Z&dateRangeUnbound=backwardInTime)

All partitions in this node are followers. But we see errors in exporting. See log below.

**Expected behavior**

Only leader exports.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
I 2021-08-24T12:51:06.018684Z Broker-1-StreamProcessor-1 Processor starts replay of events. [snapshot-position: 9202650, replay-mode: REPLAY]  Broker-1-StreamProcessor-1
I 2021-08-24T12:51:06.018782Z Broker-1-StreamProcessor-3 Processor starts replay of events. [snapshot-position: 8812892, replay-mode: REPLAY]  Broker-1-StreamProcessor-3
I 2021-08-24T12:51:06.019449332Z 
  
D 2021-08-24T12:51:06.033304Z Broker-1-Exporter-3 Recovering exporter from snapshot  Broker-1-Exporter-3
D 2021-08-24T12:51:06.033573Z Broker-1-ZeebePartition-1 Partition 1 transition complete, installed 9 resources!  Broker-1-ZeebePartition-1
D 2021-08-24T12:51:06.033578Z Broker-1-ZeebePartition-3 Partition 3 transition complete, installed 9 resources!  Broker-1-ZeebePartition-3
I 2021-08-24T12:51:06.034044838Z 
  
D 2021-08-24T12:51:06.038012Z Broker-1-ZeebePartition-2 Partition 2 transition complete, installed 9 resources!  Broker-1-ZeebePartition-2
I 2021-08-24T12:51:06.038617298Z 
  
I 2021-08-24T12:51:06.038814Z Broker-1-HealthCheckService All partitions are installed. Broker is ready!  Broker-1-HealthCheckService
D 2021-08-24T12:51:06.040482Z Bootstrap Broker-1 [9/11]: zeebe partitions started in 57507 ms  
I 2021-08-24T12:51:06.040927Z Bootstrap Broker-1 [10/11]: register diskspace usage listeners  
D 2021-08-24T12:51:06.041657Z Broker-1-Exporter-3 Recovered exporter 'Broker-1-Exporter-3' from snapshot at lastExportedPosition 7981613  Broker-1-Exporter-3
D 2021-08-24T12:51:06.041733Z Bootstrap Broker-1 [10/11]: register diskspace usage listeners started in 0 ms  
D 2021-08-24T12:51:06.041882Z Broker-1-Exporter-1 Recovered exporter 'Broker-1-Exporter-1' from snapshot at lastExportedPosition 8395793  Broker-1-Exporter-1
D 2021-08-24T12:51:06.041916Z Broker-1-Exporter-2 Recovered exporter 'Broker-1-Exporter-2' from snapshot at lastExportedPosition 7693251  Broker-1-Exporter-2
I 2021-08-24T12:51:06.042116Z Bootstrap Broker-1 [11/11]: upgrade manager  
D 2021-08-24T12:51:06.043009Z Broker-1-Exporter-3 Configure exporter with id 'elasticsearch'  Broker-1-Exporter-3
D 2021-08-24T12:51:06.043022Z Broker-1-Exporter-2 Configure exporter with id 'elasticsearch'  Broker-1-Exporter-2
D 2021-08-24T12:51:06.043047Z Broker-1-Exporter-1 Configure exporter with id 'elasticsearch'  Broker-1-Exporter-1
D 2021-08-24T12:51:06.043349Z Bootstrap Broker-1 [11/11]: upgrade manager started in 1 ms  
D 2021-08-24T12:51:06.043662Z Broker-1-Exporter-1 Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch-master:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=false, process=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=false, processMessageSubscription=false}, bulk=BulkConfiguration{delay=5, size=1000, memoryLimit=10485760}}  Broker-1-Exporter-1
D 2021-08-24T12:51:06.043692Z Broker-1-Exporter-2 Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch-master:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=false, process=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=false, processMessageSubscription=false}, bulk=BulkConfiguration{delay=5, size=1000, memoryLimit=10485760}}  Broker-1-Exporter-2
I 2021-08-24T12:51:06.043744Z Bootstrap Broker-1 succeeded. Started 11 steps in 57938 ms.  
D 2021-08-24T12:51:06.044601Z Broker-1-Exporter-1 Configure exporter with id 'MetricsExporter'  Broker-1-Exporter-1
D 2021-08-24T12:51:06.044670Z Broker-1-Exporter-2 Configure exporter with id 'MetricsExporter'  Broker-1-Exporter-2
D 2021-08-24T12:51:06.044693Z Broker-1-Exporter-3 Configure exporter with id 'MetricsExporter'  Broker-1-Exporter-3
I 2021-08-24T12:51:06.045244430Z 
  
D 2021-08-24T12:51:06.047457Z Broker-1-Exporter-1 Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, NULL_VAL=true, COMMAND=true, EVENT=true, SBE_UNKNOWN=true}, acceptValueTypes={PROCESS_INSTANCE_RESULT=true, DEPLOYMENT=true, VARIABLE=true, NULL_VAL=true, MESSAGE=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true, PROCESS_MESSAGE_SUBSCRIPTION=true, PROCESS=true, VARIABLE_DOCUMENT=true, PROCESS_INSTANCE=true, DEPLOYMENT_DISTRIBUTION=true, INCIDENT=true, JOB=true, ERROR=true, PROCESS_EVENT=true, TIMER=true, PROCESS_INSTANCE_CREATION=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, SBE_UNKNOWN=true}}  Broker-1-Exporter-1
D 2021-08-24T12:51:06.047459Z Broker-1-Exporter-3 Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, NULL_VAL=true, COMMAND=true, EVENT=true, SBE_UNKNOWN=true}, acceptValueTypes={PROCESS_INSTANCE_RESULT=true, DEPLOYMENT=true, VARIABLE=true, NULL_VAL=true, MESSAGE=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true, PROCESS_MESSAGE_SUBSCRIPTION=true, PROCESS=true, VARIABLE_DOCUMENT=true, PROCESS_INSTANCE=true, DEPLOYMENT_DISTRIBUTION=true, INCIDENT=true, JOB=true, ERROR=true, PROCESS_EVENT=true, TIMER=true, PROCESS_INSTANCE_CREATION=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, SBE_UNKNOWN=true}}  Broker-1-Exporter-3
D 2021-08-24T12:51:06.047472Z Broker-1-Exporter-2 Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, NULL_VAL=true, COMMAND=true, EVENT=true, SBE_UNKNOWN=true}, acceptValueTypes={PROCESS_INSTANCE_RESULT=true, DEPLOYMENT=true, VARIABLE=true, NULL_VAL=true, MESSAGE=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true, PROCESS_MESSAGE_SUBSCRIPTION=true, PROCESS=true, VARIABLE_DOCUMENT=true, PROCESS_INSTANCE=true, DEPLOYMENT_DISTRIBUTION=true, INCIDENT=true, JOB=true, ERROR=true, PROCESS_EVENT=true, TIMER=true, PROCESS_INSTANCE_CREATION=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, SBE_UNKNOWN=true}}  Broker-1-Exporter-2
W 2021-08-24T12:51:06.055442Z Broker-1-Exporter-1 Error on exporting record with key 2251799816753592  Broker-1-Exporter-1
W 2021-08-24T12:51:06.055443Z Broker-1-Exporter-3 Error on exporting record with key 6755399443976447  Broker-1-Exporter-3
W 2021-08-24T12:51:06.055443Z Broker-1-Exporter-2 Error on exporting record with key 4503599630186632  Broker-1-Exporter-2
W 2021-08-24T12:51:08.053528Z Broker-1-Exporter-2 Error on exporting record with key 4503599630186632  Broker-1-Exporter-2
W 2021-08-24T12:51:08.056393Z Broker-1-Exporter-3 Error on exporting record with key 6755399443976447  Broker-1-Exporter-3
W 2021-08-24T12:51:08.058500Z Broker-1-Exporter-1 Error on exporting record with key 2251799816753592  Broker-1-Exporter-1

```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by deepthidevaki** [comment]
Also found the following error in an exporter running on follower.

```
 "java.lang.IndexOutOfBoundsException: index=48 length=2 capacity=0
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:2259) ~[agrona-1.12.0.jar:1.12.0]
	at org.agrona.concurrent.UnsafeBuffer.getShort(UnsafeBuffer.java:867) ~[agrona-1.12.0.jar:1.12.0]
	at io.camunda.zeebe.logstreams.impl.log.LogEntryDescriptor.getMetadataLength(LogEntryDescriptor.java:165) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.getMetadataLength(LoggedEventImpl.java:107) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readMetadata(LoggedEventImpl.java:112) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$ExporterEventFilter.applies(ExporterDirector.java:513) ~[zeebe-broker-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.readNextEvent(ExporterDirector.java:349) ~[zeebe-broker-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

**Comment by deepthidevaki** [comment]
This is also causing segmentation fault in followers due to #7699
