### ISSUE TITLE
Failed to recover exporter because snapshot position not found

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7697]
**Describe the bug**

Found the following exception in a follower. [logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-08-25T08%3A55%3A09.301000000Z&dateRangeStart=2021-08-25T07%3A55%3A09.301Z&dateRangeEnd=2021-08-25T09%3A55%3A09.301Z&project=zeebe-io&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22medic-cw-34-4e1897f25b-benchmark%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22medic-cw-34-4e1897f25b-benchmark-zeebe-0%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22%0Atimestamp%3D%222021-08-25T08%3A54%3A39.301715000Z%22%0AinsertId%3D%22mkvt6s0ipcy9md0o%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-08-25T08%3A54%3A39.301715000Z)
```
exception: "java.lang.IllegalStateException: Expected to find event with the snapshot position 9698953 in log stream, but nothing was found. Failed to recover 'Broker-0-Exporter-2'.
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.recoverFromSnapshot(ExporterDirector.java:251) ~[zeebe-broker-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:165) ~[zeebe-broker-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

Looks like similar reason as #7662 
A snapshot was received just before this error, and the log is reset.

**Expected behavior**
Exporter should be able to start on the follower even if the event in the snapshot is not yet available.

**Comment by Zelldon** [comment]
@deepthidevaki this seems  to happen again in 1.2.0-alpha2. Wasn't the fix in this version? https://console.cloud.google.com/errors/CIXdgtfzz4WP9QE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Comment by deepthidevaki** [comment]
The new error is coming from the leader. In the leader we expect the event at the snapshot position to exists, otherwise it might lead to inconsistency.
```
ava.lang.IllegalStateException: Expected to find event with the snapshot position 81965 in log stream, but nothing was found. Failed to recover 'Broker-5-Exporter-74'.
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.startActiveExportingMode(ExporterDirector.java:302) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2
```
So we have to investigate why the event doesn't exists.

**Comment by Zelldon** [comment]
@npepinpe idk how to put that again into the triage queue

**Comment by deepthidevaki** [comment]
May be create a new issue? The original issue is different, as it happens on the follower and is not actually a bug. We just had to handle the case differently on the follower.

**Comment by npepinpe** [comment]
It's silly, but you remove it from the project, then add it back :smile:

**Comment by npepinpe** [comment]
But I think deepthi is correct, this is a different issue?

**Comment by Zelldon** [comment]
Replaced by #7858
