### ISSUE TITLE
Possible memory leak in follower

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7744]
**Describe the bug**

Medic benchmark CW35 is showing signs of a possible memory leak. 

See `Process memory usage` and `JVM memory usage`. Note that this occurs on 1 of the followers (zeebe-2, leader is zeebe-1). There have not been any role changes. 

<img width="1626" alt="Screen Shot 2021-09-01 at 17 34 38" src="https://user-images.githubusercontent.com/3511026/131700634-3b4e0f6c-ae73-4160-9f1d-5694f6aed98d.png"> 
<img width="1628" alt="Screen Shot 2021-09-01 at 17 35 37" src="https://user-images.githubusercontent.com/3511026/131700797-b8023d3c-ea36-4083-8d9d-223f33a57c80.png">

See [Grafana medic-cw-35-01f895df7-benchmark](http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&from=1630417641637&to=1630440978954&var-DS_PROMETHEUS=Prometheus&var-namespace=medic-cw-35-01f895df7-benchmark&var-pod=All&var-partition=All) for more details.

**Comment by deepthidevaki** [comment]
Observed high direct memory use in both followers

```
2021-08-31 17:10:02.351 CEST
Exception in thread "Broker-2-zb-actors-3" java.lang.OutOfMemoryError: Direct buffer memory at java.base/java.nio.Bits.reserveMemory(Bits.java:175) at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118) at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) at io.camunda.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:20) at io.camunda.zeebe.util.allocation.BufferAllocators.allocateDirect(BufferAllocators.java:16) at io.camunda.zeebe.dispatcher.DispatcherBuilder.initAllocatedBuffer(DispatcherBuilder.java:147) at io.camunda.zeebe.dispatcher.DispatcherBuilder.build(DispatcherBuilder.java:93) at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.openAppender(LogStreamImpl.java:280) at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createWriter(LogStreamImpl.java:208) at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$newLogStreamBatchWriter$1(LogStreamImpl.java:115) at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191)

```
zeebe-1 is the leader for all partition.
![image](https://user-images.githubusercontent.com/1997478/131825481-e62d5064-573b-40ce-951b-dfaa81006a85.png)

**Comment by deepthidevaki** [comment]
Also found many `StreamProcessor` instance in the heap dump. Most of them are already closed (checked their state), but not garbage collected. 

![image](https://user-images.githubusercontent.com/1997478/131833870-61aecb5f-91d2-492a-867f-284a3bed500c.png)

![image](https://user-images.githubusercontent.com/1997478/131834037-43d5369b-cc9e-4956-944f-64dcc6169e81.png)

Cyclic references??
![image](https://user-images.githubusercontent.com/1997478/131834244-347a2dc3-894e-46b8-b94d-2bc332eda759.png)

**Comment by deepthidevaki** [comment]
![image](https://user-images.githubusercontent.com/1997478/131837040-5da586eb-cf23-4c4c-825f-cb106b101f76.png)

**Comment by deepthidevaki** [comment]
Here https://github.com/camunda-cloud/zeebe/blob/a3156320fdb56f7fb6c252b37da32a75dfebd059/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/PartitionCommandSenderImpl.java#L34
we are adding TopologyPartitionListener as a listener to TopologyManager. But we never remove it when we close the leader.

**Comment by deepthidevaki** [comment]
It is not just the topology listener. StreamProcessor and LogStream are not garbage collected due to "several" listeners registered but never removed when a role is closed. So after a each transition, it is accumulated and eventually gits OOM on direct memory.
