### ISSUE TITLE
Leading exporter fails to recover from snapshot

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7858]
**Describe the bug**

Related to https://github.com/camunda-cloud/zeebe/issues/7697 where the exporter director was not able to recover from a snapshot, but this time it affects the leading exporter. 

[The last processed position 135435 seem to be much higher then the exported position 81965 ](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:40:36.718147000Z&dateRangeStart=2021-09-17T10:43:32.046Z&dateRangeEnd=2021-09-17T12:43:32.046Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-5%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:40:17.508848000Z&pinnedLogId=vkzyql23updjzgkn&pinnedLogTimestamp=2021-09-17T11:40:17.476640Z)

Error Group:

 * https://console.cloud.google.com/errors/CIXdgtfzz4WP9QE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

Not sure.

**Expected behavior**

We can recover from a snapshot.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to find event with the snapshot position 29067 in log stream, but nothing was found. Failed to recover 'Broker-0-Exporter-15'.
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.startActiveExportingMode(ExporterDirector.java:302) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:187) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by Zelldon** [comment]
@deepthidevaki I created a new issue and will close the other one as requested

**Comment by deepthidevaki** [comment]
Exportered position is going backward!

```
I 2021-09-17T11:26:41.275869Z Broker-5-SnapshotDirector-74 Finished taking temporary snapshot, need to wait until last written event position 135658 is committed, current commit position is 0. After that snapshot will be committed.  Broker-5-SnapshotDirector-74
D 2021-09-17T11:26:41.275991Z Broker-5-SnapshotDirector-74 Current commit position 0 >= 135658, committing snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/74/pending/37108-29-135198-114163, checksum=1827799141, metadata=FileBasedSnapshotMetadata{index=37108, term=29, processedPosition=135198, exporterPosition=114163}}.  Broker-5-SnapshotDirector-74
D 2021-09-17T11:27:46.411926Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=93950, MetricsExporter=95218}  Broker-5-Exporter-74
D 2021-09-17T11:28:05.511205Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=109486, MetricsExporter=109973}  Broker-5-Exporter-74
D 2021-09-17T11:30:43.812045Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=79161, MetricsExporter=79311}  Broker-5-Exporter-74
W 2021-09-17T11:31:55.735466Z Broker-5-SnapshotDirector-74 Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 79161 (processedPosition = 152928, exportedPosition=79161), but found no matching indexed entry which contains this position.  Broker-5-SnapshotDirector-74
D 2021-09-17T11:32:19.989153Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=76257, MetricsExporter=76410}  Broker-5-Exporter-74
D 2021-09-17T11:34:43.553658Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=78331, MetricsExporter=78331}  Broker-5-Exporter-74
W 2021-09-17T11:37:10.792469Z Broker-5-SnapshotDirector-74 Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 78331 (processedPosition = 157682, exportedPosition=78331), but found no matching indexed entry which contains this position.  Broker-5-SnapshotDirector-74
D 2021-09-17T11:38:58.719044Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=74798, MetricsExporter=74798}  Broker-5-Exporter-74
D 2021-09-17T11:39:17.772397Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=81616, MetricsExporter=81616}  Broker-5-Exporter-74
D 2021-09-17T11:40:16.765909Z Broker-5-Exporter-74 Discard job io.camunda.zeebe.broker.exporter.stream.ExporterDirector$$Lambda$2805/0x0000000840b9dc40 QUEUED from fastLane of Actor Broker-5-Exporter-74.  Broker-5-Exporter-74
D 2021-09-17T11:40:17.078054Z Broker-5-Exporter-74 Closed exporter director 'Broker-5-Exporter-74'.  Broker-5-Exporter-74
D 2021-09-17T11:40:17.084902Z Broker-5-SnapshotDirector-74 Discard job io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector$$Lambda$2809/0x0000000840b9ec40 QUEUED from fastLane of Actor Broker-5-SnapshotDirector-74.  Broker-5-SnapshotDirector-74
D 2021-09-17T11:40:36.263198Z Broker-5-Exporter-74 Recovering exporter from snapshot  Broker-5-Exporter-74
D 2021-09-17T11:40:36.263633Z Broker-5-Exporter-74 Recovered exporter 'Broker-5-Exporter-74' from snapshot at lastExportedPosition 81965  Broker-5-Exporter-74
D 2021-09-17T11:40:36.263790Z Broker-5-Exporter-74 Configure exporter with id 'elasticsearch'  Broker-5-Exporter-74

E 2021-09-17T11:40:36.265946Z Broker-5-Exporter-74 Actor 'Broker-5-Exporter-74' failed in phase STARTED with: java.lang.IllegalStateException: Expected to find event with the snapshot position 81965 in log stream, but nothing was found. Failed to recover 'Broker-5-Exporter-74'. .  Broker-5-Exporter-74
W 2021-09-17T11:41:17.516665Z Broker-5-SnapshotDirector-74 Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 81965 (processedPosition = 160400, exportedPosition=81965), but found no matching indexed entry which contains this position.  Broker-5-SnapshotDirector-74

```

**Comment by Zelldon** [comment]
@deepthidevaki good catch! that sounds terrible

**Comment by deepthidevaki** [comment]
Between the following events, there was a leader change. The new leader does not have the latest exporter position.
```
D 2021-09-17T11:28:05.511205Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=109486, MetricsExporter=109973}  Broker-5-Exporter-74
D 2021-09-17T11:30:43.812045Z Broker-5-Exporter-74 Received new exporter state {elasticsearch=79161, MetricsExporter=79311}  Broker-5-Exporter-74

```

```
D 2021-09-17T11:29:25.102508Z Broker-4-ZeebePartition-74 Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/74/snapshots/23455-8-73514-71944, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/74/snapshots/23455-8-73514-71944.checksum, checksum=3050882554, metadata=FileBasedSnapshotMetadata{index=23455, term=8, processedPosition=73514, exporterPosition=71944}}  Broker-4-ZeebePartition-74
D 2021-09-17T11:29:25.240899Z Broker-4-ZeebePartition-74 Opened database from '/usr/local/zeebe/data/raft-partition/partitions/74/runtime'.  Broker-4-ZeebePartition-74
```
