### ISSUE TITLE
Unexpected exception occurred on moving valid snapshot.

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7872]
**Describe the bug**

Error group 
https://console.cloud.google.com/errors/CMLQx8_l1uKeAQ?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

We can see earlier that [the snapshot is aborted](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T12:57:19.452263000Z&dateRangeStart=2021-09-20T12:26:34.118Z&dateRangeEnd=2021-09-20T14:26:34.118Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-20T12:57:17.901201000Z&pinnedLogId=vkq31l7nb88sua2c&pinnedLogTimestamp=2021-09-20T12:57:17.898248Z)

I think the impact is quite low, since a new snapshot will be take once or replicated.

**To Reproduce**

Again related to a benchmark we run, described here https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 

**Expected behavior**

No problems like concurrently aborting and committing an snapshot.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Snapshot is not valid. It may have been deleted.
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:127) ~[zeebe-snapshots-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:101) ~[zeebe-snapshots-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2 
 - Configuration:

**Comment by deepthidevaki** [comment]
Most likely not a bug, but incorrectly reported as an error instead of a warning or debug message.
