### ISSUE TITLE
Logstorage can't be opened in wrong term

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7874]
**Describe the bug**

[It seems that we try to open the log storage within a wrong term.](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T13:02:54.303924780Z&dateRangeStart=2021-09-20T12:13:59.690Z&dateRangeEnd=2021-09-20T14:13:59.690Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-20T13:02:53.513590000Z)

[Becoming leader with term 9 ](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T13:02:54.303924780Z&dateRangeStart=2021-09-20T12:13:59.690Z&dateRangeEnd=2021-09-20T14:13:59.690Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-20T13:02:48.475951000Z&pinnedLogId=6rd89q6j57cb6z3d&pinnedLogTimestamp=2021-09-20T13:02:48.408633Z) [wants to open log storage with 9, but internally it seem to be already changed to 10 ?!](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T13:02:54.303924780Z&dateRangeStart=2021-09-20T12:13:59.690Z&dateRangeEnd=2021-09-20T14:13:59.690Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-20T13:02:56.600167000Z&pinnedLogId=68ro8v177armrtez&pinnedLogTimestamp=2021-09-20T13:02:53.321286Z)

Error group:

https://console.cloud.google.com/errors/CNThuLCY1YXJmQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Sev: Low since we can become leader on a different node eventually (or on the same)

**To Reproduce**

This can be reproduce with this benchmark https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518

**Expected behavior**

No issues on becoming leader, and if the error is expected no error log.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected that current term '47' is same as raft term '48', but was not. Failing installation of 'LogStoragePartitionStep' on partition 6.
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.buildWrongTermException(LogStoragePartitionStep.java:111) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.checkAndCreateAtomixLogStorage(LogStoragePartitionStep.java:101) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.lambda$createWritableLogStorage$0(LogStoragePartitionStep.java:86) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.createWritableLogStorage(LogStoragePartitionStep.java:86) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.buildAtomixLogStorage(LogStoragePartitionStep.java:66) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.open(LogStoragePartitionStep.java:32) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:110) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$installPartition$2(PartitionTransitionImpl.java:119) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by npepinpe** [comment]
Superseded by https://github.com/camunda-cloud/zeebe/issues/8717
