### ISSUE TITLE
Not leader of partition

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7878]
**Describe the bug**

It seems during installing the `LogStoragePartitionStep` it can happen that the leader is no longer the leader and this fails with:
`java.lang.IllegalStateException: Not leader of partition 25`. This is logged as an error. This happens in a scenario where we had several leader changes.

I think the impact was quite low, since we eventually can become leader.

<details><summary>Log extract</summary>
 <pre>
2021-09-20 14:54:12.999 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition role transitioning from LEADER to FOLLOWER in term 2
2021-09-20 14:54:12.999 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ExporterDirector
2021-09-20 14:54:16.596 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition role transitioning from FOLLOWER to CANDIDATE in term 4
2021-09-20 14:54:17.119 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition role transitioning from CANDIDATE to LEADER in term 4
2021-09-20 14:54:18.396 CEST
zeebe-5
Broker-5-Exporter-13
Discard job io.camunda.zeebe.broker.exporter.stream.ExporterDirector$$Lambda$3135/0x0000000840b05840 QUEUED from fastLane of Actor Broker-5-Exporter-13.
2021-09-20 14:54:18.396 CEST
zeebe-5
Broker-5-Exporter-13
Discard job io.camunda.zeebe.broker.exporter.stream.ExporterDirector$$Lambda$2667/0x0000000840b9a840 QUEUED from fastLane of Actor Broker-5-Exporter-13.
2021-09-20 14:54:18.396 CEST
zeebe-5
Broker-5-Exporter-13
Discard job io.camunda.zeebe.broker.exporter.metrics.MetricsExporter$$Lambda$2687/0x0000000840ba1440 QUEUED from fastLane of Actor Broker-5-Exporter-13.
2021-09-20 14:54:18.403 CEST
zeebe-5
Broker-5-Exporter-13
Exporter closed
2021-09-20 14:54:18.403 CEST
zeebe-5
Broker-5-Exporter-13
Closed exporter director 'Broker-5-Exporter-13'.
2021-09-20 14:54:18.406 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ExporterDirector closed successfully
2021-09-20 14:54:18.407 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: RocksDB metric timer
2021-09-20 14:54:18.407 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: RocksDB metric timer closed successfully
2021-09-20 14:54:18.407 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: AsyncSnapshotDirector
2021-09-20 14:54:18.408 CEST
zeebe-5
Broker-5-SnapshotDirector-13
Discard job io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector$$Lambda$3144/0x0000000840b31840 QUEUED from fastLane of Actor Broker-5-SnapshotDirector-13.
2021-09-20 14:54:18.409 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: AsyncSnapshotDirector closed successfully
2021-09-20 14:54:18.409 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StreamProcessor
2021-09-20 14:54:18.412 CEST
zeebe-5
Broker-5-StreamProcessor-13
Closed stream processor controller Broker-5-StreamProcessor-13.
2021-09-20 14:54:18.412 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StreamProcessor closed successfully
2021-09-20 14:54:18.412 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ZeebeDb
2021-09-20 14:54:18.455 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closed database from '/usr/local/zeebe/data/raft-partition/partitions/13/runtime'.
2021-09-20 14:54:18.463 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ZeebeDb closed successfully
2021-09-20 14:54:18.463 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstream
2021-09-20 14:54:18.463 CEST
zeebe-5
Broker-5-LogStream-13
Close appender for log stream logstream-raft-partition-partition-13
2021-09-20 14:54:18.464 CEST
zeebe-5
Broker-5-LogStream-13
On closing logstream logstream-raft-partition-partition-13 close 2 readers
2021-09-20 14:54:18.465 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstream closed successfully
2021-09-20 14:54:18.465 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstorage
2021-09-20 14:54:18.465 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstorage closed successfully
2021-09-20 14:54:18.465 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: LogDeletionService
2021-09-20 14:54:18.465 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: LogDeletionService closed successfully
2021-09-20 14:54:18.466 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StateController
2021-09-20 14:54:18.466 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StateController closed successfully
2021-09-20 14:54:18.466 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition 13 closed all previous open resources, before transitioning.
2021-09-20 14:54:18.467 CEST
zeebe-5
Broker-5-ZeebePartition-13
Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/13/snapshots/7513-1-21989-21980, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/13/snapshots/7513-1-21989-21980.checksum, checksum=2600238408, metadata=FileBasedSnapshotMetadata{index=7513, term=1, processedPosition=21989, exporterPosition=21980}}
2021-09-20 14:54:22.449 CEST
zeebe-5
Broker-5-ZeebePartition-13
Opened database from '/usr/local/zeebe/data/raft-partition/partitions/13/runtime'.
2021-09-20 14:54:22.449 CEST
zeebe-5
Broker-5-ZeebePartition-13
Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/13/snapshots/7513-1-21989-21980, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/13/snapshots/7513-1-21989-21980.checksum, checksum=2600238408, metadata=FileBasedSnapshotMetadata{index=7513, term=1, processedPosition=21989, exporterPosition=21980}}'
2021-09-20 14:54:22.449 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition role transitioning from LEADER to FOLLOWER in term 5
2021-09-20 14:54:22.532 CEST
zeebe-5
Broker-5-LogStream-13
Configured log appender back pressure at partition 13 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
2021-09-20 14:54:22.533 CEST
zeebe-5
Broker-5-StreamProcessor-13
Recovering state of partition 13 from snapshot
2021-09-20 14:54:22.535 CEST
zeebe-5
Broker-5-StreamProcessor-13
Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@64210da)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@2bee9899, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@1ae5d4d0, configuration: Configuration(false)]
2021-09-20 14:54:22.540 CEST
zeebe-5
Broker-5-StreamProcessor-13
Recovered state of partition 13 from snapshot at position 22318
2021-09-20 14:54:22.542 CEST
zeebe-5
Broker-5-StreamProcessor-13
Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@36a8f61c)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@207ae4d3, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@7f8f8a15, configuration: Configuration(false)]
2021-09-20 14:54:22.544 CEST
zeebe-5
Broker-5-StreamProcessor-13
Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4b789260)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@3a918505, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@4dbaa2f8, configuration: Configuration(false)]
2021-09-20 14:54:22.545 CEST
zeebe-5
Broker-5-StreamProcessor-13
Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4e665678)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@41822646, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@778d3ade, configuration: Configuration(false)]
2021-09-20 14:54:22.547 CEST
zeebe-5
Broker-5-StreamProcessor-13
Processor starts replay of events. [snapshot-position: 22318, replay-mode: REPLAY]
2021-09-20 14:54:22.550 CEST
zeebe-5
Broker-5-Exporter-13
Recovering exporter from snapshot
2021-09-20 14:54:22.551 CEST
zeebe-5
Broker-5-Exporter-13
Recovered exporter 'Broker-5-Exporter-13' from snapshot at lastExportedPosition 21980
2021-09-20 14:54:22.551 CEST
zeebe-5
Broker-5-Exporter-13
Configure exporter with id 'elasticsearch'
2021-09-20 14:54:22.551 CEST
zeebe-5
Broker-5-Exporter-13
Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch-es-http:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=false, process=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=false, processMessageSubscription=false}, bulk=BulkConfiguration{delay=5, size=1000, memoryLimit=10485760}}
2021-09-20 14:54:22.552 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition 13 transition complete, installed 9 resources!
2021-09-20 14:54:22.552 CEST
zeebe-5
Broker-5-Exporter-13
Configure exporter with id 'MetricsExporter'
2021-09-20 14:54:22.552 CEST
zeebe-5
Broker-5-Exporter-13
Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={NULL_VAL=true, EVENT=true, SBE_UNKNOWN=true, COMMAND=true, COMMAND_REJECTION=true}, acceptValueTypes={PROCESS_INSTANCE_RESULT=true, JOB=true, JOB_BATCH=true, ERROR=true, TIMER=true, PROCESS_INSTANCE=true, MESSAGE_SUBSCRIPTION=true, PROCESS_MESSAGE_SUBSCRIPTION=true, PROCESS_EVENT=true, INCIDENT=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, DEPLOYMENT_DISTRIBUTION=true, VARIABLE=true, SBE_UNKNOWN=true, PROCESS_INSTANCE_CREATION=true, VARIABLE_DOCUMENT=true, PROCESS=true, NULL_VAL=true, MESSAGE=true, DEPLOYMENT=true}}
2021-09-20 14:54:22.552 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ExporterDirector
2021-09-20 14:54:22.553 CEST
zeebe-5
Broker-5-Exporter-13
Discard job io.camunda.zeebe.broker.exporter.stream.ExporterDirector$$Lambda$3135/0x0000000840b05840 QUEUED from fastLane of Actor Broker-5-Exporter-13.
2021-09-20 14:54:22.553 CEST
zeebe-5
Broker-5-Exporter-13
Closed exporter director 'Broker-5-Exporter-13'.
2021-09-20 14:54:22.553 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ExporterDirector closed successfully
2021-09-20 14:54:22.554 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: RocksDB metric timer
2021-09-20 14:54:22.554 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: RocksDB metric timer closed successfully
2021-09-20 14:54:22.554 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: AsyncSnapshotDirector
2021-09-20 14:54:22.554 CEST
zeebe-5
Broker-5-SnapshotDirector-13
Discard job io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector$$Lambda$3144/0x0000000840b31840 QUEUED from fastLane of Actor Broker-5-SnapshotDirector-13.
2021-09-20 14:54:22.555 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: AsyncSnapshotDirector closed successfully
2021-09-20 14:54:22.555 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StreamProcessor
2021-09-20 14:54:22.594 CEST
zeebe-5
Broker-5-StreamProcessor-13
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$3145/0x0000000840b32040 QUEUED from fastLane of Actor Broker-5-StreamProcessor-13.
2021-09-20 14:54:22.596 CEST
zeebe-5
Broker-5-StreamProcessor-13
Discard job io.camunda.zeebe.util.sched.future.FutureContinuationRunnable QUEUED from fastLane of Actor Broker-5-StreamProcessor-13.
2021-09-20 14:54:22.597 CEST
zeebe-5
Broker-5-StreamProcessor-13
Closed stream processor controller Broker-5-StreamProcessor-13.
2021-09-20 14:54:22.597 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StreamProcessor closed successfully
2021-09-20 14:54:22.599 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ZeebeDb
2021-09-20 14:54:22.655 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closed database from '/usr/local/zeebe/data/raft-partition/partitions/13/runtime'.
2021-09-20 14:54:22.705 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: ZeebeDb closed successfully
2021-09-20 14:54:22.706 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstream
2021-09-20 14:54:22.706 CEST
zeebe-5
Broker-5-LogStream-13
Close appender for log stream logstream-raft-partition-partition-13
2021-09-20 14:54:22.707 CEST
zeebe-5
Broker-5-LogStream-13
On closing logstream logstream-raft-partition-partition-13 close 1 readers
2021-09-20 14:54:22.707 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstream closed successfully
2021-09-20 14:54:22.707 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstorage
2021-09-20 14:54:22.707 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: logstorage closed successfully
2021-09-20 14:54:22.707 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: LogDeletionService
2021-09-20 14:54:22.708 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: LogDeletionService closed successfully
2021-09-20 14:54:22.708 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StateController
2021-09-20 14:54:22.708 CEST
zeebe-5
Broker-5-ZeebePartition-13
Closing Zeebe-Partition-13: StateController closed successfully
2021-09-20 14:54:22.708 CEST
zeebe-5
Broker-5-ZeebePartition-13
Partition 13 closed all previous open resources, before transitioning.
2021-09-20 14:54:22.718 CEST
zeebe-5
Broker-5-ZeebePartition-13
Expected to open step 'logstorage' but failed with
2021-09-20 14:54:22.719 CEST
zeebe-5
Broker-5-ZeebePartition-13
Failed to install leader partition 13
2021-09-20 14:54:22.723 CEST
zeebe-5
Broker-5-ZeebePartition-13
ZeebePartition-13 failed, marking it as unhealthy
2021-09-20 14:54:22.724 CEST

</pre>
</details>

**To Reproduce**

Happen in a benchmark described here https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518

**Expected behavior**

If the error is expected no error log.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Not leader of partition 25
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.lambda$createWritableLogStorage$1(LogStoragePartitionStep.java:91) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at java.util.Optional.orElseGet(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.createWritableLogStorage(LogStoragePartitionStep.java:87) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.buildAtomixLogStorage(LogStoragePartitionStep.java:66) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.LogStoragePartitionStep.open(LogStoragePartitionStep.java:32) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:110) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$installPartition$2(PartitionTransitionImpl.java:119) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by Zelldon** [comment]
Also happens with snapshot https://console.cloud.google.com/errors/CPSxlN7o1JWZDg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
