### ISSUE TITLE
Inconsistent log detected

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7880]
**Describe the bug**

I asked @Sijoma to run the same benchmark we did for 1.2.0-alpha, see comment https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 to run with SNAPSHOT and it seems that some of the errors are not occurring again BUT we still have endless leader role change loop, which seem to cause an inconsistent log!

This is quite problematic, since we can't recover on this.

Error group:

 * https://console.cloud.google.com/errors/COqdpdqD9fXk2QE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

see comment https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 

**Expected behavior**

No inconsistent log!

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.IllegalStateException: Expected that position '7110' of current event is higher then position '7115' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:167) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Expected that position '7110' of current event is higher then position '7115' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.onRecordReplayed(ReplayStateMachine.java:260) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayEvent(ReplayStateMachine.java:229) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:207) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:205) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:163) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:47) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	... 5 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-SNAPSHOT 
 - Configuration:

**Comment by Zelldon** [comment]
It might be caused due to concurrent execution of transitions.

```
I 2021-09-21T08:55:21.496533Z zeebe-0 Broker-0-ZeebePartition-20 Transition to LEADER on term 3 - executing SnapshotDirector  zeebe-0 Broker-0-ZeebePartition-20
I 2021-09-21T08:55:21.496779Z zeebe-0 Broker-0-StreamProcessor-20 Processor starts replay of events. [snapshot-position: 7104, replay-mode: PROCESSING]  zeebe-0 Broker-0-StreamProcessor-20
I 2021-09-21T08:55:21.496779Z zeebe-0 Broker-0-StreamProcessor-20 Processor starts replay of events. [snapshot-position: 7104, replay-mode: REPLAY]  zeebe-0 Broker-0-StreamProcessor-20
I 2021-09-21T08:55:21.499883Z zeebe-0 Broker-0-ZeebePartition-20 Transition to FOLLOWER on term 2 - executing SnapshotDirector  zeebe-0 Broker-0-ZeebePartition-20
I 2021-09-21T08:55:21.500245Z zeebe-0 Broker-0-ZeebePartition-20 Transition to LEADER on term 3 - executing ExporterDirector  zeebe-0 Broker-0-ZeebePartition-20
I 2021-09-21T08:55:21.501142Z zeebe-0 Broker-0-ZeebePartition-20 Transition to FOLLOWER on term 2 - executing ExporterDirector  zeebe-0 Broker-0-ZeebePartition-20
```

https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-21T08:55:51.508000000Z&dateRangeStart=2021-09-21T07:55:51.508Z&dateRangeEnd=2021-09-21T09:55:51.508Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22fb5fd8ba-2c7b-4628-a039-851ccaecb4eb-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&pinnedLogId=l05bwjntxb34ju81&pinnedLogTimestamp=2021-09-21T08:55:21.499883Z&scrollTimestamp=2021-09-21T08:55:21.508000000Z

See this issue https://github.com/camunda-cloud/zeebe/issues/7873#issuecomment-923805847

**Comment by npepinpe** [comment]
@deepthidevaki or @Zelldon , please take this one. Under the assumption we do corrupt the log, then we should fix it before the release. If we can't, we'll turn off the feature flag, but let's try that for now.

**Comment by Zelldon** [comment]
I think this is due to https://github.com/camunda-cloud/zeebe/issues/7873#issuecomment-923861963
