### ISSUE TITLE
`TestZbctlWithInsecureGateway/TestCommonCommands` is unstable

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8284]
**Summary**
The test `TestZbctlWithInsecureGateway/TestCommonCommands` from the go client fails because the client get's an unexpected response from the gateway.

- How often does the test fail? Rarely but more than once
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

<details><summary>Go client test failure</summary>
<pre>
[2021-11-25T17:24:39.136Z] === Failed
[2021-11-25T17:24:39.136Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job (10.01s)
[2021-11-25T17:24:39.136Z]         --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job (10.01s)
[2021-11-25T17:24:39.136Z]             main_test.go:217: failed to reformat JSON: invalid character 'E' looking for beginning of value
[2021-11-25T17:24:39.136Z] 
[2021-11-25T17:24:39.136Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway/TestCommonCommands (32.55s)
[2021-11-25T17:24:39.136Z]     --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands (32.55s)
[2021-11-25T17:24:39.136Z] 
[2021-11-25T17:24:39.136Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway (100.16s)
</pre>
</details>

**Hypotheses**

I think this is likely to be an issue on Zeebe's side, not on the client. The netty error message might indicate that we are mixing up TLS and plaintext connections.

**Logs**

<details><summary>Related zeebe logs</summary>
<pre>
2021-11-26 11:29:32.841 [] [grpc-default-worker-ELG-5-2] INFO 
      io.grpc.netty.NettyServerTransport.connections - Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 16030101050100010103032abdac323fe0d688fcb2fa9306
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108) ~[netty-codec-http2-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306) ~[netty-codec-http2-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239) [netty-codec-http2-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) [netty-codec-http2-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.70.Final.jar:4.1.70.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
</pre>
</details>

**Comment by Zelldon** [comment]
https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/develop/1282/testReport/junit/github/com_camunda-cloud_zeebe_clients_go_cmd_zbctl/Verify___Test__Go____TestZbctlWithInsecureGateway_TestCommonCommands_empty_activate_job/
```
Error Message
Failed
Stacktrace
=== RUN   TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job
    main_test.go:217: failed to reformat response JSON: invalid character 'E' looking for beginning of value
        Erroneous JSON: []
        --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job (10.01s)
```

**Comment by Zelldon** [comment]
We need to iterate over the current failure output, see here https://github.com/camunda-cloud/zeebe/pull/8376#discussion_r778158937

**Comment by Zelldon** [comment]
@npepinpe what if we get an resource exhausted ? We don't handle this here https://github.com/camunda-cloud/zeebe/blob/develop/clients/go/cmd/zbctl/main_test.go#L204

Which means we try to format the json which then fail?

**Comment by Zelldon** [comment]
Can reproduce it with:

```
fmtJSON, err := reformatJSON([]byte("Error: Resource Exhausted" +
                    ""))
```

```
=== RUN   TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job
    main_test.go:217: failed to reformat response JSON: invalid character 'E' looking for beginning of value
        Erroneous JSON: {
          "jobs": []
        }
```

**Comment by npepinpe** [comment]
Yeah I assumed it happened on any error, but I wanted to see the actual error :smile: Resource exhausted sounds like a plausible case where you'd still want to pass this specific test :+1:

**Comment by Zelldon** [comment]
@npepinpe now we have proof:

```
] === Failed

[2022-01-13T09:39:08.825Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job (10.01s)

[2022-01-13T09:39:08.825Z]     main_test.go:217: failed to reformat response JSON: invalid character 'E' looking for beginning of value

[2022-01-13T09:39:08.825Z]         Erroneous JSON: Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded

[2022-01-13T09:39:08.825Z]         --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands/empty_activate_job (10.01s)
```

**Comment by npepinpe** [comment]
Seems deadline exceeded is the most common case. We could add a bit of timeout for this, as we do in a lot of our Java tests.

**Comment by npepinpe** [comment]
So this isn't as simple as I initially thought. We can't just slap a time out on this, because - surprise! - we're already waiting for the result. I'm a little confused, in fact, as to why this times out. One case was activating jobs when there are none to activate - this should poll each partition (there's only 1) and return nothing. It times out after 10s as that's the default time out in Zeebe for job activation, which means the broker never answered there was nothing. I find that a bit hard to believe, honestly. I'll add a bit more improvements - like dumping the container logs on failure, and we do another round of wait and see :see_no_evil:
