### ISSUE TITLE
Node ID bigger than Cluster size

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/zeebe#8342]
**Describe the bug**

Broker startup has failed because the node ID got the value 2, though the cluster size is 1.
The cluster plan that was used is: `83593107-8231-421d-8e2f-925911142136`

This occurred on the DEV stage with a test cluster plan. It might be a non-issue where people were playing around with strange configurations, but I wanted too make sure it's nothing major.

It occurred on one cluster. The issue for this cluster was resolved by migrating it to a different cluster plan.

**To Reproduce**

Unknown for now

**Expected behavior**

The broker should start without issue.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) [spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.4.jar:2.5.4]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:58) [camunda-cloud-zeebe-1.2.1.jar:1.2.1]
Caused by: java.lang.IllegalArgumentException: Node id 2 needs to be non negative and smaller then cluster size 1.
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:81) ~[zeebe-broker-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:59) ~[zeebe-broker-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:52) ~[zeebe-broker-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.broker.StandaloneBroker.createSystemContextInBaseDirectory(StandaloneBroker.java:96) ~[camunda-cloud-zeebe-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:64) ~[camunda-cloud-zeebe-1.2.1.jar:1.2.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.4.jar:2.5.4]
	... 5 more
```

</p>
</details>

<details><summary>Logs</summary>
<p>

```
I 2021-12-08T08:46:37.112630761Z KUBERNETES_SERVICE_PORT_HTTPS=443 
I 2021-12-08T08:46:37.112645791Z ELASTICSEARCH_PORT_9200_TCP_PORT=9200 
I 2021-12-08T08:46:37.112651910Z ZEEBE_LOG_LEVEL=debug 
I 2021-12-08T08:46:37.112659569Z KUBERNETES_SERVICE_PORT=443 
I 2021-12-08T08:46:37.112666032Z ELASTICSEARCH_PORT_9200_TCP_ADDR=10.100.6.55 
I 2021-12-08T08:46:37.112671818Z TASKLIST_SERVICE_WEBAPP_PORT_8081_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.112676807Z ATOMIX_LOG_LEVEL=info 
I 2021-12-08T08:46:37.112681866Z ELASTICSEARCH_SERVICE_HOST=10.100.6.55 
I 2021-12-08T08:46:37.112687003Z ZEEBE_BROKER_NETWORK_HOST=0.0.0.0 
I 2021-12-08T08:46:37.112693243Z ZEEBE_GATEWAY_SERVICE_SERVICE_PORT_HTTP=9600 
I 2021-12-08T08:46:37.112698280Z TASKLIST_SERVICE_WEBAPP_PORT_8080_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.112703549Z HOSTNAME=zeebe-2 
I 2021-12-08T08:46:37.112708992Z ZEEBE_GATEWAY_SERVICE_PORT_26500_TCP=tcp://10.100.11.202:26500 
I 2021-12-08T08:46:37.112715343Z ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=zeebe-2.zeebe-broker-service.733bffc4-5a81-415b-8867-a75aa6fccb21-zeebe.svc.cluster.local 
I 2021-12-08T08:46:37.112741901Z ZEEBE_BROKER_GATEWAY_ENABLE=false 
I 2021-12-08T08:46:37.112747877Z ELASTICSEARCH_PORT_9114_TCP_PORT=9114 
I 2021-12-08T08:46:37.112753046Z JAVA_HOME=/usr/local/openjdk-11 
I 2021-12-08T08:46:37.112758229Z ELASTICSEARCH_PORT_9114_TCP_ADDR=10.100.6.55 
I 2021-12-08T08:46:37.112763453Z ZEEBE_BROKER_CLUSTER_NODEID=2 
I 2021-12-08T08:46:37.112768445Z ZEEBE_SERVICE_SERVICE_PORT_GATEWAY=26500 
I 2021-12-08T08:46:37.112774032Z ZEEBE_GATEWAY_SERVICE_SERVICE_HOST=10.100.11.202 
I 2021-12-08T08:46:37.112779615Z ZEEBE_SERVICE_PORT_26500_TCP=tcp://10.100.1.112:26500 
I 2021-12-08T08:46:37.112785357Z TASKLIST_SERVICE_WEBAPP_PORT_8080_TCP_PORT=8080 
I 2021-12-08T08:46:37.112790540Z ZEEBE_SERVICE_PORT_26500_TCP_ADDR=10.100.1.112 
I 2021-12-08T08:46:37.112796032Z ELASTICSEARCH_PORT=tcp://10.100.6.55:9200 
I 2021-12-08T08:46:37.112801297Z OPERATE_SERVICE_WEBAPP_PORT_8081_TCP_ADDR=10.100.13.136 
I 2021-12-08T08:46:37.112806540Z ZEEBE_GATEWAY_SERVICE_PORT_9600_TCP_PORT=9600 
I 2021-12-08T08:46:37.112811885Z ZEEBE_BROKER_CLUSTER_CLUSTERNAME=733bffc4-5a81-415b-8867-a75aa6fccb21-zeebe 
I 2021-12-08T08:46:37.112819119Z ZEEBE_GATEWAY_SERVICE_SERVICE_PORT_GATEWAY=26500 
I 2021-12-08T08:46:37.112832486Z PWD=/usr/local/zeebe 
I 2021-12-08T08:46:37.112837667Z CAMUNDA_CLOUD_ORGANIZATION_ID=3cddfdff-9656-4cf7-a97f-9d874de46d65 
I 2021-12-08T08:46:37.112848713Z ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-0.zeebe-broker-service.733bffc4-5a81-415b-8867-a75aa6fccb21-zeebe.svc.cluster.local:26502, 
I 2021-12-08T08:46:37.112854473Z OPERATE_SERVICE_WEBAPP_SERVICE_PORT_HTTP=8080 
I 2021-12-08T08:46:37.112859963Z ZEEBE_GATEWAY_SERVICE_PORT_26500_TCP_ADDR=10.100.11.202 
I 2021-12-08T08:46:37.112864752Z ELASTICSEARCH_PORT_9200_TCP=tcp://10.100.6.55:9200 
I 2021-12-08T08:46:37.112869837Z ZEEBE_GATEWAY_SERVICE_PORT_26500_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.112874848Z ELASTICSEARCH_PORT_9114_TCP=tcp://10.100.6.55:9114 
I 2021-12-08T08:46:37.112880079Z K8S_NAMESPACE=733bffc4-5a81-415b-8867-a75aa6fccb21-zeebe 
I 2021-12-08T08:46:37.112885017Z TASKLIST_SERVICE_WEBAPP_SERVICE_PORT_METRICS=8081 
I 2021-12-08T08:46:37.112889993Z ZEEBE_SERVICE_SERVICE_PORT=9600 
I 2021-12-08T08:46:37.112895082Z HOME=/root 
I 2021-12-08T08:46:37.112900312Z LANG=C.UTF-8 
I 2021-12-08T08:46:37.112915406Z OPERATE_SERVICE_WEBAPP_PORT_8081_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.112920758Z ZEEBE_BROKER_GATEWAY_MONITORING_ENABLED=true 
I 2021-12-08T08:46:37.112925864Z KUBERNETES_PORT_443_TCP=tcp://10.100.0.1:443 
I 2021-12-08T08:46:37.112931215Z ZEEBE_SERVICE_PORT_9600_TCP_ADDR=10.100.1.112 
I 2021-12-08T08:46:37.112936663Z ZEEBE_GATEWAY_SERVICE_PORT_9600_TCP_ADDR=10.100.11.202 
I 2021-12-08T08:46:37.112942583Z OPTIMIZE_SERVICE_WEBAPP_SERVICE_PORT=8090 
I 2021-12-08T08:46:37.112947918Z OPTIMIZE_SERVICE_WEBAPP_SERVICE_HOST=10.100.15.90 
I 2021-12-08T08:46:37.112953274Z OPERATE_SERVICE_WEBAPP_PORT_8080_TCP_PORT=8080 
I 2021-12-08T08:46:37.112958747Z ZEEBE_LOG_STACKDRIVER_SERVICEVERSION=1.2.1 
I 2021-12-08T08:46:37.112963840Z TASKLIST_SERVICE_WEBAPP_PORT_8081_TCP_ADDR=10.100.15.52 
I 2021-12-08T08:46:37.112969252Z OPERATE_SERVICE_WEBAPP_PORT_8080_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.112974066Z K8S_POD_NAME=zeebe-2 
I 2021-12-08T08:46:37.112979240Z TASKLIST_SERVICE_WEBAPP_SERVICE_HOST=10.100.15.52 
I 2021-12-08T08:46:37.112984375Z ZEEBE_SERVICE_PORT=tcp://10.100.1.112:9600 
I 2021-12-08T08:46:37.112989608Z ELASTICSEARCH_SERVICE_PORT_METRICS=9114 
I 2021-12-08T08:46:37.112995240Z ZEEBE_STANDALONE_GATEWAY=false 
I 2021-12-08T08:46:37.113000727Z ZEEBE_SERVICE_SERVICE_PORT_METRICS=9600 
I 2021-12-08T08:46:37.113005783Z ZEEBE_SERVICE_PORT_9600_TCP_PORT=9600 
I 2021-12-08T08:46:37.113011306Z SPRING_CONFIG_LOCATION=classpath:/,file:./config/zeebe.cfg.yaml 
I 2021-12-08T08:46:37.113024460Z ZEEBE_SERVICE_PORT_26500_TCP_PORT=26500 
I 2021-12-08T08:46:37.113029569Z ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2 
I 2021-12-08T08:46:37.113035036Z ZEEBE_SERVICE_PORT_26500_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113040884Z TASKLIST_SERVICE_WEBAPP_SERVICE_PORT_HTTP=8080 
I 2021-12-08T08:46:37.113046755Z TASKLIST_SERVICE_WEBAPP_PORT_8080_TCP_ADDR=10.100.15.52 
I 2021-12-08T08:46:37.113052475Z ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=1 
I 2021-12-08T08:46:37.113058111Z TASKLIST_SERVICE_WEBAPP_PORT=tcp://10.100.15.52:8080 
I 2021-12-08T08:46:37.113063492Z ELASTICSEARCH_SERVICE_PORT_HTTP=9200 
I 2021-12-08T08:46:37.113068581Z TASKLIST_SERVICE_WEBAPP_PORT_8081_TCP_PORT=8081 
I 2021-12-08T08:46:37.113073580Z OPTIMIZE_SERVICE_WEBAPP_SERVICE_PORT_HTTP=8090 
I 2021-12-08T08:46:37.113078600Z ZEEBE_LOG_STACKDRIVER_SERVICENAME=zeebe 
I 2021-12-08T08:46:37.113083872Z OPTIMIZE_SERVICE_WEBAPP_PORT=tcp://10.100.15.90:8090 
I 2021-12-08T08:46:37.113089269Z ZEEBE_GATEWAY_SERVICE_PORT_9600_TCP=tcp://10.100.11.202:9600 
I 2021-12-08T08:46:37.113094569Z ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=1 
I 2021-12-08T08:46:37.113100365Z JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data/java_started_1638953197.hprof 
I 2021-12-08T08:46:37.113107236Z TASKLIST_SERVICE_WEBAPP_PORT_8081_TCP=tcp://10.100.15.52:8081 
I 2021-12-08T08:46:37.113112137Z OPERATE_SERVICE_WEBAPP_PORT_8080_TCP=tcp://10.100.13.136:8080 
I 2021-12-08T08:46:37.113117934Z ZEEBE_GATEWAY_SERVICE_PORT_9600_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113122983Z ELASTICSEARCH_PORT_9114_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113128473Z TASKLIST_SERVICE_WEBAPP_SERVICE_PORT=8080 
I 2021-12-08T08:46:37.113134430Z SHLVL=1 
I 2021-12-08T08:46:37.113140052Z ZEEBE_GATEWAY_SERVICE_SERVICE_PORT=9600 
I 2021-12-08T08:46:37.113145893Z OPTIMIZE_SERVICE_WEBAPP_PORT_8090_TCP_PORT=8090 
I 2021-12-08T08:46:37.113151492Z OPERATE_SERVICE_WEBAPP_PORT_8081_TCP_PORT=8081 
I 2021-12-08T08:46:37.113157118Z KUBERNETES_PORT_443_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113183880Z ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED=true 
I 2021-12-08T08:46:37.113204272Z OPERATE_SERVICE_WEBAPP_PORT_8080_TCP_ADDR=10.100.13.136 
I 2021-12-08T08:46:37.113211462Z KUBERNETES_PORT_443_TCP_ADDR=10.100.0.1 
I 2021-12-08T08:46:37.113217126Z ZB_HOME=/usr/local/zeebe 
I 2021-12-08T08:46:37.113222528Z ZEEBE_SERVICE_PORT_9600_TCP=tcp://10.100.1.112:9600 
I 2021-12-08T08:46:37.113228159Z ZEEBE_SERVICE_PORT_9600_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113233659Z ZEEBE_GATEWAY_SERVICE_PORT=tcp://10.100.11.202:9600 
I 2021-12-08T08:46:37.113238917Z OPTIMIZE_SERVICE_WEBAPP_PORT_8090_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113244195Z OPERATE_SERVICE_WEBAPP_SERVICE_PORT_METRICS=8081 
I 2021-12-08T08:46:37.113249567Z TASKLIST_SERVICE_WEBAPP_PORT_8080_TCP=tcp://10.100.15.52:8080 
I 2021-12-08T08:46:37.113254806Z KUBERNETES_SERVICE_HOST=10.100.0.1 
I 2021-12-08T08:46:37.113260257Z ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=zeebe-2.zeebe-broker-service.733bffc4-5a81-415b-8867-a75aa6fccb21-zeebe.svc.cluster.local 
I 2021-12-08T08:46:37.113265823Z OPERATE_SERVICE_WEBAPP_SERVICE_PORT=8080 
I 2021-12-08T08:46:37.113272260Z KUBERNETES_PORT=tcp://10.100.0.1:443 
I 2021-12-08T08:46:37.113277466Z KUBERNETES_PORT_443_TCP_PORT=443 
I 2021-12-08T08:46:37.113282525Z ELASTICSEARCH_SERVICE_PORT=9200 
I 2021-12-08T08:46:37.113287792Z ELASTICSEARCH_PORT_9200_TCP_PROTO=tcp 
I 2021-12-08T08:46:37.113293388Z PATH=/usr/local/zeebe/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
I 2021-12-08T08:46:37.113298977Z ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0 
I 2021-12-08T08:46:37.113304351Z OPERATE_SERVICE_WEBAPP_SERVICE_HOST=10.100.13.136 
I 2021-12-08T08:46:37.113316870Z ZEEBE_GATEWAY_SERVICE_PORT_26500_TCP_PORT=26500 
I 2021-12-08T08:46:37.113322538Z OPERATE_SERVICE_WEBAPP_PORT=tcp://10.100.13.136:8080 
I 2021-12-08T08:46:37.113327841Z ZEEBE_LOG_APPENDER=Stackdriver 
I 2021-12-08T08:46:37.113332762Z ZEEBE_SERVICE_SERVICE_HOST=10.100.1.112 
I 2021-12-08T08:46:37.113337909Z OPTIMIZE_SERVICE_WEBAPP_PORT_8090_TCP_ADDR=10.100.15.90 
I 2021-12-08T08:46:37.113343028Z OPTIMIZE_SERVICE_WEBAPP_PORT_8090_TCP=tcp://10.100.15.90:8090 
I 2021-12-08T08:46:37.113347875Z JAVA_VERSION=11.0.12 
I 2021-12-08T08:46:37.113353251Z OPERATE_SERVICE_WEBAPP_PORT_8081_TCP=tcp://10.100.13.136:8081 
I 2021-12-08T08:46:37.113358885Z _=/usr/bin/env 
I 2021-12-08T08:46:38.682580084Z   ______  ______   ______   ____    ______     ____    _____     ____    _  __  ______   _____   
I 2021-12-08T08:46:38.682615261Z  |___  / |  ____| |  ____| |  _ \  |  ____|   |  _ \  |  __ \   / __ \  | |/ / |  ____| |  __ \  
I 2021-12-08T08:46:38.682620182Z     / /  | |__    | |__    | |_) | | |__      | |_) | | |__) | | |  | | | ' /  | |__    | |__) | 
I 2021-12-08T08:46:38.682624597Z    / /   |  __|   |  __|   |  _ <  |  __|     |  _ <  |  _  /  | |  | | |  <   |  __|   |  _  /  
I 2021-12-08T08:46:38.682628213Z   / /__  | |____  | |____  | |_) | | |____    | |_) | | | \ \  | |__| | | . \  | |____  | | \ \  
I 2021-12-08T08:46:38.682631645Z  /_____| |______| |______| |____/  |______|   |____/  |_|  \_\  \____/  |_|\_\ |______| |_|  \_\ 
I 2021-12-08T08:46:38.682635996Z                                                                                                  
I 2021-12-08T08:46:38.753006Z Starting StandaloneBroker v1.2.1 using Java 11.0.12 on zeebe-2 with PID 7 (/usr/local/zeebe/lib/camunda-cloud-zeebe-1.2.1.jar started by root in /usr/local/zeebe) 
D 2021-12-08T08:46:38.777879Z Running with Spring Boot v2.5.4, Spring v5.3.10 
I 2021-12-08T08:46:38.779377Z No active profile set, falling back to default profiles: default 
I 2021-12-08T08:46:39.944014Z Tomcat initialized with port(s): 9600 (http) 
I 2021-12-08T08:46:39.954810Z Initializing ProtocolHandler ["http-nio-0.0.0.0-9600"] 
I 2021-12-08T08:46:39.955857Z Starting service [Tomcat] 
I 2021-12-08T08:46:39.956503Z Starting Servlet engine: [Apache Tomcat/9.0.52] 
I 2021-12-08T08:46:40.037449Z Initializing Spring embedded WebApplicationContext 
I 2021-12-08T08:46:40.038075Z Root WebApplicationContext: initialization completed in 1210 ms 
I 2021-12-08T08:46:40.726936Z Exposing 4 endpoint(s) beneath base path '/actuator' 
I 2021-12-08T08:46:40.747998Z Starting ProtocolHandler ["http-nio-0.0.0.0-9600"] 
I 2021-12-08T08:46:40.761360Z Tomcat started on port(s): 9600 (http) with context path '' 
I 2021-12-08T08:46:40.774464Z Started StandaloneBroker in 2.497 seconds (JVM running for 3.652) 
D 2021-12-08T08:46:40.782452Z Initializing system with base path /usr/local/zeebe 
I 2021-12-08T08:46:40.810669Z 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
E 2021-12-08T08:46:40.825024Z Application run failed 
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 1.2.1
 - Configuration: `ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=1`

**Comment by npepinpe** [comment]
Most likely the same as https://github.com/camunda-cloud/zeebe/issues/6277. No need to look into this for now, I'll try to figure out who could fix this - console or SREs - and hopefully it doesn't come up again.
