### ISSUE TITLE
MultiPartitionRecoveryTest#shouldCreateProcessInstanceOnAllPartitionsAfterRestart is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#8445]
**Summary**

- How often does the test fail?
  - Once this case, but we've often had this test resulting in unparseable XML, so might be related
- Does it block your work?
  - No
- Do we suspect that it is a real failure?
  - Not really, but can't say

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1757)
	at app//io.camunda.zeebe.test.util.record.RecordingExporter$RecordIterator.hasNext(RecordingExporter.java:265)
	at java.base@17.0.1/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1855)
	at java.base@17.0.1/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.1/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.1/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at app//io.camunda.zeebe.test.util.stream.StreamWrapper.exists(StreamWrapper.java:67)
	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.util.GrpcClientRule.lambda$waitUntilDeploymentIsDone$3(GrpcClientRule.java:102)
	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.util.GrpcClientRule$$Lambda$1178/0x0000000100828c60.getAsBoolean(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:36)
	at app//io.camunda.zeebe.test.util.TestUtil$$Lambda$921/0x000000010064c000.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:89)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation$$Lambda$924/0x000000010064c6b0.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:179)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:149)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:88)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at app//io.camunda.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.util.GrpcClientRule.waitUntilDeploymentIsDone(GrpcClientRule.java:98)
	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.startup.MultiPartitionRecoveryTest.deploy(MultiPartitionRecoveryTest.java:132)
	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.startup.MultiPartitionRecoveryTest.shouldCreateProcessInstanceOnAllPartitionsAfterRestart(MultiPartitionRecoveryTest.java:94)
</pre>
</details>

**Hypotheses**

None yet.

**Logs**

https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/dependabot%2Fmaven%2Fnet.bytebuddy-byte-buddy-1.12.6/1/ - this build is kept forever, so please delete it when closing the issue.

Logs are attached as a gist as they're too big to fit a comment: [logs](https://gist.github.com/npepinpe/261d0830de6f5fd828427846db1f42fb)

**Comment by deepthidevaki** [comment]
Test is flaky due to bug https://github.com/camunda-cloud/zeebe/issues/8525
