### ISSUE TITLE
Failed to finish replaying records because recovery future was already completed before

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#8528]
**Describe the bug**

[An error](https://console.cloud.google.com/errors/CJjHssPP_4fnEQ?service=zeebe&time=P30D&refresh=off&project=camunda-cloud-240911) was reported on a cluster running 1.3.0-alpha3 in production. The error did not effect the cluster's health.

Interestingly, the same error happened on 3 different partitions (13, 20, 48) on the same broker (5) around the same time.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value 41842325
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:184) ~[zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:191) ~[zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:191) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
Caused by: java.lang.RuntimeException: Failed to replay records. [snapshot-position: 41842325, last-read-record-position: 41842326, last-replayed-event-position: -1]
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value 41842325
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.complete(CompletableActorFuture.java:164) ~[zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.onRecordsReplayed(ReplayStateMachine.java:237) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:180) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	... 6 more
```

</p>
</details>

<details><summary>Logs of partition 13 just before the error</summary>
 <p>

```
2022-01-02 08:21:52.733 CET "Transition to LEADER on term 52 - transitioning LogStorage"
2022-01-02 08:21:52.733 CET "Transition to LEADER on term 52 - transitioning LogStream"
2022-01-02 08:21:52.733 CET "Detected 'HEALTHY' components. The current health status of components: [Broker-5-LogStream-13{status=HEALTHY}, ZeebePartition-13{status=HEALTHY}, raft-partition-partition-13{status=HEALTHY}]"
2022-01-02 08:21:52.734 CET "Transition to LEADER on term 52 - transitioning ZeebeDb"
2022-01-02 08:21:52.734 CET "Transition to LEADER on term 52 - transitioning QueryService"
2022-01-02 08:21:52.734 CET "Transition to LEADER on term 52 - transitioning StreamProcessor"
2022-01-02 08:21:52.876 CET "RaftServer{raft-partition-partition-13} - Received successful append response higher term (53 > 52) from DefaultRaftMember{id=0, type=ACTIVE, updated=2021-12-15T22:02:02.411Z}, implying there is a new leader - transitioning to follower"
2022-01-02 08:21:52.884 CET "RaftServer{raft-partition-partition-13} - Transitioning to FOLLOWER"
2022-01-02 08:21:52.884 CET "Transition to FOLLOWER on term 53 requested."
2022-01-02 08:21:52.884 CET "Partition role transitioning from LEADER to FOLLOWER in term 53"
2022-01-02 08:21:52.884 CET "Received cancel signal for transition to LEADER on term 52"
2022-01-02 08:21:52.890 CET "Configured log appender back pressure at partition 13 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled"
2022-01-02 08:21:52.892 CET "Recovering state of partition 13 from snapshot"
2022-01-02 08:21:52.892 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4714f5ef)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@f1bdcd6, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@77997600, configuration: Configuration(false)]"
2022-01-02 08:21:52.894 CET "Recovered state of partition 13 from snapshot at position 41842325"
2022-01-02 08:21:52.894 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@bd53571)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@6b8e1269, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3aa28ea2, configuration: Configuration(false)]"
2022-01-02 08:21:52.895 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@637c680)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@246b058a, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3f6d4634, configuration: Configuration(false)]"
2022-01-02 08:21:52.895 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@111408e5)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@29afdf81, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@5594c86b, configuration: Configuration(false)]"
2022-01-02 08:21:52.896 CET "Processor starts replay of events. [snapshot-position: 41842325, replay-mode: PROCESSING]"
2022-01-02 08:21:52.896 CET "Detected 'HEALTHY' components. The current health status of components: [Broker-5-LogStream-13{status=HEALTHY}, ZeebePartition-13{status=HEALTHY}, raft-partition-partition-13{status=HEALTHY}, Broker-5-StreamProcessor-13{status=HEALTHY}]"
2022-01-02 08:21:52.896 CET "Cancelling transition to LEADER on term 52"
2022-01-02 08:21:52.896 CET "Paused replay for partition 13"
2022-01-02 08:21:52.896 CET "Resumed replay for partition 13"
2022-01-02 08:21:52.896 CET "ZeebePartition-13 recovered, marking it as healthy"
2022-01-02 08:21:52.896 CET "Processor finished replay at event position 41842326"
2022-01-02 08:21:52.896 CET "Detected 'HEALTHY' components. The current health status of components: [Broker-5-LogStream-13{status=HEALTHY}, ZeebePartition-13{status=HEALTHY}, raft-partition-partition-13{status=HEALTHY}, Broker-5-StreamProcessor-13{status=HEALTHY}]"
2022-01-02 08:21:52.896 CET "Processor finished replay at event position 41842326"
2022-01-02 08:21:52.896 CET "Prepare transition from FOLLOWER on term 53 to FOLLOWER"
2022-01-02 08:21:52.897 CET "Prepare transition from FOLLOWER on term 53 to FOLLOWER - preparing ExporterDirector"
2022-01-02 08:21:52.897 CET "Prepare transition from FOLLOWER on term 53 to FOLLOWER - preparing SnapshotDirector"
2022-01-02 08:21:52.897 CET "Prepare transition from FOLLOWER on term 53 to FOLLOWER - preparing StreamProcessor"
2022-01-02 08:21:52.898 CET "Actor Broker-5-StreamProcessor-13 failed in phase STARTED."
```

</p>
</details>

**Initial investigation**
I already spend some time trying to figure out what happened here:

This broker was transitioning to leader for partition 13. After installing the snapshot, it started replay, which was shortly paused and then resumed. 

The ReplayStateMachine is replaying the next event, but there is no next record and the StreamProcessorMode is PROCESSING. So it ends the replay with [onRecordsReplayed](https://github.com/camunda-cloud/zeebe/blob/1.3.0-alpha3/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java#L180). This [completes the recoveryFuture with the last source event position](https://github.com/camunda-cloud/zeebe/blob/1.3.0-alpha3/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java#L237). However, this future was already completed with value 41842325, which is an Illegal State. This failure to complete the future is [caught by the ReplayStateMachine](https://github.com/camunda-cloud/zeebe/blob/1.3.0-alpha3/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java#L186). As a failure it again tries to [complete this future (this time exceptionally)](https://github.com/camunda-cloud/zeebe/blob/1.3.0-alpha3/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java#L191), which is again not possible. Naturally, completing the future exceptionally fails with the same IllegalStateException as before. However, this time it is not caught which is why it popped up in the Error Reporting Tool.

> Failed to replay records. [snapshot-position: 41842325, last-read-record-position: 41842326, last-replayed-event-position: -1]

Note the message that it tries to complete the future exceptionally with. The snapshot position is the same as the value of the completed future. This is because the last source event position is set to the snapshot position at the start of recovery. It then goes on to replay the first next event.

[The logs](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.namespace_name%3D%22a3e99e0f-6283-4c21-80f7-5e7f9b9dafff-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-5%22%0AjsonPayload.context.partitionId%3D%2213%22%0Atimestamp%3E%222022-01-02T07:21:52.733389465Z%22%0Atimestamp%3C%222022-01-02T07:21:55.384604952Z%22;timeRange=2022-01-02T06:52:22.901Z%2F2022-01-02T07:52:22.901Z;pinnedLogId=2022-01-02T07:21:52.898005635Z%2Fzy7xehcr5o8afykl;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning;cursorTimestamp=2022-01-02T07:21:52.898005635Z?project=camunda-cloud-240911) show that replay was finished twice, around the same time:
>2022-01-02 08:21:52.896 CET "Processor finished replay at event position 41842326"
>2022-01-02 08:21:52.896 CET "Detected 'HEALTHY' components. The current health status of components: [Broker-5-LogStream-13{status=HEALTHY}, ZeebePartition-13{status=HEALTHY}, raft-partition-partition-13{status=HEALTHY}, Broker-5-StreamProcessor-13{status=HEALTHY}]"
>2022-01-02 08:21:52.896 CET "Processor finished replay at event position 41842326"

What I don't understand is: 
- How can it be that onRecordsCompleted tried to complete an already completed future? 
- Why is it starting to replay if it's already in the PROCESSING mode? Or why is it in PROCESSING mode at the start of replay?

**Comment by npepinpe** [comment]
But to clarify, the only impact here was a longer time to a processing leader?

**Comment by npepinpe** [comment]
As the impact is low, and it only happened once, I would leave it in the backlog.

**Comment by korthout** [comment]
>But to clarify, the only impact here was a longer time to a processing leader?

Not even that. This broker was cancelling its transition to leader. Practically 10 seconds after the error a new leader was found, but that was gonna happen regardless of the error.

**Comment by koevskinikola** [comment]
The issue happened again in a production cluster ([internal Google doc](https://drive.google.com/file/d/1p7rKYk7QsF05QpDfBuY52VEp_eZ_CQbH/view?usp=sharing)).

**Comment by lenaschoenburg** [comment]
Occurred again on 8.6.2: https://console.cloud.google.com/errors/detail/CKLTyeONkqLZCg;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod-lhr

**Comment by koevskinikola** [comment]
We got another one:
- Env: SaaS Dev
- Version: `8.9.0-SNAPSHOT`
- GCP log viewer: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.namespace_name%3D%22fe7314d2-3b0d-4ab6-83a7-ab890b4e44cf-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-2%22;pinnedLogId=2025-10-29T22:53:16.796375070Z%2F803xjamdhkqt3raz;cursorTimestamp=2025-10-29T22:53:16.796440035Z;startTime=2025-10-29T22:23:46.796Z;endTime=2025-10-29T23:23:46.796Z?project=camunda-saas-dev)
- Downloaded GCP logs: [internal link](https://drive.google.com/file/d/1bPfusTuaEh543fj3AOj4S88DkjhrEdwj/view?usp=sharing)

**Comment by remcowesterhoud** [comment]
Another occurence on `8.8.3`

```
 java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value [lastProcessedPosition: 3421, lastWrittenPosition: 3422]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:219)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:226)
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:195)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
Caused by: java.lang.RuntimeException: Failed to replay records. [snapshot-position: 3421, last-read-record-position: 3422, last-replayed-event-position: -1]
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value [lastProcessedPosition: 3421, lastWrittenPosition: 3422]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.complete(CompletableActorFuture.java:199)
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.onRecordsReplayed(ReplayStateMachine.java:262)
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:184)
	... 6 more 
```

**Comment by koevskinikola** [comment]
Another occurrence of this one:
- Env: Camunda SaaS
- Version: Zeebe `8.8-SNAPSHOT`
- [GCP internal logs link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22568c2700-3b2a-40b5-869d-c88ab5a09433-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;pinnedLogId=2026-02-12T21:40:26.327529750Z%2Fj9u2605q17p5wj8r;cursorTimestamp=2026-02-12T21:40:26.327565769Z;startTime=2026-02-12T21:10:56.327Z;endTime=2026-02-12T22:10:56.327Z?project=camunda-saas-int-chaos)
- [GCP downloaded links (internal)](https://drive.google.com/file/d/1hGkaz7LhVQacmzXjFJ5hhghV8zqKYp7c/view?usp=sharing)
