### ISSUE TITLE
Writing a `DecisionEvaluationResult` fails because `EvaluatedInput.inputName()` is null

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8909]
**Describe the bug**

Error: https://console.cloud.google.com/errors/detail/CIHdh_bs1r-nDQ;service=zeebe;time=P7D?project=camunda-cloud-240911

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:39) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:35) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.msgpack.property.StringProperty.setValue(StringProperty.java:30) ~[zeebe-msgpack-value-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.protocol.impl.record.value.decision.EvaluatedInputRecord.setInputName(EvaluatedInputRecord.java:46) ~[zeebe-protocol-impl-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.addInputToEvaluationEvent(BpmnDecisionBehavior.java:296) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.lambda$addDecisionToEvaluationEvent$8(BpmnDecisionBehavior.java:282) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.addDecisionToEvaluationEvent(BpmnDecisionBehavior.java:281) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.lambda$writeDecisionEvaluationEvent$7(BpmnDecisionBehavior.java:242) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.writeDecisionEvaluationEvent(BpmnDecisionBehavior.java:240) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.lambda$evaluateDecision$3(BpmnDecisionBehavior.java:114) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.evaluateDecision(BpmnDecisionBehavior.java:109) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.lambda$onActivate$0(BusinessRuleTaskProcessor.java:89) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.onActivate(BusinessRuleTaskProcessor.java:89) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate(BusinessRuleTaskProcessor.java:40) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate(BusinessRuleTaskProcessor.java:21) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:128) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:127) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:297) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:287) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:252) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:212) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:188) ~[zeebe-workflow-engine-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.4.0-alpha2.jar:1.4.0-alpha2] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 1.4.0-alpha2

**Comment by npepinpe** [comment]
@korthout - could we have a look at this and see if this is a quick fix for 1.4?

**Comment by korthout** [comment]
Thanks for reporting @oleschoenburg.

I think this is a bug. Alternatively, it could have been a case where we simply want to add a deployment validator, but I think we want to support this case. 

I've created a fix for it, but I'm keeping it in draft until I've confirmed that we consider this a valid decision model.

**Comment by korthout** [comment]
As far as I can tell, this is indeed a bug.

For inputs, the spec does not define names. Labels can be attached but are optional. We use the label as a way to display names for inputs in the modeler. Naming inputs is something Camunda does but is not officially part of the DMN spec.

For outputs, names are part of the DMN spec. They are only mandatory for decision tables with multiple outputs. So single output decision tables can leave out the output name.

So in my opinion, the case above is a bug and it is fixed by allowing inputs and outputs without names (or labels). I'll mark the PR as ready for review.
